### PR TITLE
[ENTESB-11971] Fixing configuration of AWS DDB

### PR DESCRIPTION
**Pull request by Delawen**
Using dataList instead of the string type to make sure we have input type text.

### CODE REVIEW

**Comment by KurtStam** [comment]
@Delawen Is the field some sort of list? Or do you really want a simple `text`?

**Comment by Delawen** [comment]
I want a simple text with suggestions/auto-complete

**Comment by KurtStam** [comment]
Ah so you will have a list of options that will be tried to autocomplete? If so then dataType seems appropriate.

**Comment by Delawen** [comment]
No merging... but the failing build was not due to this PR.

**Comment by heiko-braun** [comment]
@Delawen What ENTESB does this refer to?

**Comment by squakez** [comment]
@Delawen you need to rebase master to pull a fix for the mongodb test failure: https://github.com/syndesisio/syndesis/pull/6885

**Comment by Delawen** [comment]
> @Delawen What ENTESB does this refer to?

None at the time. Now I guess ENTESB-11971

**Comment by heiko-braun** [comment]
@Delawen Does it need to go into 1.8.x?

**Comment by Delawen** [comment]
Unless the regression was solved some other way on 1.8, yes.

**Comment by squakez** [comment]
Regression was brought on master by dependabot, is not affecting `1.8.x`.

**Comment by christophd** [comment]
@heiko-braun yes this should go to 1.8.x

**Comment by christophd** [comment]
@squakez is talking about the mongodb failure which is not affecting 1.8.x. but the changes maria made on the connector should to to 1.8.x

**Pull request merged**
