### PR TITLE
feat(ui): embed Atlasmap React UI

### PR DESCRIPTION
**Pull request by riccardo-forina**
Adds a Technology Preview switch in the Data Mapping page to toggle between the Angular and React version of Atlasmap. The toggle selection is persisted between refreshes, but defaults to the Angular version of the app for the moment. Demo:

Kapture 2020-04-24 at 10 35 57

The mapping document passed to Atlasmap is also logged in the browser's dev console. This allows in combination with [Atlasmap's storybook](https://atlasmap.netlify.app/) to quickly debug the integration between Syndesis and Atlasmap like this:

c4e5a27fa37bc75f385919c6f0d18cd6

(All the `.yalc` stuff is temporary and will be removed when https://github.com/atlasmap/atlasmap/pull/1961 lands)

Closes ENTESB-12080

### CODE REVIEW

**Comment by riccardo-forina** [comment]
Tech preview switch removed, as well as the angular version of Atlasmap

**Comment by igarashitm** [comment]
@riccardo-forina nice to have atlasmap 2.0.0 directly! can you also update to 2.0.0 in `app/pom.xml` and `/app/integration/bom/pom.xml`?

**Comment by riccardo-forina** [comment]
Done but I had to skip this validation step that seemed wrong to me:

```
➜  syndesis git:(atlasmap-integration) ✗ git commit -m "chore(app): also update atlasmap engine to 2.0.0"
husky > pre-commit (node v10.16.0)
$ lint-staged
✔ Preparing...
⚠ Running tasks...
  ↓ No staged files match *.go [SKIPPED]
  ❯ Running tasks for *.{java,properties,xml}
    ✖ ./tools/misc/format-license.sh /Users/riccardoforina/Code/syndesis/app/
integration/bom/pom.xml /Users/riccardoforina/Code/syndesis/app/pom.xml [ENOE
NT]
    ◼ [Function] git ...
  ↓ No staged files match install/operator/pkg/generator/assets/** [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ ./tools/misc/format-license.sh /Users/riccardoforina/Code/syndesis/app/integration/bom/pom.xml /Users/riccardoforina/Code/syndesis/app/pom.xml failed without output (ENOENT).
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "pre-commit:lint-staged" exited with 1.
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by igarashitm** [comment]
Hmm I don't know what is the problem with this... @riccardo-forina you can stay with 2.0.0-M4 for this PR and update to 2.0.0 GA separately once this is solved.
```
[INFO] --- duplicate-finder-maven-plugin:1.3.0:check (basepom.default) @ integration-runtime ---
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Checking test classpath
[WARNING] Found duplicate (but equal) classes in [io.atlasmap:atlas-dfdl-core:2.0.0, io.atlasmap:atlas-xml-core:2.0.0]:
[WARNING]   io.atlasmap.xml.core.AtlasXmlConstants
[WARNING]   io.atlasmap.xml.core.AtlasXmlNamespaceContext
[WARNING]   io.atlasmap.xml.core.XmlComplexTypeFactory
[WARNING]   io.atlasmap.xml.core.XmlFieldReader
[WARNING]   io.atlasmap.xml.core.XmlFieldTransformer
[WARNING]   io.atlasmap.xml.core.XmlFieldWriter
[WARNING]   io.atlasmap.xml.core.XmlIOHelper
[WARNING]   io.atlasmap.xml.core.XmlPath
[WARNING] Found duplicate (but equal) classes in [org.apache.daffodil:daffodil-io_2.12:2.6.0, org.apache.daffodil:daffodil-lib_2.12:2.6.0]:
[WARNING]   org.apache.daffodil.exceptions.AssertMacros
[WARNING]   org.apache.daffodil.exceptions.SDEMacros
[WARNING]   org.apache.daffodil.io.IOMacros
[WARNING]   org.apache.daffodil.util.LoggerMacros
[WARNING]   org.apache.daffodil.util.TimeTrackerMacros
[WARNING] Found duplicate classes/resources in test classpath.

Yes atlas-dfdl-core was added in 2.0.0, and it depends on atlas-xml-core. But I don't know what this exactly means and how I should fix...

**Comment by igarashitm** [comment]
@riccardo-forina @gashcrumb CircleCI build passed! ready to merge?

**Comment by riccardo-forina** [comment]
Pinging @gashcrumb, I'll not pull the trigger :P

**Comment by tplevko** [comment]
It seems this wasn't backported to 1.10.x

**Comment by riccardo-forina** [comment]
Uhm, right. I'll do that manually.

**Comment by riccardo-forina** [comment]
https://github.com/syndesisio/syndesis/pull/8456

Backport here.

**Pull request merged**
