### PR TITLE
chore: Update to AtlasMap 2.1.2

### PR DESCRIPTION
**Pull request by igarashitm**
https://issues.redhat.com/browse/ENTESB-15520
Succeeding #9263

Release Notes:
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.2
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.1
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.0

### CODE REVIEW

**Comment by igarashitm** [comment]
retest this please

**Comment by igarashitm** [comment]
@asmigala This error looks weird as jsonEnumFields does exist on JsonComplexType here - https://github.com/atlasmap/atlasmap/blob/atlasmap-2.1.2/lib/modules/json/model/src/main/java/io/atlasmap/json/v2/JsonComplexType.java#L28
Doesn't it have old atlas-json-model dependency?
> [2021-01-19 03:53:41,154] [1;31mERROR[0;39m [io.syndesis.qe.endpoint.util.RetryingInvocationBuilder:278] Exception raised during method invocation, will retry 1 more times
javax.ws.rs.client.ResponseProcessingException: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "jsonEnumFields" (class io.atlasmap.json.v2.JsonComplexType), not marked as ignorable (18 known properties: "jsonFields", "path", "arrayDimensions", "primitive", "name", "uri", "value", "index", "docId", "fieldType", "format", "collectionType", "arraySize", "actions", "required", "typeName", "status", "userCreated"])
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 47, column: 31] (through reference chain: io.atlasmap.json.v2.JsonInspectionResponse["jsonDocument"]->io.atlasmap.json.v2.JsonDocument["fields"]->io.atlasmap.v2.Fields["field"]->java.util.ArrayList[0]->io.atlasmap.json.v2.JsonComplexType["jsonEnumFields"])
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:199)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:508)
	at io.syndesis.qe.endpoint.util.RetryingInvocationBuilder.retryingInvoke(RetryingInvocationBuilder.java:275)
	at io.syndesis.qe.endpoint.util.RetryingInvocationBuilder.post(RetryingInvocationBuilder.java:171)
	at io.syndesis.qe.endpoint.AtlasmapEndpoint.inspectJson(AtlasmapEndpoint.java:42)
	at io.syndesis.qe.datamapper.AtlasMapperGenerator.processDataShapeIntoFields(AtlasMapperGenerator.java:122)
	at io.syndesis.qe.datamapper.AtlasMapperGenerator.lambda$processPrecedingSteps$1(AtlasMapperGenerator.java:87)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at io.syndesis.qe.datamapper.AtlasMapperGenerator.processPrecedingSteps(AtlasMapperGenerator.java:84)
	at io.syndesis.qe.datamapper.AtlasMapperGenerator.getAtlasMappingStep(AtlasMapperGenerator.java:243)
	at io.syndesis.qe.IntegrationHandler.processMapperSteps(IntegrationHandler.java:183)
	at io.syndesis.qe.IntegrationHandler.createIntegrationFromGivenStepsWithStateAndValidation(IntegrationHandler.java:67)
	at io.syndesis.qe.IntegrationHandler.createIntegrationWithoutValidation(IntegrationHandler.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
....

**Comment by asmigala** [comment]
@igarashitm yes, the QE test suite has an older dependency, unfortunately we don't have an easy way to run a PR version of the test suite against a syndesis PR, I'm currently running it on my machine and will get back to you once it's finished

**Comment by zregvart** [comment]
This'll need a rebase to pick up #9231

**Comment by igarashitm** [comment]
#9295 takes over

**Pull request closed without merging**
