### PR TITLE
Update container images

### PR DESCRIPTION
**Pull request by claudio4j**
Following upgrade to some images in downstream, it is important
to update images on upstream

### CODE REVIEW

**Comment by zregvart** [comment]
retest this please

**Review by zregvart — APPROVED** [review]
LGTM, perhaps we can wait for the smoke tests to pass?

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
our jenkins master got rate limited, I added auth and hopefully it will be ok :crossed_fingers:

**Comment by avano** [comment]
retest this please

**Pull request merged**
