### PR TITLE
fix: added vertical max height and scroll TEIIDTOOLS-784

### PR DESCRIPTION
**Pull request by indraraj**
- Jira Issue https://issues.jboss.org/browse/TEIIDTOOLS-784

- With this pr add the vertical scroll property to ConnectionSchemaList with max-height of 45em.

- UI Look & feel 
Screenshot from 2019-10-29 20-42-55

### CODE REVIEW

**Comment by mdrillin** [comment]
I put a comment on the jira.  We might need to adjust the vertical height - I'm getting double scrollbars

**Comment by indraraj** [comment]
Hey @mcoker can you please suggest some better way to provide height here so that it fits on the screen without creating the outer page section scrollable.

**Comment by mcoker** [comment]
Hey @indraraj my apologies for missing your initial comment. I took a look at this and I think using the existing page stucture, you can do this with the following CSS.

```
.integration-editor-layout__contentInner,
.integration-editor-layout__contentInner > .pf-c-page__main-section,
.integration-editor-layout__contentInner > .pf-c-page__main-section > .pf-c-card,
.views-import-layout-card-body {
  max-height: 100%;
}

.views-import-layout-card-body {
  min-height: 0;
  display: flex;
  flex-direction: column;
}

.views-import-layout-card-body > .list-view-toolbar {
  margin-left: 0;
  margin-right: 0;
}

.views-import-layout-card-body > .view-info-list > .list-group {
  margin-bottom: 0;
}
```

Note, I was only able to test this in the chrome browser. When I try to visit syndesis staging in a browser other than chrome, I get this error message. Can you test this in the other supported browser, or let me know why I'm getting this error in the other browsers?

Screen Shot 2019-11-20 at 1 38 47 PM

cc @dlabaj

**Comment by gashcrumb** [comment]
> When I try to visit syndesis staging in a browser other than chrome, I get this error message.

Is that firefox?  I wonder if you still have the service worker installed, looks like you can go to about:debugging#workers and double-check that there isn't one installed for staging, if there is it can be disabled.  I'd also check the 'Storage' tab and clear the cache and the oauth cookie if it still persists.  Firefox seems to work alright here for me against staging.

**Comment by mcoker** [comment]
@gashcrumb that did it, thanks! The changes look good in Firefox, too.

**Pull request merged**
