### PR TITLE
[Backport 1.10.x] Kafka connector TLS support

### PR DESCRIPTION
**Pull request by squakez**
Porting few commits and changing some import to be compliant with Camel 2.x

### CODE REVIEW

**Comment by squakez** [comment]
I am having UI failures even after merging to the latest `1.10.x`

@syndesisio/ui any idea how to fix this?

**Comment by kahboom** [comment]
I've kicked off a new build (seemed to fix it the last time this happened), but this theoretically should have been fixed with this: https://github.com/syndesisio/syndesis/pull/7913

**Comment by squakez** [comment]
> I've kicked off a new build (seemed to fix it the last time this happened), but this theoretically should have been fixed with this: #7913

Thanks @kahboom , it seems that those commits have not yet ported to `1.10.x`. I can pick them into this PR too if there is no other cascade commits they need.

**Comment by gashcrumb** [comment]
Also I found when working with the DV folks changing that setting from 2 to
1 improved reliability even more.

**Pull request merged**
