### PR TITLE
fix: #600 Integrations - unify "Add a Step"/"Choose a Step" labels

### PR DESCRIPTION
**Pull request by mastepan**
[#600 Integrations - unify "Add a Step"/"Choose a Step" labels](https://github.com/syndesisio/syndesis/issues/600)

### CODE REVIEW

**Comment by rhuss** [comment]
@syndesisio/uxd Does this change looks good to you ?

**Comment by TovaCohen** [comment]
I'm just seeing this change now and if there is a good internal reason for it, I won't get in the way. 
But I think there is a subtle difference between Choose and Add, that was helpful.
The user must choose the start connection and the finish connection, but adding a step is optional. With the start and finish connections in place, a prompt to Choose a Step slightly implies that it is required. Using a different verb, Add, might make it more apparent that having a step in an integration is not required. It's subtle and maybe the benefit of always using "Choose" is greater.

**Comment by dongniwang** [comment]
> The user must choose the start connection and the finish connection, but adding a step is optional. With the start and finish connections in place, a prompt to Choose a Step slightly implies that it is required. 

I agreed with what Tova suggested here. Keeping the "add" would help users understand that the steps are optional. 

cc: @amysueg @sjcox-rh

**Comment by amysueg** [comment]
+1 to @dongniwang @TovaCohen

**Comment by rhuss** [comment]
I'm not complete sure whether the 'optional' argument applies to this screenshot as the user *already* has chosen to add a step (otherwise he wouldn't be on this screen). Now she has to *chose* the concrete step. 

I agree with @mastepan that its not much different to a connection at this point (when a user alread has selected to add a step)

It's perfectly fine when here its about "adding" a step:

image

But when the user clicked on "add step" the next screen should be about choosing which step:

image

So for consistencies sake, I'm really for changing "Add" to "Choose" on this screen.

> I agreed with what Tova suggested here. Keeping the "add" would help users understand that the steps are optional.

At this point, the step is not optional anymore. She can cancel this action but if she proceeds she has to choose a step.

**Comment by TovaCohen** [comment]
It seems inconsistent to me for the user to click "Add a step" and then get a page that says "Choose a Step", but it's not a big deal. I stand by my original comment. But there are good arguments on both sides. Someone just needs to make a decision. :-)

**Comment by rhuss** [comment]
> It seems inconsistent to me for the user to click "Add a step" and then get a page that says "Choose a Step", but it's not a big deal

Yeah, I see the point. But then, the "Choose a Step" on the left column in the screenshot is also inappropriate, isn't it?

Actually, I also think it's not a big deal. So let's @kcbabo decide ;-)

**Comment by kcbabo** [comment]
'Choose' is fine with me.

**Comment by dsimansk** [comment]
@rhuss should it have been merged eventually? I was under impression that more votes favoured current state.

**Pull request merged**
