### PR TITLE
Pin operator image to 1.7.1-20190617

### PR DESCRIPTION
**Pull request by lgarciaaco**

### CODE REVIEW

**Comment by lgarciaaco** [comment]
@zregvart ^^

**Comment by zregvart** [comment]
Link to the [daily releases](https://ci.fabric8.io/view/syndesis/job/syndesis-release-daily/) if you're not aware of them.

**Comment by lgarciaaco** [comment]
> Link to the [daily releases](https://ci.fabric8.io/view/syndesis/job/syndesis-release-daily/) if you're not aware of them.

There is no rush on building this tbh ...

**Comment by zregvart** [comment]
It's automated, runs every day...

**Pull request merged**
