### PR TITLE
fix: Update template to use links from locale (backport)

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes [ENTESB-12868](https://issues.redhat.com/browse/ENTESB-12868)

And also updates the commit to point to the 7.6 URLs

### CODE REVIEW

**Comment by gashcrumb** [comment]
So one follow on question, [this line](https://github.com/syndesisio/syndesis/pull/7800/files#diff-38d54cc1ec6b270563c94153f356a568R93) and [this line](https://github.com/syndesisio/syndesis/pull/7800/files#diff-38d54cc1ec6b270563c94153f356a568R86) need to be updated for the product branch, where does that happen?

**Comment by zregvart** [comment]
@gashcrumb on the [product fork](https://github.com/jboss-fuse/syndesis/tree/1.9.x)

**Comment by gashcrumb** [comment]
@zregvart cool, thanks!  I'll open a PR against that with the right locale entries.

**Comment by gashcrumb** [comment]
Created [this PR](https://github.com/jboss-fuse/syndesis/pull/13) with those changes.

**Pull request merged**
