### PR TITLE
fix(basicfilter): rework UI for bordered sections and sticky top condition

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/syndesisio/syndesis/issues/6336 and https://github.com/syndesisio/syndesis/issues/6222

@seanforyou23  there is an empty label for the trash icon. Should that have text, or can we remove it if it's empty?

### CODE REVIEW

**Comment by gashcrumb** [comment]
I'm liking it!  I wonder if we should go a similar route with the conditional flow page as well, that also uses the auto-form array functionality including the up/down arrows.  At the moment I've naturally kinda hosed it up with my pf4 changes, so it's lookin' like:

image

**Comment by mcoker** [comment]
@dongniwang what do you think about the conditional flow page UI in @gashcrumb's comment?

**Comment by dongniwang** [comment]
@mcoker @gashcrumb - conditional flow design update in progress, I can definitely try the border treatment. I would go ahead with what we have for the basic filter right now. The conditional flow page needs some review.

**Comment by mcoker** [comment]
@gashcrumb is there anything else you'd like to see in this PR?

**Pull request merged**
