### PR TITLE
Fixes #4702: Fixed public api proxy serviceaccount clusterrolebinding namespace

### LINKED ISSUE #4702: Public API proxy template doesn't set permission for service account
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have a clean minishift instance with syndesis:
`syndesis minishift --full-reset --install --project syndesis --openshift-version 3.11.0`

I create template for public [endpoint](https://github.com/syndesisio/syndesis/tree/master/install#create-template-for-public-api-endpoint)
`oc create -f install/support/syndesis-public-oauth-proxy.yml`

After that, I create a new app
```
oc new-app --template=syndesis-public-oauthproxy \
    -p PUBLIC_API_ROUTE_HOSTNAME= public-syndesis.192.168.42.4.nip.io \
    -p OPENSHIFT_PROJECT=$(oc project -q) \
    -p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client) \
    -p SAR_PROJECT=$(oc project -q)
```
The output looks good:
```
--> Deploying template "syndesis/syndesis-public-oauthproxy" to project syndesis

     syndesis-public-oauthproxy
     ---------
     Syndesis Public API is deployed to public-syndesis.192.168.42.4.nip.io.

     * With parameters:
        * PUBLIC_API_ROUTE_HOSTNAME=public-syndesis.192.168.42.4.nip.io
        * OpenShift project to deploy into=syndesis
        * OpenShift project to be used to authenticate the user against=syndesis
        * OPENSHIFT_OAUTH_CLIENT_SECRET=<TOKEN>
        * OAUTH_PROXY_TAG=v1.1.0
        * Syndesis Image Registry=docker.io
        * Image Stream Namespace=
        * OAuth Cookie Secret=ENHr4n1W4DEnYOliL4LdCGXuu0WBkunj # generated

--> Creating resources ...
    serviceaccount "syndesis-public-oauthproxy" created
    rolebinding.authorization.openshift.io "syndesis-public-oauthproxy:viewers" created
    clusterrolebinding.authorization.openshift.io "syndesis-syndesis-auth-delegator" created
    imagestream.image.openshift.io "syndesis-public-oauthproxy" created
    service "syndesis-public-oauthproxy" created
    route.route.openshift.io "syndesis-public-api" created
    deploymentconfig.apps.openshift.io "syndesis-public-oauthproxy" created
--> Success
    Access your application via route 'public-syndesis.192.168.42.4.nip.io' 
    Run 'oc status' to view your app.
```
But the syndesis-public-oauthproxy contains error in log:
```
unable to load OpenShift configuration: unable to retrieve authentication information for tokens: tokenreviews.authentication.k8s.io is forbidden: User "system:serviceaccount:syndesis:syndesis-public-oauthproxy" cannot create tokenreviews.authentication.k8s.io at the cluster scope: no RBAC policy matched
```
It is strange because the [delegator](https://github.com/syndesisio/syndesis/blob/master/install/support/syndesis-public-oauth-proxy.yml#L75) is successfully created according to log.

After add  permission manually
```
oc adm policy add-cluster-role-to-user system:auth-delegator system:serviceaccount:syndesis:syndesis-public-oauthproxy
```
the public-oauthproxy pod works.

For the reproducing this, it is necessary to have a fresh minishift instance. (--full-reset)

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by heiko-braun** [comment]
@dhirajsb Why is this file static and the other oauth proxy generated? See https://github.com/syndesisio/syndesis/blob/master/install/generator/04-syndesis-oauth-proxy.yml.mustache#L145 for instance

**Comment by dhirajsb** [comment]
Due to it's cluster level permissions requirement we decided to not make this part of the default Syndesis install process. Hence it's a standalone template on its own.

**Comment by gashcrumb** [comment]
Can I click the button?

**Comment by heiko-braun** [comment]
What happened to the bot? @gashcrumb gfeel free to merge.

**Comment by dhirajsb** [comment]
I did it! I clicked the button! Yee-haw!

**Pull request merged**
