### PR TITLE
refactor: move from FMP to KOMP 

### PR DESCRIPTION
**Pull request by zregvart**
This replaces the Fabric8 Maven Plugin with Kubernetes/Openshift Maven
Plugin.

We used to use `fabric8.mode` to determine which mode of the FMP plugin
will be used: kubernetes - where a Docker daemon builds images;
openshift - when we use the OpenShift builds to build images and push
them to image streams (used in development). The KOMP doesn't have a
mode setting, the mode is implicitly determined by which plugin is used
i.e. `kubernetes-maven-plugin` or `openshift-maven-plugin`, for this
reason we no longer have one `image` Maven profile, but two, aptly named
`image:kubernetes` and `image:openshift`. Both activated by setting
`build.mode` property to either `kubernetes` or `openshift`. This is
handled automatically by the `syndesis` CLI.

In the UI mode, an issue was hit in using OpenShift build mode with a
Dockerfile and an inline assembly:
```
Failed to execute the build: Unable to build the image using the
OpenShift build service: This image has already been flattened, you can
only flatten the image once
```
For this reason the inline assembly was replaced with a symbolic link
from the Docker context directory (`app/ui-react/docker`) to the build
artifacts directory `app/ui-react/syndesis/build`. A better solution
should be found for this.

Since the TAR file generated by the plugin serving as the context sent
for the build is now prefixed with `maven`, `Dockerfile`s were updated
to reflect that.

Ref. issues.redhat.com/browse/ENTESB-17787

Also includes:

refactor: remove unused project generator bits (1bf7665b)

This removes unused and unmaintained project generator bits that at some
point might have made some sense but were never enabled and thus fell
out of maintenance.

### CODE REVIEW

**Comment by zregvart** [comment]
Would be good to get to the bottom of the image build with KOMP in UI, let this not postpone 1.13.0.

**Comment by zregvart** [comment]
We need [JKube 1.6.0](https://github.com/eclipse/jkube/milestone/13) to get the version with the issue https://github.com/eclipse/jkube/issues/1115 resolved.

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
@mkralik3 for this PR to pass the smoke tests we need to change the Maven property from `fabric8.mode` to `build.mode`, otherwise the Maven profile to build the images will not be activated and no images will be built. Perhaps as a start we can keep `-Dfabric8.mode=kubernetes` and add `-Dbuild.mode=kubernetes` until this is merged?

**Comment by mkralik3** [comment]
@zregvart  I have changed build mode https://gitlab.cee.redhat.com/jboss-fuse-qe/syndesis-pipeline-library/-/commit/7ccda4d28e7c384c87e1f257e5faf988993f947c but building S2I failed, 
https://fuse-7x-jenkins-csb-fuse-qe.apps.ocp4.prod.psi.redhat.com/job/fuse-7.11-syndesis-tests-PR-ENG/100/console

**Comment by mkralik3** [comment]
@zregvart an integration has the following error after start:
```
[mkralik@matejntb syndesis-qe]$ oc logs -f i-integration1-2-tmtbx
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/project-0.1-SNAPSHOT.jar 
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalArgumentException: Invalid source directory /deployments/data/syndesis/loader
	at org.springframework.boot.loader.PropertiesLauncher.<init>(PropertiesLauncher.java:158)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:465)
Caused by: java.lang.IllegalArgumentException: Invalid source directory /deployments/data/syndesis/loader
	at org.springframework.boot.loader.archive.ExplodedArchive.<init>(ExplodedArchive.java:73)
	at org.springframework.boot.loader.PropertiesLauncher.getProperty(PropertiesLauncher.java:426)
	at org.springframework.boot.loader.PropertiesLauncher.getProperty(PropertiesLauncher.java:395)
	at org.springframework.boot.loader.PropertiesLauncher.initializeProperties(PropertiesLauncher.java:173)
	at org.springframework.boot.loader.PropertiesLauncher.<init>(PropertiesLauncher.java:153)
	... 1 more
```

**Comment by zregvart** [comment]
Thanks @mkralik3, I've tested with one extension anticipating an issue with that, but I haven't tested without any :confused: So I need to cover that case as well and make sure that the `/deployments/data/syndesis/loader` directory is present in all cases.

**Comment by mkralik3** [comment]
https://fuse-7x-jenkins-csb-fuse-qe.apps.ocp4.prod.psi.redhat.com/job/fuse-7.11-syndesis-tests-PR-ENG/120/
There is one failed test that the integration was not triggered in time. I will check it manually.

**Comment by zregvart** [comment]
> [fuse-7x-jenkins-csb-fuse-qe.apps.ocp4.prod.psi.redhat.com/job/fuse-7.11-syndesis-tests-PR-ENG/120](https://fuse-7x-jenkins-csb-fuse-qe.apps.ocp4.prod.psi.redhat.com/job/fuse-7.11-syndesis-tests-PR-ENG/120/) There is one failed test that the integration was not triggered in time. I will check it manually.

Thanks @mkralik3, much appreciated. I noticed that and looked at the results, but I could not see anything obviously wrong.

**Comment by mkralik3** [comment]
np,
It looks that `IntegrationsMetricsEndpoint` (/metrics/integrations)  `IntegrationMetricsSummary.getMessages().intValue()` returns 0 even though the messages go through the integration according to the activity log in UI. I need to debug it for more info.

**Comment by mkralik3** [comment]
@zregvart 
It looks that there is a problem with metrics. The activity tab shows some messages but metrics tab is empty,
image
also the metrics endpoint returns 0 for getMessages as I mentioned in the previous comment
image

**Comment by zregvart** [comment]
Thanks @mkralik3 I'll have a deeper look into metrics then.

**Comment by zregvart** [comment]
retest this please

**Pull request merged**
