### PR TITLE
chore: drop pf-react dep from ApiConnectorListView

### PR DESCRIPTION
**Pull request by kahboom**
Epic: [ENTESB-12896](https://issues.redhat.com/browse/ENTESB-12896)

Drop `patternfly-react` (PF3) dependency to instead use `@patternfly/react-core` (PF4) stuffs in the `ApiConnectorListView` component.

Screenshot:

Screenshot 2020-02-11 15 37 28 copy

Includes:
- ListView => DataList
- Tooltip
- Empty state
- Icon, etc.

Note: Similar to https://github.com/syndesisio/syndesis/pull/7863 had some issues capturing the tooltip.

### CODE REVIEW

**Comment by gashcrumb** [comment]
Can we do anything with the button alignment in the toolbar?

**Comment by kahboom** [comment]
I can just look into migrating the `ListViewToolbar` as well if it'd fix it, or do you mean some temporary workaround like manually aligning them?

**Comment by gashcrumb** [comment]
I guess either way you want to go, if migrating the toolbar seems easy enough go for it.

**Comment by kahboom** [comment]
Just checked and it's an experimental feature, probably better suited for a separate PR and some advice from UXD. I'll push up a fix for the button alignment.

**Comment by gashcrumb** [comment]
yep, sounds good to me, thanks!

**Comment by kahboom** [comment]
This last commit fixes it, but I had to remove the tooltip (which doesn't seem to be working either way) from the toolbar. To be fair, I don't understand why we'd have a tooltip in both the toolbar and the main body, for the same exact button.

**Pull request merged**
