### PR TITLE
chore: Update to AtlasMap 2.1.3

### PR DESCRIPTION
**Pull request by igarashitm**
https://issues.redhat.com/browse/ENTESB-15520
Succeeding #9287, #9263

Release Notes:
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.3
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.2
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.1
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.0

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by igarashitm** [comment]
retest this please

**Comment by igarashitm** [comment]
retest this please

**Comment by igarashitm** [comment]
@mcada don't I have a permission to rerun the test?

**Comment by mcada** [comment]
@jsafarik can you please check our whitelist?

**Comment by jsafarik** [comment]
@mcada @igarashitm There shouldn't be any whitelist, probably the build is not accessible due to a big amount of PR tests.

**Comment by igarashitm** [comment]
retest this please

**Comment by igarashitm** [comment]
It still fails with old atlasmap dependency, same with https://github.com/syndesisio/syndesis/pull/9287#issuecomment-762733525
@asmigala what do we do for this one?

**Comment by asmigala** [comment]
@igarashitm hi, I ran into an issue when running the QE tests for API Provider with the new atlas map version, it's a simple api provider integration loading data from database, when querying the resulting API, I get 

```
expected:<[[{"id":1,"completed":null,"task":"task1"},{"id":2,"completed":null,"task":"task2"}]]> but was:<[{"httpResponseCode":200,"category":"SERVER_ERROR","message":"Errors: [Failed to write field value into target document: For input string: \"null\": docId='i-MS7LrrAg6SVUZn7lOF2z', path='/body<>/completed'], ","error":"atlas_error"}]>
```

This does not happen on 1.12.x without this PR.


Looking at the exported integrations, I see a difference:
1.12:
```
"atlasmapping": "{\"AtlasMapping\":{\"jsonType\":\"io.atlasmap.v2.AtlasMapping\",\"dataSource\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonDataSource\",\"id\":\"-MS7I5VqXb0ypYux44dd\",\"uri\":\"atlas:json:-MS7I5VqXb0ypYux44dd\",\"dataSourceType\":\"SOURCE\"},{\"jsonType\":\"io.atlasmap.json.v2.JsonDataSource\",\"id\":\"i-MS7Hoe8MyTPrYgcBvXZz\",\"uri\":\"atlas:json:i-MS7Hoe8MyTPrYgcBvXZz\",\"dataSourceType\":\"TARGET\",\"template\":null}],\"mappings\":{\"mapping\":[{\"jsonType\":\"io.atlasmap.v2.Mapping\",\"id\":\"mapping.733193\",\"inputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"id\",\"path\":\"/<>/id\",\"fieldType\":\"INTEGER\",\"docId\":\"-MS7I5VqXb0ypYux44dd\",\"userCreated\":false}],\"outputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"id\",\"path\":\"/body<>/id\",\"fieldType\":\"INTEGER\",\"docId\":\"i-MS7Hoe8MyTPrYgcBvXZz\",\"userCreated\":false}]},{\"jsonType\":\"io.atlasmap.v2.Mapping\",\"id\":\"mapping.148758\",\"inputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"completed\",\"path\":\"/<>/completed\",\"fieldType\":\"INTEGER\",\"docId\":\"-MS7I5VqXb0ypYux44dd\",\"userCreated\":false}],\"outputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"completed\",\"path\":\"/body<>/completed\",\"fieldType\":\"INTEGER\",\"docId\":\"i-MS7Hoe8MyTPrYgcBvXZz\",\"userCreated\":false}]},{\"jsonType\":\"io.atlasmap.v2.Mapping\",\"id\":\"mapping.580513\",\"inputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"task\",\"path\":\"/<>/task\",\"fieldType\":\"STRING\",\"docId\":\"-MS7I5VqXb0ypYux44dd\",\"userCreated\":false}],\"outputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"task\",\"path\":\"/body<>/task\",\"fieldType\":\"STRING\",\"docId\":\"i-MS7Hoe8MyTPrYgcBvXZz\",\"userCreated\":false}]}]},\"name\":\"UI.0\",\"lookupTables\":{\"lookupTable\":[]},\"constants\":{\"constant\":[]},\"properties\":{\"property\":[]}}}"
```

#9295 
```
"atlasmapping": "{\"AtlasMapping\":{\"jsonType\":\"io.atlasmap.v2.AtlasMapping\",\"dataSource\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonDataSource\",\"id\":\"-MS7M8lU9MLEVgIy3pTS\",\"name\":\"2 - SQL Result\",\"description\":\"Result of SQL [SELECT * FROM todo]\",\"uri\":\"atlas:json:-MS7M8lU9MLEVgIy3pTS\",\"dataSourceType\":\"SOURCE\"},{\"jsonType\":\"io.atlasmap.json.v2.JsonDataSource\",\"id\":\"i-MS7LrrAg6SVUZn7lOF2z\",\"name\":\"3 - Response\",\"description\":\"API response payload\",\"uri\":\"atlas:json:i-MS7LrrAg6SVUZn7lOF2z\",\"dataSourceType\":\"TARGET\",\"template\":null}],\"mappings\":{\"mapping\":[{\"jsonType\":\"io.atlasmap.v2.Mapping\",\"id\":\"mapping.459765\",\"inputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"id\",\"path\":\"/<>/id\",\"fieldType\":\"BIG_INTEGER\",\"docId\":\"-MS7M8lU9MLEVgIy3pTS\",\"userCreated\":false}],\"outputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"id\",\"path\":\"/body<>/id\",\"fieldType\":\"BIG_INTEGER\",\"docId\":\"i-MS7LrrAg6SVUZn7lOF2z\",\"userCreated\":false}]},{\"jsonType\":\"io.atlasmap.v2.Mapping\",\"id\":\"mapping.352061\",\"inputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"completed\",\"path\":\"/<>/completed\",\"fieldType\":\"BIG_INTEGER\",\"docId\":\"-MS7M8lU9MLEVgIy3pTS\",\"userCreated\":false}],\"outputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"completed\",\"path\":\"/body<>/completed\",\"fieldType\":\"BIG_INTEGER\",\"docId\":\"i-MS7LrrAg6SVUZn7lOF2z\",\"userCreated\":false}]},{\"jsonType\":\"io.atlasmap.v2.Mapping\",\"id\":\"mapping.252216\",\"inputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"task\",\"path\":\"/<>/task\",\"fieldType\":\"STRING\",\"docId\":\"-MS7M8lU9MLEVgIy3pTS\",\"userCreated\":false}],\"outputField\":[{\"jsonType\":\"io.atlasmap.json.v2.JsonField\",\"name\":\"task\",\"path\":\"/body<>/task\",\"fieldType\":\"STRING\",\"docId\":\"i-MS7LrrAg6SVUZn7lOF2z\",\"userCreated\":false}]}]},\"name\":\"UI.0\",\"lookupTables\":{\"lookupTable\":[]},\"constants\":{\"constant\":[]},\"properties\":{\"property\":[]}}}"
```

**Comment by asmigala** [comment]
@igarashitm another issue found in API provider tests:

When the same source is mapped to two different targets, the new datamapper behaves in a different way:

1.12:
image

#9295 : 
image


The output from the particular integration was `{"id":42,"task":"42"}` and now is `{"id":42}`

The two mappings in question:

1.12:
```
{
  "AtlasMapping": {
    "jsonType": "io.atlasmap.v2.AtlasMapping",
    "dataSource": [
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "i-MS86pBr-khT1EOFrhyYz",
        "uri": "atlas:json:i-MS86pBr-khT1EOFrhyYz",
        "dataSourceType": "SOURCE"
      },
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "i-MS86pBr-khT1EOFrhyZz",
        "uri": "atlas:json:i-MS86pBr-khT1EOFrhyZz",
        "dataSourceType": "TARGET",
        "template": null
      }
    ],
    "mappings": {
      "mapping": [
        {
          "jsonType": "io.atlasmap.v2.Mapping",
          "id": "mapping.260725",
          "inputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "id",
              "path": "/parameters/id",
              "fieldType": "INTEGER",
              "docId": "i-MS86pBr-khT1EOFrhyYz",
              "userCreated": false
            }
          ],
          "outputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "id",
              "path": "/body/id",
              "fieldType": "INTEGER",
              "docId": "i-MS86pBr-khT1EOFrhyZz",
              "userCreated": false
            }
          ]
        },
        {
          "jsonType": "io.atlasmap.v2.Mapping",
          "id": "mapping.333092",
          "inputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "id",
              "path": "/parameters/id",
              "fieldType": "INTEGER",
              "docId": "i-MS86pBr-khT1EOFrhyYz",
              "userCreated": false
            }
          ],
          "outputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "task",
              "path": "/body/task",
              "fieldType": "STRING",
              "docId": "i-MS86pBr-khT1EOFrhyZz",
              "userCreated": false
            }
          ]
        }
      ]
    },
    "name": "UI.0",
    "lookupTables": {
      "lookupTable": []
    },
    "constants": {
      "constant": []
    },
    "properties": {
      "property": []
    }
  }
}
```

#9295 : 
```
{
  "AtlasMapping": {
    "jsonType": "io.atlasmap.v2.AtlasMapping",
    "dataSource": [
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "i-MS81JTRg6SVUZn7lOFrz",
        "name": "1 - Request",
        "description": "API request payload",
        "uri": "atlas:json:i-MS81JTRg6SVUZn7lOFrz",
        "dataSourceType": "SOURCE"
      },
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "i-MS81JTRg6SVUZn7lOFsz",
        "name": "2 - Response",
        "description": "API response payload",
        "uri": "atlas:json:i-MS81JTRg6SVUZn7lOFsz",
        "dataSourceType": "TARGET",
        "template": null
      }
    ],
    "mappings": {
      "mapping": [
        {
          "jsonType": "io.atlasmap.v2.Mapping",
          "id": "mapping.145526",
          "inputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "id",
              "path": "/parameters/id",
              "fieldType": "BIG_INTEGER",
              "docId": "i-MS81JTRg6SVUZn7lOFrz",
              "userCreated": false,
              "actions": [
                {
                  "delimiter": " ",
                  "@type": "Split"
                }
              ]
            }
          ],
          "outputField": [
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "id",
              "path": "/body/id",
              "fieldType": "BIG_INTEGER",
              "docId": "i-MS81JTRg6SVUZn7lOFsz",
              "userCreated": false,
              "index": 0
            },
            {
              "jsonType": "io.atlasmap.json.v2.JsonField",
              "name": "task",
              "path": "/body/task",
              "fieldType": "STRING",
              "docId": "i-MS81JTRg6SVUZn7lOFsz",
              "userCreated": false,
              "index": 1
            }
          ]
        }
      ]
    },
    "name": "UI.0",
    "lookupTables": {
      "lookupTable": []
    },
    "constants": {
      "constant": []
    },
    "properties": {
      "property": []
    }
  }
}
```

**Comment by igarashitm** [comment]
Cc @pleacu
https://user-images.githubusercontent.com/9480152/106166505-8800c680-618c-11eb-868c-545d4121e10f.png could happen if you add "task" to the existing mapping instead of creating a new mapping. It just depends on which icon you click in the UI. But the weird thing is that it shows "One to One" while it has to show "One to Many (Split)". I tried with atlasmap standalone but it didn't reproduce, two of "One to One" from a same source field could be successfully created, and also "One to Many (Split)". Reload didn't break it either. Are the all atlasmap dependencies same version?

**Comment by igarashitm** [comment]
I managed to get to the root cause of https://github.com/syndesisio/syndesis/pull/9295#issuecomment-768937402 and fixed https://github.com/atlasmap/atlasmap/pull/2553, will be in next release. @asmigala 
 can you reproduce manually what is done with the test https://github.com/syndesisio/syndesis/pull/9295#issuecomment-769200737 ? export and re-import also didn't reproduce the same condition in standalone.

**Comment by asmigala** [comment]
@igarashitm I think I found the reason for the "double" mapping I mentioned earlier. The test suite decides whether to create a mapping based on the state of the `connect-to-the-selected-mapping-button` button. If it's disabled, it will create a new mapping and then click the connect button on both source and target.

However, in the new version of AtlasMap, the `connect-to-the-selected-mapping-button` is _always_ enabled, and the behaviour is that when a mappping does not exist, clicking it will create a new mapping and add the selected source/target to the created mapping right away.

I'll need to figure out a way to decide whether to create a new mapping or not on our side.

**Comment by rkorytkowski** [comment]
@asmigala is there anything I can assist you with at this point or you are good?

**Comment by asmigala** [comment]
@rkorytkowski I started a new run of the test suite with the test suite fix I mentioned above.

However, I think we should get a release which includes atlasmap/atlasmap#2553 mentioned above before we merge this in syndesis.

**Comment by igarashitm** [comment]
yep, running a 2.1.4 release right now. I'll submit another PR with it today.

**Comment by igarashitm** [comment]
#9316 takes it over

**Pull request closed without merging**
