### PR TITLE
[operator] replace eject for install standalone 

### PR DESCRIPTION
**Pull request by lgarciaaco**
This PR replace `operator eject` with `operator install standalone`

```
perform a fire an forget installation

Usage:
  operator install standalone [flags]

Flags:
      --addons string            a coma separated list of addons that should be enabled
  -h, --help                     help for standalone
      --operator-config string   Path to the operator configuration file. (default "/conf/config.yaml")
```

`install standalone` aims to provide a way of installation where no cluster admin rights are required. It will parse the syndesis resources and directly install them in openshift.

There is no eject mode for `install standalone`.

`install standalone` supports addons installation, but some addons require 3rd party CRDs ... which brings us back to the problem we are trying to solve.

```
operator install standalone --addons camelk,opds --operator-config build/conf/config.yaml
```

`install standalone` requires the conf/config.yaml

### CODE REVIEW

**Comment by lgarciaaco** [comment]
related with https://github.com/syndesisio/syndesis/issues/6356

**Comment by lgarciaaco** [comment]
Updated [documentation](https://github.com/syndesisio/syndesis/wiki/Deploying-to-a-Remote-OpenShift-from-the-Syndesis-Template) accordingly

**Comment by lgarciaaco** [comment]
@heiko-braun are we going to use this for eval clusters? If so, we rather get QE to test it

**Comment by zregvart** [comment]
Perhaps `operator install unmanaged`?

**Comment by heiko-braun** [comment]
@lgarciaaco The backport needs some handholding.

**Pull request merged**
