### PR TITLE
feat: add the flow ID to the route instead of using the fragment

### PR DESCRIPTION
**Pull request by gashcrumb**
As eventually we'll need to do this anyways when we further adjust the routes to add the choose operation page.

### CODE REVIEW

**Comment by gashcrumb** [comment]
There's more I'd probably do but this is the bare minimum I'd want to get the `flows` branch merged I think.

**Comment by lburgazzoli** [comment]
I need to fix some tests then I think you may need to rebase

**Comment by gashcrumb** [comment]
Sounds good, lemme know and I'll rebase this PR.

**Comment by gashcrumb** [comment]
Rebased

**Comment by lburgazzoli** [comment]
I think you need to rebase one more soon :)

**Comment by lburgazzoli** [comment]
@gashcrumb can you rebase again ?

**Comment by gashcrumb** [comment]
@lburgazzoli done!

**Pull request merged**
