### PR TITLE
TEIIDTOOLS-890 changing publishing to a single service

### PR DESCRIPTION
**Pull request by shawkins**

### CODE REVIEW

**Comment by rareddy** [comment]
@shawkins I believe backport not working, this needs to be manually backported 1.9.x branch

**Comment by shawkins** [comment]
Yep.  That will follow shortly.

**Comment by rareddy** [comment]
@shawkins looks like it is not quite 1.9.x branch, see @zregvart email on this subject

**Comment by shawkins** [comment]
@rareddy you'll have to be more specific.  There are other prs pending against syndesis 1.9.x.

**Comment by rareddy** [comment]
@shawkins Nevermind, sorry for the confusion. Per @zregvart we should push to 1.9.x branch, then product branch which on git-repo `fuse-online` will get it from this branch.

**Pull request merged**
