### PR TITLE
fix: If a step has no configurable properties, show that and don't error out

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes [ENTESB-12888](https://issues.redhat.com/browse/ENTESB-12888)

image

This also adds the same message for the split step as it also doesn't currently have configuration either.

@claudio4j FYI

### CODE REVIEW

**Comment by gashcrumb** [comment]
Wonder if it's time to bump the version of yarn on CI:

image

double-checking if I see the same error locally.

**Comment by gashcrumb** [comment]
Builds ok here:

image

**Comment by gashcrumb** [comment]
Well shoot the maven build works fine for me.

**Comment by gashcrumb** [comment]
3rd time was the trick apparently.

**Comment by heiko-braun** [comment]
@gashcrumb Do you backport it manually?

**Comment by gashcrumb** [comment]
yeah, will do that in a few...

**Pull request merged**
