### PR TITLE
Activity Log Errors not showing up in the right step

### LINKED ISSUE #2365: Activity Log Errors not showing up in the right step.
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Successful processing flow:
syndesis

Processing flow where the Random Error step throws an exception:
syndesis

Notice that the Random Error step is not listed and the error is shown in 'Periodic SQL Invocation' step.

## Expected behavior
Random Error step should show up and have the exception on that step entry.

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #2365

@chirino 

this is still not completed but I'm out of time for this week, maybe you can pick it up and fix the remaining issues:

```
i-db2db-3-9gdlj i-db2db {"exchange":"i-L9uEjTEfAV7-XxRXyd-z","status":"begin"}
i-db2db-3-9gdlj i-db2db {"exchange":"i-L9uEjTEfAV7-XxRXyd-z","step":"-L9uAA_Z6ilg1CZ1KX9i","id":"i-L9uEjTEfAV7-XxRXyd0z","duration":4640676}
i-db2db-3-9gdlj i-db2db {"exchange":"i-L9uEjTEfAV7-XxRXyd-z","step":"-L9uADvJ6ilg1CZ1KX9j","id":"i-L9uEjTKfAV7-XxRXyd5z","message":"Body: [{\"last_name\":\"Jackson\",\"company\":\"Red Hat\",\"create_date\":\"2018-04-12\",\"first_name\":\"Joe\",\"lead_source\":\"db\"}] "}
i-db2db-3-9gdlj i-db2db {"exchange":"i-L9uEjTEfAV7-XxRXyd-z","step":"-L9uADvJ6ilg1CZ1KX9j","id":"i-L9uEjTJfAV7-XxRXyd4z","duration":1091133}
i-db2db-3-9gdlj i-db2db {"exchange":"i-L9uEjTEfAV7-XxRXyd-z","step":"-L9uAGBx6ilg1CZ1KX9j","id":"i-L9uEjTLfAV7-XxRXyd6z","duration":1972311}
i-db2db-3-9gdlj i-db2db {"exchange":"i-L9uEjTEfAV7-XxRXyd-z","step":"-L9uAHt46ilg1CZ1KX9j","id":"i-L9uEjTNfAV7-XxRXyd8z","duration":11186569,"failure":"org.apache.camel.RuntimeCamelException: Random error.. try your luck again next time.\n\tat io.syndesis.extension.error.rng.RngErrorAction.handle(RngErrorAction.java:20)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:481)\n\tat org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:300)\n\tat org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:273)\n\tat org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:187)\n\tat org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:53)\n\tat org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:41)\n\tat org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:711)\n\tat org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:634)\n\tat org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248)\n\tat org.apache.camel.processor.Splitter.process(Splitter.java:114)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197)\n\tat org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79)\n\tat java.util.TimerThread.mainLoop(Timer.java:555)\n\tat java.util.TimerThread.run(Timer.java:505)\n"}
i-db2db-3-9gdlj i-db2db {"exchange":"i-L9uEjTEfAV7-XxRXyd-z","status":"done","failed":true}
i-db2db-3-9gdlj i-db2db {"exchange":"i-L9uEjTEfAV7-XxRXyd-z","step":"-L9uAA_Z6ilg1CZ1KX9i","id":"i-L9uEjTEfAV7-XxRXyd0z","duration":20841000,"failure":"org.apache.camel.RuntimeCamelException: Random error.. try your luck again next time.\n\tat io.syndesis.extension.error.rng.RngErrorAction.handle(RngErrorAction.java:20)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:481)\n\tat org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:300)\n\tat org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:273)\n\tat org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:187)\n\tat org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:53)\n\tat org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:41)\n\tat org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:711)\n\tat org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:634)\n\tat org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248)\n\tat org.apache.camel.processor.Splitter.process(Splitter.java:114)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197)\n\tat org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79)\n\tat java.util.TimerThread.mainLoop(Timer.java:555)\n\tat java.util.TimerThread.run(Timer.java:505)\n"}
i-db2db-3-9gdlj i-db2db {"exchange":"i-L9uEjTEfAV7-XxRXyd-z","status":"done","failed":true}
```

Whit my changes the result is a lille better:

image

### CODE REVIEW

**Comment by gashcrumb** [comment]
K took a couple installs and rebuilds but finally got something running.  This is what I see at least, no local changes:

capture

I'd say open the devtools and make sure the option is enabled to "disable the cache while DevTools are open" to avoid any issue that might be introduced by caching, that includes static content served from the UI pod in case you're actually getting some old version of the UI code maybe.

**Comment by lburgazzoli** [comment]
@gashcrumb I rebuilt everything and I'm experiencing the following error:

```
Error: Error: No setting found with the specified group/key [consoleUrl]!
    at ConfigService.webpackJsonp.../../../../../src/app/config.service.ts.ConfigService.getSettings (config.service.ts:69)
    at IntegrationActivityComponent.webpackJsonp.../../../../../src/app/integration/integration_detail/integration_activity/integration-activity.component.ts.IntegrationActivityComponent.updateActivities (integration-activity.component.ts:124)
    at SafeSubscriber._next (integration-activity.component.ts:93)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub (polyfills.bundle.js:2934)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next (polyfills.bundle.js:2881)
    at Subscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next (polyfills.bundle.js:2822)
    at Subscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next (polyfills.bundle.js:2786)
    at MapSubscriber.webpackJsonp.../../../../rxjs/_esm5/operators/map.js.MapSubscriber._next (polyfills.bundle.js:5613)
    at MapSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next (polyfills.bundle.js:2786)
    at ForkJoinSubscriber.webpackJsonp.../../../../rxjs/_esm5/observable/ForkJoinObservable.js.ForkJoinSubscriber.notifyComplete (ForkJoinObservable.js:197)
webpackJsonp.../../../../../src/app/error-handler/exception-handler.service.ts.ExceptionHandlerService.log @ exception-handler.service.ts:19
webpackJsonp.../../../../../src/app/error-handler/exception-handler.service.ts.ExceptionHandlerService.handleError @ exception-handler.service.ts:12
next @ core.js:5481
schedulerFn @ core.js:4319
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ polyfills.bundle.js:2934
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ polyfills.bundle.js:2881
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ polyfills.bundle.js:2822
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ polyfills.bundle.js:2786
webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ polyfills.bundle.js:2519
webpackJsonp.../../../core/esm5/core.js.EventEmitter.emit @ core.js:4299
(anonymous) @ core.js:4755
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:7470
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ polyfills.bundle.js:7220
webpackJsonp.../../../core/esm5/core.js.NgZone.runOutsideAngular @ core.js:4681
onHandleError @ core.js:4755
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ polyfills.bundle.js:7474
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:7273
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.bundle.js:7578
invokeTask @ polyfills.bundle.js:8599
globalZoneAwareCallback @ polyfills.bundle.js:8625
error (async)
customScheduleGlobal @ polyfills.bundle.js:8725
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.bundle.js:7489
onScheduleTask @ polyfills.bundle.js:7379
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ polyfills.bundle.js:7483
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ polyfills.bundle.js:7314
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleEventTask @ polyfills.bundle.js:7340
(anonymous) @ polyfills.bundle.js:8890
(anonymous) @ http.js:2355
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable._trySubscribe @ polyfills.bundle.js:2256
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2244
webpackJsonp.../../../../rxjs/_esm5/operators/tap.js.DoOperator.call @ polyfills.bundle.js:6405
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2241
webpackJsonp.../../../../rxjs/_esm5/operators/map.js.MapOperator.call @ polyfills.bundle.js:5585
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2241
subscribeToResult @ polyfills.bundle.js:6933
webpackJsonp.../../../../rxjs/_esm5/operators/mergeMap.js.MergeMapSubscriber._innerSub @ polyfills.bundle.js:5833
webpackJsonp.../../../../rxjs/_esm5/operators/mergeMap.js.MergeMapSubscriber._tryNext @ polyfills.bundle.js:5830
webpackJsonp.../../../../rxjs/_esm5/operators/mergeMap.js.MergeMapSubscriber._next @ polyfills.bundle.js:5813
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ polyfills.bundle.js:2786
webpackJsonp.../../../../rxjs/_esm5/observable/ScalarObservable.js.ScalarObservable._subscribe @ polyfills.bundle.js:4195
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable._trySubscribe @ polyfills.bundle.js:2256
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2244
webpackJsonp.../../../../rxjs/_esm5/operators/mergeMap.js.MergeMapOperator.call @ polyfills.bundle.js:5787
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2241
webpackJsonp.../../../../rxjs/_esm5/operators/filter.js.FilterOperator.call @ polyfills.bundle.js:5319
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2241
webpackJsonp.../../../../rxjs/_esm5/operators/map.js.MapOperator.call @ polyfills.bundle.js:5585
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2241
webpackJsonp.../../../../rxjs/_esm5/operators/catchError.js.CatchOperator.call @ polyfills.bundle.js:5046
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2241
webpackJsonp.../../../../rxjs/_esm5/operators/map.js.MapOperator.call @ polyfills.bundle.js:5585
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2241
subscribeToResult @ polyfills.bundle.js:6933
ForkJoinSubscriber @ ForkJoinObservable.js:169
webpackJsonp.../../../../rxjs/_esm5/observable/ForkJoinObservable.js.ForkJoinObservable._subscribe @ ForkJoinObservable.js:147
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable._trySubscribe @ polyfills.bundle.js:2256
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2244
webpackJsonp.../../../../rxjs/_esm5/operators/map.js.MapOperator.call @ polyfills.bundle.js:5585
webpackJsonp.../../../../rxjs/_esm5/Observable.js.Observable.subscribe @ polyfills.bundle.js:2241
webpackJsonp.../../../../../src/app/integration/integration_detail/integration_activity/integration-activity.component.ts.IntegrationActivityComponent.fetchActivities @ integration-activity.component.ts:92
webpackJsonp.../../../../../src/app/integration/integration_detail/integration_activity/integration-activity.component.ts.IntegrationActivityComponent.ngOnInit @ integration-activity.component.ts:36
checkAndUpdateDirectiveInline @ core.js:12352
checkAndUpdateNodeInline @ core.js:13876
checkAndUpdateNode @ core.js:13819
debugCheckAndUpdateNode @ core.js:14712
debugCheckDirectivesFn @ core.js:14653
(anonymous) @ IntegrationDetailComponent.html:96
debugUpdateDirectives @ core.js:14638
checkAndUpdateView @ core.js:13785
callViewAction @ core.js:14136
execEmbeddedViewsAction @ core.js:14094
checkAndUpdateView @ core.js:13786
callViewAction @ core.js:14136
execEmbeddedViewsAction @ core.js:14094
checkAndUpdateView @ core.js:13786
callViewAction @ core.js:14136
execComponentViewsAction @ core.js:14068
checkAndUpdateView @ core.js:13791
callViewAction @ core.js:14136
execEmbeddedViewsAction @ core.js:14094
checkAndUpdateView @ core.js:13786
callViewAction @ core.js:14136
execEmbeddedViewsAction @ core.js:14094
checkAndUpdateView @ core.js:13786
callViewAction @ core.js:14136
execComponentViewsAction @ core.js:14068
checkAndUpdateView @ core.js:13791
callWithDebugContext @ core.js:15039
debugCheckAndUpdateView @ core.js:14576
webpackJsonp.../../../core/esm5/core.js.ViewRef_.detectChanges @ core.js:11560
(anonymous) @ core.js:5891
webpackJsonp.../../../core/esm5/core.js.ApplicationRef.tick @ core.js:5891
(anonymous) @ core.js:5724
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:7470
onInvoke @ core.js:4733
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:7469
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ polyfills.bundle.js:7220
webpackJsonp.../../../core/esm5/core.js.NgZone.run @ core.js:4550
next @ core.js:5724
schedulerFn @ core.js:4319
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ polyfills.bundle.js:2934
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ polyfills.bundle.js:2881
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ polyfills.bundle.js:2822
webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ polyfills.bundle.js:2786
webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ polyfills.bundle.js:2519
webpackJsonp.../../../core/esm5/core.js.EventEmitter.emit @ core.js:4299
checkStable @ core.js:4698
onHasTask @ core.js:4746
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.hasTask @ polyfills.bundle.js:7523
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ polyfills.bundle.js:7543
webpackJsonp.../../../../zone.js/dist/zone.js.Zone._updateTaskCount @ polyfills.bundle.js:7367
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:7287
drainMicroTaskQueue @ polyfills.bundle.js:7677
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ polyfills.bundle.js:7582
invokeTask @ polyfills.bundle.js:8599
globalZoneAwareCallback @ polyfills.bundle.js:8625
```

**Comment by gashcrumb** [comment]
@lburgazzoli before you rebuild `rm app/ui/src/config.json` maybe?

Weird, it's showing up in my instance but as an empty string (response I'm seeing for `/config.json`):

```
{
  "apiBase": "https://syndesis.192.168.1.130.nip.io",
  "apiEndpoint": "/api/v1",
  "title": "Syndesis",
  "consoleUrl": "",
  "project": "syndesis",
  "datamapper": {
    "baseMappingServiceUrl": "https://syndesis.192.168.1.130.nip.io/api/v1/atlas/",
    "baseJavaInspectionServiceUrl": "https://syndesis.192.168.1.130.nip.io/api/v1/atlas/java/",
    "baseXMLInspectionServiceUrl": "https://syndesis.192.168.1.130.nip.io/api/v1/atlas/xml/",
    "baseJSONInspectionServiceUrl": "https://syndesis.192.168.1.130.nip.io/api/v1/atlas/json/"
  },
  "features" : {
    "logging": false
  },
  "branding": {
    "logoWhiteBg": "assets/images/syndesis-logo-svg-white.svg",
    "logoDarkBg": "assets/images/syndesis-logo-svg-white.svg",
    "iconWhiteBg": "assets/images/glasses_logo_square.png",
    "iconDarkBg": "assets/images/glasses_logo_square.png",
    "appName": "Syndesis",
    "favicon32": "/favicon-32x32.png",
    "favicon16": "/favicon-16x16.png",
    "touchIcon": "/apple-touch-icon.png",
    "productBuild": false
 }
}
```

Have you done a fresh install since like early last week or the week before?  I forget exactly when the PR that added the openshift console link was merged.

**Comment by gashcrumb** [comment]
This kinda stuff makes me really want a page with commit IDs and versions that we can all look at :-)

**Comment by lburgazzoli** [comment]
I'm reinstalling everything, let see :)

**Comment by lburgazzoli** [comment]
@gashcrumb ok after a full rebuild it is now showing the activity log, thx

**Comment by lburgazzoli** [comment]
@chirino I think we have a working solution now, do you mind doing some tests ? I think after GA we need to re-thing the route builder to have one `direct` route for each step so we have  better control of what's going on (tracked this with #2400)

**Comment by gashcrumb** [comment]
I'll give it another test today as well

**Comment by gashcrumb** [comment]
Looks good to me, one thing I noticed is that the exception seems to show up for the first step and the random error step, for example:

capture

I don't see it as a huge issue though.

**Comment by lburgazzoli** [comment]
@gashcrumb it is happening again ? this should have been fixed

**Comment by lburgazzoli** [comment]
@gashcrumb did you rebuild also the s2i image ?

**Comment by gashcrumb** [comment]
@lburgazzoli so this morning I actually had done a `minishift delete` because the s2i build was failing for me this morning, after which I did `syndesis install`, `syndesis build` and then after everything was built I went and added your extension and created the integration.  So I think yes, this should be with all your changes in place on the branch.

**Comment by lburgazzoli** [comment]
ok will check again

**Comment by chirino** [comment]
Luca,  did not notice you had updated the PR.  I’ll rebase shortly. Was working on some more updates. Mostly a better unit test so it should not be a big loss.

**Pull request merged**
