### PR TITLE
Faux addons feature in the operator

### PR DESCRIPTION
**Pull request by zregvart**
It was simple to implement this, thought now I'm faced with an issue and would like some help, so halp!

When I create a Syndesis object like:

```yaml
apiVersion: "syndesis.io/v1alpha1"
kind: "Syndesis"
metadata:
  name: "example"
spec:
  addons:
    komodo:
```

I get this lovely error:
```
"level":"error","ts":1558512713.3689954,"logger":"controller","msg":"Error reconciling","action":"*action.installAction","phase":"Installing","error":"failed to decode json data with gvk(apps.openshift.io/v1, Kind=DeploymentConfig): v1.DeploymentConfig.Spec: v1.DeploymentConfigSpec.Replicas: readUint32: unexpected character: \ufffd, error found in #10 byte of ...|eplicas\":\"1\",\"select|..., bigger context ...|ure\"},\"name\":\"komodo-server\"},\"spec\":{\"replicas\":\"1\",\"selector\":{\"app\":\"syndesis\",\"syndesis.io/app\":|...","stacktrace":"github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis.(*ReconcileSyndesis).Reconcile\n\t/go/src/github.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis/syndesis_controller.go:122\ngithub.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213\ngithub.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

So there's a `\ufffd` ([replacement char](https://en.wikipedia.org/wiki/Specials_(Unicode_block))) somewhere around `"replicas": "1"`, or here in the template:

https://github.com/syndesisio/syndesis/blob/57c352e39cb99b8610d9e092a95bed38a1297170/install/syndesis.yml#L2019

I see no issues when installing via template and specifying the `DATAVIRT_ENABLED` parameter as `"1"` or `"0"`.

Any ideas anyone?

### CODE REVIEW

**Comment by valdar** [comment]
Or in the value of `${DATAVIRT_ENABLED}` ?

**Comment by astefanutti** [comment]
I think you need to change to:

```
replicas: ${{DATAVIRT_ENABLED}}
```

**Comment by zregvart** [comment]
> Or in the value of `${DATAVIRT_ENABLED}` ?

@valdar thanks, the thing I don't understand is that I control the value and I see it set to `"1"` in the error, this bit: `...eplicas\":\"1\"...`. 

Here: https://github.com/syndesisio/syndesis/blob/1ab29d49337473c27e972a15775bfef3ea9d5fa5/install/operator/pkg/syndesis/template/install.go#L51

**Comment by zregvart** [comment]
@astefanutti thanks, I'm not sure, we're already using the same template with just `${}` (no double curlys `${{...}}`) for the `OPENSHIFT_OAUTH_CLIENT_SECRET` parameter, e.g. here:
https://github.com/syndesisio/syndesis/blob/1ab29d49337473c27e972a15775bfef3ea9d5fa5/install/operator/pkg/syndesis/template/install.go#L49

we set `${OPENSHIFT_OAUTH_CLIENT_SECRET}` parameter for use here:
https://github.com/syndesisio/syndesis/blob/57c352e39cb99b8610d9e092a95bed38a1297170/install/syndesis.yml#L1051

**Comment by astefanutti** [comment]
I had that issue and solved it using `${{...}}`:

https://github.com/hawtio/hawtio-operator/blob/master/templates/deployment.yaml#L71

**Comment by astefanutti** [comment]
More info: https://docs.openshift.com/container-platform/3.11/dev_guide/templates.html#writing-parameters

**Comment by astefanutti** [comment]
`replicas` field is different as it is an integer and expects unquoted string, which the `${{...}}` notation permits.

**Comment by zregvart** [comment]
So the delay here is that even though it seems that the `DATAVIRT_ENABLED` parameter was passed to the template, the deployment config still has the replicas set to 0, so I need to investigate this a bit more.

**Comment by zregvart** [comment]
I have found the enemy and it was me. I missed the second call to `GetInstallResourcesAsRuntimeObjects` which would generate a new set of objects without the `DataVirtEnabled` parameter. I'm removing the `pr/wip` and if anyone has some time to review this I would greatly appreciate it.

**Comment by zregvart** [comment]
> Looks ok to me. Has the effect, I think, that all bits of komodo will be installed bar bringing up an actual pod?

Yeah, that's what we agreed offline, as a first implementation of a feature toggle for data virtualization feature. First change was in the template #5442.

**Comment by zregvart** [comment]
Any thoughts on this @astefanutti @rareddy @nicolaferraro @lgarciaaco before I merge it?

**Pull request merged**
