### PR TITLE
Extenstion import ui

### PR DESCRIPTION
**Pull request by michael-coker**
Fixes https://github.com/syndesisio/syndesis/issues/1714

* Update general import workflow UI
* Enable drag & drop upload
* Create helper class for drag & drop UI
* Update integration importer classes to use helper classes

**One remaining part I need help with**
* Disable multiple file uploads or clear the existing `uploader` queue when you initiate an import either via the select box or drag & drop. Only 1 extension can be imported at a time.

@lburgazzoli - @dongniwang said to ping you on this PR. Do you know who I can talk to about disabling multiple files being uploaded in the import uploader?

### CODE REVIEW

**Comment by gashcrumb** [comment]
@michael-coker we're using ng2-file-upload for this particular view currently, which supports [these options](https://github.com/valor-software/ng2-file-upload/blob/development/src/file-upload/file-uploader.class.ts#L22-L42).  Wonder if setting the queue limit to 1 or `removeAfterUpload` would do the trick.  If you like, we could merge this PR and just raise an issue, assign it to me and I can take a look tomorrow

**Comment by michael-coker** [comment]
@gashcrumb awesome, thanks! `removeAfterUpload` did it.

**Comment by rhuss** [comment]
@michael-coker @gashcrumb there seems to be a failing ui test ...

**Comment by gashcrumb** [comment]
retest this please

**Pull request merged**
