### PR TITLE
ENTESB-12873 - Upgrade Camel to version 2.23.2.fuse-760023

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
This artifacts are available only on jboss organizzation. @zregvart is this expected?

**Comment by oscerd** [comment]
@lgarciaaco about the assets_vfsdata.go, is there something to do while updating the camel version?

**Comment by lgarciaaco** [comment]
> @lgarciaaco about the assets_vfsdata.go, is there something to do while updating the camel version?

I recommend to run `install/operator/build.sh --operator-build go` before commit so it generates all required assets.

**Comment by oscerd** [comment]
This needs to be documented somewhere.

**Comment by oscerd** [comment]
This is what I'm getting 

```
oscerd@ghost:~/workspace/jboss-fuse/syndesis$ install/operator/build.sh --operator-build go
======================================================
Building executable with go tooling
======================================================
generating sources
go: downloading k8s.io/code-generator v0.0.0-20191004115455-8e001e5d1894
go: downloading github.com/stretchr/testify v1.4.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading cloud.google.com/go v0.38.0
go: downloading k8s.io/gengo v0.0.0-20191010091904-7fa3014cb28f
go: extracting github.com/inconshreveable/mousetrap v1.0.0
go: downloading google.golang.org/appengine v1.6.5
go: extracting github.com/stretchr/testify v1.4.0
go: extracting google.golang.org/appengine v1.6.5
go: extracting k8s.io/gengo v0.0.0-20191010091904-7fa3014cb28f
go: downloading golang.org/x/tools v0.0.0-20191018212557-ed542cd5b28a
go: extracting k8s.io/code-generator v0.0.0-20191004115455-8e001e5d1894
go: extracting cloud.google.com/go v0.38.0
go: extracting golang.org/x/tools v0.0.0-20191018212557-ed542cd5b28a

ERROR: 'operator-sdk' not installed. This is necessary if generating new operator source code but not essential for compiling the operator.

# runtime
/usr/local/go/src/runtime/stubs_x86.go:10:6: stackcheck redeclared in this block
	previous declaration at /usr/local/go/src/runtime/stubs_amd64x.go:10:6
/usr/local/go/src/runtime/unaligned1.go:11:6: readUnaligned32 redeclared in this block
	previous declaration at /usr/local/go/src/runtime/alg.go:321:40
/usr/local/go/src/runtime/unaligned1.go:15:6: readUnaligned64 redeclared in this block
	previous declaration at /usr/local/go/src/runtime/alg.go:329:40
pkg/generator/generator.go:18: running "go": exit status 2

```

**Comment by oscerd** [comment]
It doesn't work even by rebuilding the operator.

**Pull request merged**
