### PR TITLE
[fix] Query parameters are not set in the API-Connector #3564

### PR DESCRIPTION
**Pull request by zregvart**
(cherry picked from commit 61ab88570c43e296b06c8fe4ecc39bedb51a7133)

@KurtStam I saw that the PR #3572 had `pr/needs-backport` label but it was subsequently removed. I think we should backport this fix, but I could be missing some discussion around this and we could have decided not to backport the fix.

cc @paoloantinori @heiko-braun

### CODE REVIEW

**Comment by heiko-braun** [comment]
Thanks @zregvart . We had discussed it and decided to keep the changes in 7.1.1 to a minimum. I'll loop in @gaughan for feedback. 

Gary, do you think https://github.com/syndesisio/syndesis/issues/3564 should be included in 7.1.1?

**Comment by zregvart** [comment]
Without this integrations using custom API client connectors can't use HTTP query parameters.

They get mapped and received, but the minimization of the Swagger specification removes the query parameters. So the `camel-rest-swagger` Camel component doesn't propagate the query parameter to the HTTP request as the parameter is not found in the Swagger specification that the component is configured with.

And further background on why we minimize the Swagger specification can be found in #2880.

**Comment by gaughan** [comment]
@heiko-braun Agree on including in 7.1.1

**Comment by heiko-braun** [comment]
@zregvart See above. We agreed to include it in 7.1.1

**Pull request merged**
