### PR TITLE
Teiidtools 979

### PR DESCRIPTION
**Pull request by indraraj**
- Jira Issue https://issues.redhat.com/browse/TEIIDTOOLS-979

- Implemented the data permission screen ui based on updated UX  

- Screenshots 
image
image
image

### CODE REVIEW

**Comment by rareddy** [comment]
Nice. Looking good. I have asked for further clarification on the comments on the design for expansions of list.

**Comment by avano** [comment]
retest this please

**Comment by indraraj** [comment]
Update the View Dropdown.
image

**Comment by indraraj** [comment]
yes agreed changes in UI functional code will be required as we integrate backed. and having this in will provide the basic setup to further work upon.

**Pull request merged**
