### PR TITLE
fix: agent directive syntax error

### PR DESCRIPTION
**Pull request by zregvart**
Fixes `agent` directive syntax in `Jenkinsfile`

### CODE REVIEW

**Comment by rhuss** [comment]
@zregvart oops, I just approved #552 from @iocanel 

Does this PR target the same issue ?

**Comment by iocanel** [comment]
@rhuss: No, this one takes things one step further.

**Comment by zregvart** [comment]
> @rhuss: No, this one takes things one step further.

@iocanel any luck getting those accounts on fuse ignite cluster? if so this can be closed

**Comment by iocanel** [comment]
@zregvart: requested them today. Not sure when they will be ready?

**Comment by zregvart** [comment]
I'll close this, seems not to be relevant any more.

**Pull request closed without merging**
