### PR TITLE
Fix for the incorrect query in FuseOnlinePostgresExporterDown alert.

### PR DESCRIPTION
**Pull request by Rajagopalan-Ranganathan**
JIRA Link: https://issues.redhat.com/browse/INTLY-9047

From the issue description: 

The alert FuseOnlinePostgresExporterDown has a potentially incorrect query and has a SOP ecnourages toil.
```
{
  "name": "FuseOnlinePostgresExporterDown",
  "query": "absent(up{job=\"syndesis-db\"}) == 1",
  "duration": 300,
  "labels": {
    "severity": "critical"
  },
  "annotations": {
    "message": "syndesis-db has disappeared from Prometheus target discovery.",
    "sop_url": "https://github.com/syndesisio/syndesis/blob/master/doc/managing_environments/topics/alerting_sop.adoc#fuseonlinepostgresexporterdown"
  },
  "alerts": [],
  "health": "ok",
  "type": "alerting",
  "file": "/etc/prometheus/rules/prometheus-application-monitoring-rulefiles-0/openshift-fuse-syndesis-infra-db-alerting-rules.yaml"
}```

Code changes made to correct the query.  code generation done to have  the pkg/generator/assets_vfsdata.go updated.

### CODE REVIEW

**Comment by Rajagopalan-Ranganathan** [comment]
@zregvart @Delawen  - Please take a look.

@david-martin @pepedocs  - FYI

**Comment by claudio4j** [comment]
@Rajagopalan-Ranganathan do you need this fix for 1.11.x branch ? (that branch is for fuse online 7.8)

**Comment by heiko-braun** [comment]
@claudio4j Yes, let's backport it.

**Comment by david-martin** [comment]
> do you need this fix for 1.11.x branch ? (that branch is for fuse online 7.8)

This would be ideal so the fix is in place for our SRE team sooner.
What's the process for this? Should another PR be created to that branch?

Thanks

**Comment by claudio4j** [comment]
> What's the process for this? Should another PR be created to that branch?

Yeah, a cherry-pick to 1.11.x branch is fine.

**Comment by Rajagopalan-Ranganathan** [comment]
https://github.com/syndesisio/syndesis/pull/8857 - PR for 1.11.x branch.

**Pull request merged**
