### PR TITLE
backport - fix for ENTESB-11675 to add errorHandler field to the schema

### PR DESCRIPTION
**Pull request by KurtStam**
backport to 1.9.x

https://issues.redhat.com/browse/ENTESB-13104

### CODE REVIEW

**Comment by heiko-braun** [comment]
@KurtStam Thanks for the fix. Let's keep it on master.

**Comment by KurtStam** [comment]
@heiko-braun , if we don't backport it this will prevent the UI from fully working with the ErrorHandling configuration.

**Comment by heiko-braun** [comment]
@KurtStam What's the ENTESB ticket for this? What priority does QE give to the item? At this point we only accept blocking issues into 1.9.x.

**Comment by heiko-braun** [comment]
@KurtStam I have seen ENTESB-11675, but that's closed already. Hence my question about the ticket

**Comment by heiko-braun** [comment]
Please hold until @KurtStam and Michael have discusseit the impact of bringing it on 1.9.x. this late.

**Comment by KurtStam** [comment]
After discussing with Micheal I'm fine with not backporting this to 1.9.x.

**Pull request closed without merging**
