### PR TITLE
ENTESB-11729: Upgrade of fuse-camel

### PR DESCRIPTION
**Pull request by phantomjinx**
* Bumps version to 2.21.0.fuse-750029

* Corrects odata tests to conform with upstream change.

### CODE REVIEW

**Comment by phantomjinx** [comment]
> Have the artifact been pinned?

I assume so as I didn't promote it. Another fuse project had already done that & upgraded to it.
Can't actually access https://repository.jboss.org/nexus either at the moment (just remains spinning "Loading Nexus UI").

**Comment by phantomjinx** [comment]
> I believe you need to update the camel-k catalog too

Have searched through the syndesis codebase and can't find any other references to 2.21.0.fuse-7500 other than these:
```
extension/bom/pom.xml:    <camel.version>2.21.0.fuse-750029</camel.version>
integration/bom-camel-k/pom.xml:    <camel.version>2.21.0.fuse-750029</camel.version>
integration/bom/pom.xml:    <camel.version>2.21.0.fuse-750029</camel.version>
pom.xml:    <camel.version>2.21.0.fuse-750029</camel.version>
```
Can you point to what I've missed?

Thx.

@oscerd

**Comment by oscerd** [comment]
There is a reference here:

install/operator/build/conf/config.yaml
install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.21.0.fuse-750007.yaml.tmpl

I think this must be overriden from integration/camel-k build

@nicolaferraro @valdar right?

**Comment by nicolaferraro** [comment]
Yes, please the `config.yaml` file needs to be updated with the new version of Camel and a new camel-catalog-${version}.yaml.tmpl needs to be added to the list of resources added by the camel k addon in the operator (look at the existing one install/operator/pkg/generator/assets/addons/camelk/camel-catalog-2.21.0.fuse-750007.yaml.tmpl  for ref on how to generate it).

This is needed only for upstream bits to work in camel k mode (not needed in prod build).

We can get rid of this manual process when we switch to camel k 1.x and camel 3.x.

**Comment by phantomjinx** [comment]
@nicolaferraro @oscerd 
Been through all the codebase now with
```
grep -r 2\\.21\\.0 * | grep -v node_modules | grep -v target | grep -v yarn | grep -v json | grep -v svg | grep -v apicurio | grep -v Binary | grep -v 29
```
so all references to 2.21.0.fuse-750007 not update to ...029 except for

```
doc/shared/attributes.adoc::camelFullVersion: 2.21.0.fuse-740039-redhat-00001
```

Know if that should be updated too?
Looks like it hasn't been updated in a while although it is seems a product version.

**Comment by oscerd** [comment]
Pinned the needed bits.

**Pull request merged**
