### PR TITLE
[backport 1.12x] fix(UI): [ENTESB-11411] - display a generic step icon when replacing a step

### PR DESCRIPTION
**Pull request by kahboom**
backport of https://github.com/syndesisio/syndesis/pull/9302 for [ENTESB-11411](https://issues.redhat.com/browse/ENTESB-11411)

### CODE REVIEW

**Comment by kahboom** [comment]
@avano - do you happen to know if anything is going on with the QE Jenkins PR build for 1.12.x?

**Comment by avano** [comment]
retest this please

@kahboom our infra is in very bad shape at the moment :cry:

**Comment by avano** [comment]
@kahboom :+1:

**Comment by kahboom** [comment]
Thanks @avano 🎉

**Pull request merged**
