### PR TITLE
Fix:Add support for Set type operation

### PR DESCRIPTION
**Pull request by indraraj**
- Jira issue https://issues.redhat.com/browse/TEIIDTOOLS-1060

- Added the SET value type to operation.

- screenshot 
image

### CODE REVIEW

**Comment by indraraj** [comment]
Retest this please.

**Comment by indraraj** [comment]
Retest this please.

**Comment by gashcrumb** [comment]
retest this please

**Comment by mdrillin** [comment]
code looks good, but there seems to be an issue with removing a role.  I will add further comments on the JIRA.  We can merge this and work the remaining as a separate issue if you like.

**Comment by indraraj** [comment]
sure, I think we can fix it in here and hold this merge until that as nothing else is going around on this feature as of now.

**Pull request merged**
