### PR TITLE
chore: Update to AtlasMap 2.0.4

### PR DESCRIPTION
**Pull request by igarashitm**
https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.0.4

### CODE REVIEW

**Comment by gashcrumb** [comment]
you might need to rebase this to get the ui/ui-doc jobs working, along with your backport PR

**Comment by igarashitm** [comment]
hmm it still fails with exit code 137, would be OOM killer.

**Comment by gashcrumb** [comment]
yep, sure did...  <sigh>  let's try a manual restart and see how that does.  We might also be able to tune down the node heap a little more.

**Comment by gashcrumb** [comment]
retest this please

**Comment by gashcrumb** [comment]
Retest this please

**Pull request merged**
