### PR TITLE
chore(dep): upgrade Camel

### PR DESCRIPTION
**Pull request by zregvart**
Upgrades Camel to 2.23.2.fuse-7_10_0-00020-redhat-00001.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by mkralik3** [comment]
retest this please  (It looks that our cluster is unstable, i will try it with another one )

**Comment by mkralik3** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Pull request merged**
