### PR TITLE
user doc: Add a readme file, asciidoc tips, and delete an unneeded file.

### PR DESCRIPTION
**Pull request by TovaCohen**

### CODE REVIEW

**Comment by TovaCohen** [comment]
Thanks for letting me know. 
I can look at this Friday.

**Comment by TovaCohen** [comment]
If this I blocking things can you back out the merge?

**Comment by TovaCohen** [comment]
@heiko-braun  - Zoran's PR, which Fintan approved, fixes the build, right?
https://github.com/syndesisio/syndesis/pull/6664

I think that I do not need to do anything, so please let me know if I something is needed from me. 
Thanks, and sorry about breaking the build :-(

**Comment by zregvart** [comment]
I think the daily builds will be fixed with #6664 and #6676, don't worry about breaking the build, if it was always succeeding we wouldn't be doing much...

**Pull request merged**
