### PR TITLE
fix: integration list re-rendering when polling

### LINKED ISSUE #3121: The View/Edit/Start/Stop dropdown menu of syndesis integration is disappearing on integration start
## This is a...

<pre><code>
[ ] Feature request
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

There is a problem with the syndesis integration dropdown menu, which offers the user operations: View/Edit/Start/Stop/Delete/Export. 
When the integration is starting, the menu tends to disappear approx. every 3 seconds.

## Expected behavior

The menu should be in its place until the user selects one of the offered operations or clicks somewhere else on the page.

## Screenshot

out

## Tasks involved / Steps to Reproduce

1. Create some integration
2. While the integration is starting - go to the integrations list page
3. Click on the three vertical dots in the right - the menu appears
4. Observe how it disappears without any action after 3 seconds (can be observed only when the integration is starting)

### PR DESCRIPTION
**Pull request by riccardo-forina**
Fixes #3121.

This requires patternfly/patternfly-ng/pull/435 to be merged and released to work.

### CODE REVIEW

**Comment by gashcrumb** [comment]
AOT error during the build:

```
[ERROR] ERROR in : Can't bind to 'trackBy' since it isn't a known property of 'pfng-list'.
[ERROR] 1. If 'pfng-list' is an Angular component and it has 'trackBy' input, then verify that it is part of this module.
[ERROR] 2. If 'pfng-list' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
[ERROR] 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("          [itemTemplate]="itemTemplate"
[ERROR]              [actionTemplate]="actionTemplate"
[ERROR]              [ERROR ->][trackBy]="trackById"
[ERROR]              (onActionSelect)="integrationActionsService.requestAction($event.i")
```

Might need to wait until a patternfly-ng release and add a bump to the version containing this input to this PR before we can merge.

**Comment by riccardo-forina** [comment]
Yes exactly. PR got merged, but we will have to wait for a new release.

In the meanwhile this can be tested using [yalc](https://github.com/whitecolor/yalc).

First it must be installed `yarn global add yalc`.

Then in `patternfly-ng`:
```
$ yarn build
$ cd dist
$ yalc publish
```

In `syndesis` then:
```
$ cd app/ui
$ yalc add --link patternfly-ng
```

That should be it. To be sure `yarn list patternfly-ng` should output something like this
`patternfly-ng@0.0.0-semantically-released-0b4ae0ff`

Just be sure that `package.json` doesn't get changed, and if it does, don't commit it :)

**Comment by paoloantinori** [comment]
retest this please

**Comment by riccardo-forina** [comment]
There is a problem on `master` that makes CircleCI tests to fail. I'm monitoring for updates, will rebase this again as soon as the problem is fixed.

**Comment by zregvart** [comment]
Issue on master should be fixed with #3311

**Comment by rhuss** [comment]
As soon as https://github.com/syndesisio/syndesis/pull/3311 is merged, master should be good again.

**Comment by paoloantinori** [comment]
guys has the branching for 7.1 productization happened already? I haven't seen any email reporting that.

And since you well know that we are in code freeze and we should merge only blockers, this, not being a blocker, is not going to be merged.

**Comment by riccardo-forina** [comment]
Is master still frozen? Because this is ready to be merged IMHO, it just needs approval.

**Pull request merged**
