### PR TITLE
chore(operator): Revert renaming from syndeses to syndesises for compat reasons.

### LINKED ISSUE #4641: [Upgrade] How to upgrade from 1.5.9 to current master wrt new crd name?
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
@rhuss what is the procedure to upgrade older syndesis to current master?

I deployed `1.5.9-20181130` and I want to upgrade to `1.6.1-20190219`.

Before creating a new operator, I manually created new crd `syndeses.syndesis.io` and I had both CRDs defined:

```
oc get crd
NAME                                                                     CREATED AT
openshiftwebconsoleconfigs.webconsole.operator.openshift.io              2019-02-20T07:45:19Z
servicecertsigneroperatorconfigs.servicecertsigner.config.openshift.io   2019-02-20T07:43:18Z
syndeses.syndesis.io                                                     2019-02-20T08:53:29Z
syndesises.syndesis.io                                                   2019-02-20T08:51:08Z

```

Then in `1.6.1-20190219` tag:

```
oc delete -f install/operator/deploy/syndesis-operator.yml 
oc create -f install/operator/deploy/syndesis-operator.yml 
```

The new operator does not like that:

```
{"level":"info","ts":1550652936.0611773,"logger":"cmd","msg":"Using template","template":"/conf/syndesis-template.yml"}
{"level":"info","ts":1550652936.0612476,"logger":"cmd","msg":"Go Version: go1.11"}
{"level":"info","ts":1550652936.0612583,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1550652936.0612621,"logger":"cmd","msg":"Version of operator-sdk: v0.5.0"}
{"level":"info","ts":1550652936.0615678,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1550652936.1777678,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1550652936.182354,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1550652936.2558882,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1550652936.2581608,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"syndesis-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1550652936.2610352,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1550652936.3613627,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"syndesis-controller"}
{"level":"info","ts":1550652936.4622655,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"syndesis-controller","worker count":1}
{"level":"info","ts":1550652936.462466,"logger":"controller","msg":"Reconciling Syndesis","Request.Namespace":"syndesis","Request.Name":"app"}
{"level":"info","ts":1550652936.462515,"logger":"controller","msg":"Running action","action":"action.checkUpdatesAction"}
{"level":"info","ts":1550652936.6070914,"logger":"action","msg":"Starting upgrade of Syndesis resource","type":"check-updates","name":"app","currentVersion":"1.5.9-20181130","targetVersion":"1.6.1-20190219","type":"checkUpdate"}
{"level":"error","ts":1550652936.6084971,"logger":"controller","msg":"Error reconciling","action":"action.checkUpdatesAction","phase":"Installed","error":"the server could not find the requested resource (put syndesises.syndesis.io app)","stacktrace":"github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis.(*ReconcileSyndesis).Reconcile\n\t/go/src/github.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis/syndesis_controller.go:119\ngithub.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213\ngithub.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

### PR DESCRIPTION
**Pull request by rhuss**
Fixes #4641

### CODE REVIEW

**Comment by heiko-braun** [comment]
@avano Mind a second look?

**Comment by avano** [comment]
@heiko-braun yes I'm on it

**Comment by avano** [comment]
@rhuss since there is no functional change in the operator in this PR, I would expect the upgrade from older version to work - I did the same steps as #4641 , but my only CRD is `syndesises.syndesis.io` :

```
oc get crd
NAME                                                                     CREATED AT
openshiftwebconsoleconfigs.webconsole.operator.openshift.io              2019-02-22T08:23:57Z
servicecertsigneroperatorconfigs.servicecertsigner.config.openshift.io   2019-02-22T08:21:14Z
syndesises.syndesis.io                                                   2019-02-22T11:10:19Z

```

The `latest` operator still seems to be confused:

```
{"level":"info","ts":1550834332.7621875,"logger":"action","msg":"Starting upgrade of Syndesis resource","type":"check-updates","name":"app","currentVersion":"1.5.9-20181130","targetVersion":"latest","type":"checkUpdate"}
{"level":"error","ts":1550834332.7674634,"logger":"controller","msg":"Error reconciling","action":"action.checkUpdatesAction","phase":"Installed","error":"the server could not find the requested resource (put syndesises.syndesis.io app)","stacktrace":"github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis.(*ReconcileSyndesis).Reconcile\n\t/go/src/github.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis/syndesis_controller.go:119\ngithub.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213\ngithub.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

```

```
oc describe crd syndesises.syndesis.io
Name:         syndesises.syndesis.io
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-02-22T11:10:19Z
  Generation:          1
  Resource Version:    44968
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/syndesises.syndesis.io
  UID:                 70b97cf8-3692-11e9-85ab-0800272c3b77
Spec:
  Additional Printer Columns:
    JSON Path:    .metadata.creationTimestamp
    Description:  CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    Name:  Age
    Type:  date
  Group:   syndesis.io
  Names:
    Kind:       Syndesis
    List Kind:  SyndesisList
    Plural:     syndesises
    Singular:   syndesis
  Scope:        Namespaced
  Version:      v1alpha1
  Versions:
    Name:     v1alpha1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       Syndesis
    List Kind:  SyndesisList
    Plural:     syndesises
    Singular:   syndesis
  Conditions:
    Last Transition Time:  2019-02-22T11:10:19Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1alpha1
Events:  <none>

```

```
oc get syndesis
NAME      AGE
app       16m
```

Am I missing something here?

**Comment by rhuss** [comment]
@avano I will check that asap. Some strange is happening.

**Comment by rhuss** [comment]
The somewhat good news: I can reproduce it now.

**Comment by avano** [comment]
@rhuss great, btw the same error I can see on "dedicated" (not on minishift) OCP 3.10 : https://github.com/syndesisio/syndesis/issues/4681

**Comment by rhuss** [comment]
I found the issue: In the new CRD version we introuced a subresource "status" and in the operator we only update this status. However in the old CRD versiom there's not such subresource declared hence the update failure.

@avano @heiko-braun we have now two options:

* Remove the subresource declaration from "status" and update the operator to make a full resource update (which is not considered to be good practice when only the status changes)
* Go the full route by increasing the API version of the Syndesis CRD and migrate the old 'Syndesis' CRs to this new format (with the new plurarl form + status subresource).

I strongly recommend for the first option as being having the least impact now. However, the second moved shoudl be seriously considered when doing the upgrade from 7.3 to 7.4. It will be a challenge for performng the CRD version update out of band (this is an extra step an admin needs to do, so we need to update the scripts) and to migrate from one older to a new CR (this can part of the update scripts or part of the 7.4. operator code).

Thoughts on this ?

In the meantime I update this PR to not use the status subresource for the update (option 1)

**Comment by avano** [comment]
+1 to go the simple way now and fix for 7.4 (ideally sooner than in the last sprint :grinning:)

**Comment by heiko-braun** [comment]
+1 for the first option as well. Please create a separate issue for the changes we should make in 7.4

**Pull request merged**
