### PR TITLE
ENTESB-16528 Fuse Online 7.9 Dependencies aligment

### PR DESCRIPTION
**Pull request by claudio4j**
https://issues.redhat.com/browse/ENTESB-16528

### CODE REVIEW

**Comment by Delawen** [comment]
retest this please

**Comment by mkralik3** [comment]
retest this please

**Comment by mkralik3** [comment]
retest this please

**Comment by mkralik3** [comment]
:cry:  (the kube API started failing randomly on the cluster where the tests are running)
retest this please

**Review by zregvart — APPROVED** [review]

**Pull request merged**
