### PR TITLE
ENTESB-11970: adding a cpu request for teiid-syndesis

### PR DESCRIPTION
**Pull request by shawkins**

### CODE REVIEW

**Comment by rareddy** [comment]
@heiko-braun looks like the checks are failing on unrelated changes, do you want to merge this in?

**Comment by zregvart** [comment]
This failed in CI because the regeneration of `install/operator/pkg/generator/assets_vfsdata.go` was not done. If subsequent build, i.e. in productization, do not run the asset generation step of the operator build then the content of this change will not be included in the built operator.

This is not a CI flake as an [issue was clearly reported](https://circleci.com/gh/syndesisio/syndesis/153064) by the CI, please refrain from merging pull requests that break the CI. This breaks the workflow for everyone.

**Comment by heiko-braun** [comment]
@zregvart Sorry, that was my bad. Sorry for the mess. I am going to revert the chnages.

@rareddy Can you prepare another PR that includes the changes to `assets_vfsdata.go`?

**Comment by heiko-braun** [comment]
@rareddy nm, @zregvart fixed it in https://github.com/syndesisio/syndesis/pull/6921/commits/4d3835652d715de976b3ffff8532bbc6757f501c

**Comment by rareddy** [comment]
Thanks @zregvart 
Does the `assets_vfsdata.go` changes every time there is another commit in code? Is this like post commit we used to do with `syndesis.yml` before?

**Comment by zregvart** [comment]
@rareddy from what I understand the assets_vfsdata.go changes with each change to the template files in the operator. We recently switched from pre-commit to Husky it should be fairly trivial to make sure that it's up to date by adding a git hook. I'll have a look into that.

**Comment by rareddy** [comment]
That would be great @zregvart as it happened couple times to us already :)

**Pull request merged**
