### PR TITLE
feature(operator): Initial build and install support for syndesis-operator

### PR DESCRIPTION
**Pull request by rhuss**
This PR will change the way how "syndesis" works, and it is expected,
as it is not a small change, that there might be some kinks.

Not yet finished, but good enough to give it a try.

### CODE REVIEW

**Comment by rhuss** [comment]
Fixes https://github.com/syndesisio/syndesis/issues/2888

**Comment by rhuss** [comment]
I think I'm ready for a review and possible merge. Its quite a mouthful, but I had to completely adapt the way how we are performing the build with `syndesis`

I updated the following parts

* `syndesis build` creates the operator (`-m operator`) as well as the Docker images. Build can be done locally with a local go installation (faster) or via a Docker image (more robust). For a local build to work you have to checkout syndesis at $GOPATH/src/github.com/syndesisio/syndesis. The image build either works via a Docker daemon (`--docker`, required by the CI) or a S2I Dockerfile build (useful to autmatically update the operator in minishift like the other images). Also the Docker build for the Java Docker images has been deprecated and the options have been slightly changed

* `syndesis minishift` now does the following (instead of installing the oauthclient and applying the template):
  - Switch to system:admin to register the Syndesis CRD an create a role with some missing perms for `developer` user. Add a rolebdinding to `developer` for this role
  - As `developer`: Install `syndesis-operator` as a regular DeploymentConfig
  - Create a Syndesis resource on the fly reflecting the parameter given

* For `syndesis install` the same is performed, except that there is no automatic change to admin as this is not possible in general. So you can use multiple steps:
  `syndesis install --setup-crd` (as admin)
  `syndesis install --fix-permission <user>` add permissions to user (to be run as admin)
  `syndesis install` as normal user to install the operator and the custom resource

* The operator now reads the template from the filesystem. The proper template is packaged in to the operator's Docker image.

* `syndesis release` has been updated to release the operator with the proper template

* CircleCI job now also builds the Operator Images and pushes it to Docker Hub

-----------

There are for sure still some kinks, i.e. the update needs to be tested.

**Comment by nicolaferraro** [comment]
Looks very good :smile:

**Comment by rhuss** [comment]
> Let's merge and fix any issues that come up, if they come up.

well, seems that this didn't really worked out.

It's all my fault that I haven't mailed the notes from https://github.com/syndesisio/syndesis/pull/3213#issuecomment-408915960 and haven't updated the user manual yet.

**Pull request merged**
