### PR TITLE
Fixes #4789, fixed public API deployment search when stopping integrations

### LINKED ISSUE #4789: Stop integration via Public API doesn't work
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have a running integration. When I call
```
curl -k -L -H -v -X PUT "Content-Type: application/json" -H "SYNDESIS-XSRF-TOKEN: awesome" -H 'Authorization: Bearer <TOKEN>' https://public-syndesis.my-minishift.syndesis.io/api/v1/public/integrations/timer-to-log/deployments/stop 
```
It returns 
```
{"errorCode":403,"userMsg":"Given request is not acceptable","developerMsg":"Integration timer-to-log is not published"}
```

On the other hand, when the integration is Unpublished, it returns `204 No Content`. In my POV, it should return the error to notify a user that the integration is not published. 

output

### PR DESCRIPTION
**Pull request by dhirajsb**
Fixes #4789

### CODE REVIEW

**Comment by dhirajsb** [comment]
Created https://github.com/syndesisio/syndesis/pull/4884 to backport to 1.6.x

**Comment by dhirajsb** [comment]
@gashcrumb can you bless this please?

**Comment by mkralik3** [comment]
Verified from the functional point of view.

**Comment by heiko-braun** [comment]
@syndesisio/backend Can anyone review this?

**Comment by dhirajsb** [comment]
@oscerd can you approve this too?

**Pull request merged**
