### PR TITLE
Add UX design for data buckets

### PR DESCRIPTION
**Pull request by dongniwang**
This design covers the following aspects of data buckets:
- Visualizing Step ID (#1111) and showing data type information (#700) in Integration Visualization Panel (IVP)
- Showing visual indicator when data types don't match (#700)
- Displaying multiple source documents in data mapper source card (#1654)

Please review: @igarashitm @kcbabo @gashcrumb @amysueg @sjcox-rh @michael-coker @seanforyou23 @TovaCohen

### CODE REVIEW

**Comment by TovaCohen** [comment]
LGTM!  Thanks Dongni!

**Comment by amysueg** [comment]
This looks *great* @dongniwang thank you.
I have a tiny concern that Michael S raised during the meeting today. In this design, we are specifying that the user must select/click on the "i" information icon in order to display the information. That behavior is not the same as the "i" icon in the configuration form pages which only requires hover to display a tooltip. I suspect it may be ok since the context is so different between the two areas of the application, but I'm a little concerned about the inconsistent implementations. Not sure what the answer is.

**Comment by igarashitm** [comment]
@amysueg IIRC @gashcrumb pointed out that the hover is not accessible for touch device. Do we want to convert all the hovery into clicky? Maybe later...

**Comment by gashcrumb** [comment]
I made 'em clicky in this PR -> https://github.com/syndesisio/syndesis/pull/1681

**Comment by TovaCohen** [comment]
Can you clarify for me what the user needs to click on where previously they hovered?
Does the user still hover over the plus sign in the IVP to get the popup for adding a step or connection?

**Pull request merged**
