### PR TITLE
fix(5607): Unify template step naming

### PR DESCRIPTION
**Pull request by phantomjinx**
* Removes templater codename as no longer required and confuses with template.

### CODE REVIEW

**Comment by gashcrumb** [comment]
"template" here feels too generic.  But I can't think of a more precise term yet to suggest yet.

**Comment by phantomjinx** [comment]
> "template" here feels too generic. But I can't think of a more precise term yet to suggest yet.

Problem is that there is an awful lot of "template" and "template step" labels and names to change if we go that way. It made sense to remove "templater" as the lesser contributor.

**Comment by phantomjinx** [comment]
Same problem as #5955, the Camel-K compiling in test-builds seems to be failing to find dependencies. Is someone able to help with this please?

**Comment by riccardo-forina** [comment]
`useTemplateEditor` maybe?

**Comment by gashcrumb** [comment]
+1

**Comment by phantomjinx** [comment]
> `useTemplateEditor` maybe?

1. Do you want all BE java classes updated to "TemplateEditor"?
2. Do you want the labels seen by users to say "Template Editor" rather than than "Template"?

@riccardo-forina 
@gashcrumb

**Comment by riccardo-forina** [comment]
For the user, I dunno. For the BE classes, is there value in using the same name?

**Comment by phantomjinx** [comment]
So have being mulling over this for the last couple of days...

The objective of the issue is to unify the template naming. That is achieved with the current PR.

To change 'template' to something more original requires a number of further changes, including
- Labels in the UI
- Package & class names in ui-react code
- Package & class names in BE
- The stepKind which bridges both FE & BE

Now, the point was raised why change stuff not seen by the user. The reason, to my mind, is that it should be obvious in the code where a feature resides so, for example, the 'template' feature should be in the 'step/template' package & the main class should be 'TemplateStepHandler'.

At this juncture, I feel that the breadth of change & possibility of breaking things is too high to justify a renaming without a more definitive driver for doing it.

Interested to hear your views, @gashcrumb, @riccardo-forina.

**Comment by gashcrumb** [comment]
I was just thinking in terms of maintenance, non generic self describing
class names are nicer.   I wasn't talking about the UI or user visible bits
at all :-)

**Comment by phantomjinx** [comment]
> I was just thinking in terms of maintenance, non generic self describing class names are nicer. I wasn't talking about the UI or user visible bits at all :-)

No problem. Its just the original issue #5607 was more concerned about what the user saw on the screen so am trying to straddle 2 related concerns.

**Comment by phantomjinx** [comment]
Any chance that this PR could be approved so at least the "templater" name is now removed? Then we can move on to refactoring a different name for the 'template' feature if required.
Thx.
@gashcrumb, @riccardo-forina

**Pull request merged**
