### PR TITLE
fix(ui) - ENTESB-14562 - select first option in array for ports + services

### PR DESCRIPTION
**Pull request by kahboom**
fix for [ENTESB-14562](https://issues.redhat.com/browse/ENTESB-14562)

cc @dhirajsb

### CODE REVIEW

**Comment by kahboom** [comment]
retest this please

**Review by gashcrumb — APPROVED** [review]

**Comment by kahboom** [comment]
@avano - is this ok to merge? I re-ran the integration tests but they just keep failing 😅

**Comment by avano** [comment]
@kahboom those are not the QE tests, so can't help with that :grin:

**Comment by gashcrumb** [comment]
@dhirajsb weren't you having some issues with one of these integration tests today?

**Pull request merged**
