### PR TITLE
Fix #4278 Support basic and bearer token authentication in FHIR

### LINKED ISSUE #4278: Support basic and bearer token authentication in FHIR
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

FHIR connector needs to support basic and bearer token (oauth) authentication.

### PR DESCRIPTION
**Pull request by rkorytkowski**
I have an issue with building this locally with checks enabled. It fails due to:
`[WARNING] /home/rafal/.m2/repository/io/syndesis/common/common-model/1.6-SNAPSHOT/common-model-1.6-SNAPSHOT.jar(/io/syndesis/common/model/WithConfigurationProperties.class):[-1,-1] Cannot find annotation method 'value()' in type 'edu.umd.cs.findbugs.annotations.SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found`

It started to happen after adding tests.

I have no idea why it happens. Does anyone have a clue?

### CODE REVIEW

**Comment by rkorytkowski** [comment]
@zregvart worked! Have you seen it before? How did you figure it out?

**Comment by rkorytkowski** [comment]
PR for #4278

**Comment by zregvart** [comment]
> @zregvart worked! Have you seen it before? How did you figure it out?

Saw it before, easy way to get an idea what's missing is to do a `fc:edu.umd.cs.findbugs.annotations.SuppressFBWarnings` search on https://search.maven.org and see if any dependencies show up that are missing in `mvn dependency:tree`. Since this is a SpotBugs annotation it is [not required at runtime](https://github.com/spotbugs/spotbugs/blob/e6ea7a71cd4ab8a349c5c573adfca26c0acc2bdb/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs/annotations/SuppressFBWarnings.java#L33), we need to set the `provided` scope.

**Comment by rkorytkowski** [comment]
@zregvart thanks for the explanation. I was mistaken by the fact that IntelliJ was showing me that the class was already on classpath, but I missed that the package was different and only name matched!

**Comment by rkorytkowski** [comment]
It seems like a failure due to connectivity issue. I've force-pushed to rebuild.

**Pull request merged**
