### PR TITLE
Port permission for operator

### PR DESCRIPTION
**Pull request by lgarciaaco**
When  `install/operator/pkg/generator/assets/install/05-syndesis-security.yml.mustache` was moved to inside the operator, apparently an old version was copied missing most of the required permissions.

Delete `patch_for_using_template_from_configmap` since the `syndesis.yml` doesn't contain the resources, not need to debug this file

Some generated stuff ...

### CODE REVIEW

**Comment by lgarciaaco** [comment]
@chirino, @zregvart what about I delete `install/generator/` since it is not used anymore?

**Comment by lgarciaaco** [comment]
Fixes https://github.com/syndesisio/syndesis/issues/5934

**Comment by zregvart** [comment]
> @chirino, @zregvart what about I delete `install/generator/` since it is not used anymore?

That sets us on a road where we need to have other environments (developer staging, product staging, evaluation) supporting operator, so we need to coordinate with those teams.

**Comment by lgarciaaco** [comment]
> > @chirino, @zregvart what about I delete `install/generator/` since it is not used anymore?
> 
> That sets us on a road where we need to have other environments (developer staging, product staging, evaluation) supporting operator, so we need to coordinate with those teams.

I don't get it. Files aren't used by the operator, if some team or tool is using them, they should be using the new location

**Comment by zregvart** [comment]
> I don't get it. Files aren't used by the operator, if some team or tool is using them, they should be using the new location

Ah, I thought we lost the template entirely. Then we need to notify the other teams of the location change with and we need update our tooling with the new location.

**Comment by lgarciaaco** [comment]
> > I don't get it. Files aren't used by the operator, if some team or tool is using them, they should be using the new location
> 
> Ah, I thought we lost the template entirely. Then we need to notify the other teams of the location change with and we need update our tooling with the new location.

You are right, there is no template anymore with the latest version. But the .mustache files still and they are used from within the operator. @chirino correct me if I am not telling the truth.

Nevertheless we can have a separate discussion for that topic, in this PR I am not deleting the files *yet*

**Comment by lgarciaaco** [comment]
fixes https://github.com/syndesisio/syndesis/pull/5954

**Pull request merged**
