### PR TITLE
chore: Update to AtlasMap 1.35.5 in Integration BOM

### PR DESCRIPTION
**Pull request by zregvart**
We need to update AtlasMap to 1.35.5 in Integration BOM as well,
otherwise our integrations run with older version.

cc @igarashitm

### CODE REVIEW

**Comment by zregvart** [comment]
> hi guys, which bug is this PR fixing?

None, I didn't think we need a bug for bumping versions.

**Comment by paoloantinori** [comment]
normally we don't need it. 

but since we are in code freeze, it means that only bug related commits can get in.

**Comment by zregvart** [comment]
@paoloantinori this is an additional task that we need to do for Integration BOM, a follow-on on the AtlasMap upgrade we did in #3127.

**Comment by paoloantinori** [comment]
thanks, the correlation with that activity was what was needed.

**Pull request merged**
