### PR TITLE
Support, incorporated feedback from UX

### LINKED ISSUE #334: Support Page UX Design
|</img> @dongniwang | [2017-10-17](https://github.com/syndesisio/syndesis-ux/issues/47) | UX Design  |
|-|-|-|

### PR DESCRIPTION
**Pull request by paoloantinori**
fixes  #334,  #1288

@michael-coker   I might use your help in aligning the spinner and the notification box

### CODE REVIEW

**Comment by michael-coker** [comment]
Thanks @paoloantinori! I ran this by @sjcox-rh and she suggested allowing "Select All" to toggle selecting all filtered integrations, and updating the link text to "Deselect All" when all filtered integrations are selected.

Otherwise this looks good to me.

**Comment by michael-coker** [comment]
Also worth mentioning, looks like "bulk selection" will be an option in the PF toolbar at some point. https://github.com/patternfly/patternfly-design/issues/341

**Comment by michael-coker** [comment]
My layout changes for the spinner and a global change to the spacing in PF toolbar filter labels are here https://github.com/michael-coker/syndesis/tree/support_ui

**Comment by michael-coker** [comment]
@paoloantinori looks great, thank! Did you see my comment re: the "select all" button toggling the select all functionality, and toggling the link text between "Select All" and "Deselect All"?

https://github.com/syndesisio/syndesis/pull/1586#issuecomment-366050428

I also added some code to [/app/ui/src/scss/utils/_overrides.scss](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/scss/utils/_overrides.scss) that I was hoping to make globally across the app.

    .toolbar-pf {
      .filter-pf {
        .list-inline {
          margin-left: -3px;
        }
      }
    }

That would address the small space before the first filter label here. It's an issue across all of the toolbars in syndesis that have filter labels.

screen shot 2018-02-16 at 10 06 27 am

Here's what it looks like after the update

screen shot 2018-02-16 at 10 07 36 am

Should I submit another PR with that change? I also removed some css from `support.component.scss` that isn't reflected in the merge that I can submit in the PR, too.

**Comment by paoloantinori** [comment]
Hi Micheal, yes, please open directly I PR.

I had squashed the commits of my branch, so I had to manually pick your
edits and I might have missed some.

**Comment by michael-coker** [comment]
done! https://github.com/syndesisio/syndesis/pull/1599

**Pull request merged**
