### PR TITLE
(chore) remove dependency on camel-core from rest

### PR DESCRIPTION
**Pull request by nicolaferraro**
@rhuss this should be sufficient.. I don't see camel anymore in rest/runtime `dependency:tree`

### CODE REVIEW

**Comment by nicolaferraro** [comment]
failure unrelated.. although scary..

**Comment by zregvart** [comment]
> failure unrelated.. although scary..

Yeah, I've seen that once before, was not able to reproduce (created  #1345)

**Comment by nicolaferraro** [comment]
retest this please

**Comment by nicolaferraro** [comment]
Still unrelated, will fix

**Comment by nicolaferraro** [comment]
Not unrelated.. camel brought jaxb-core, that is a required dependency

**Comment by nicolaferraro** [comment]
@rhuss can we merge this?

**Pull request merged**
