### PR TITLE
Backport: Cross console navigation

### PR DESCRIPTION
**Pull request by dlabaj**
Backport for PR #8561

### CODE REVIEW

**Comment by claudio4j** [comment]
Is there an ENTESB issue for this ? Is this feature required to go in Fuse Online 7.7 ? A reminder, tomorrow is code freeze.

**Comment by claudio4j** [comment]
Today is code freeze, is this PR going to merged today ?

**Comment by gashcrumb** [comment]
@dlabaj just needs to rebase this and the other one on master and hopefully it should be ready to go in.

**Comment by dlabaj** [comment]
retest this please

**Comment by dlabaj** [comment]
@gashcrumb Can we get this into the build now that Circle CI is fixed?

**Pull request merged**
