### PR TITLE
feat: finish up ci/cd dialog functions (almost)

### LINKED ISSUE #4494: Implement UXD design for add to CI/CD dialog
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Implement this design -> https://redhat.invisionapp.com/share/E9QCV528WVN#/screens/345130937

Using this info -> https://github.com/syndesisio/syndesis/issues/4326

backend API -> https://github.com/syndesisio/syndesis/blob/f178db73b5124913ffeaf84456b92b0e4cb2b78b/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/continuousdelivery/ContinuousDeliveryHandler.java

Object definition -> https://github.com/syndesisio/syndesis/blob/f178db73b5124913ffeaf84456b92b0e4cb2b78b/app/common/model/src/main/java/io/syndesis/common/model/integration/ContinuousDeliveryEnvironment.java

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #4494 

Well, almost.  The rename function doesn't work, I'm not sure if I just don't have the request data set up or what.  For example I wound up making myself an environment literally named `\{ "environment": "foo", "newEnvironment": "bar" \}`, oops.  But from what I can see the API expects just a string, but I send it that and it's rejected.

The "remove" functionality works I think as described.  The "add" button next to the dialog kinda didn't make sense to me but I think the way it behaves is as described.

Anyhoo, @riccardo-forina @dhirajsb if you get a chance to play with it that'd be awesome, it's like 90% there I think...

image

### CODE REVIEW

**Comment by dhirajsb** [comment]
I tried testing locally but all links, `Add new`, `Edit` and `Remove` point to `https://syndesis.192.168.64.42.nip.io/null` and reload the ui when clicked.

**Comment by dhirajsb** [comment]
Sorry, it was an issue with my environment. Actions `Add new`, and `Remove` are indeed working. `Rename` doesn't seem to be working and adds braces around the new value for some reason. For example, the value `testing` becomes `{"testing"}`.

**Comment by dhirajsb** [comment]
Ok, I tested a little more, and it looks like it's complaining that the request `Content-Type` should be set to 'application/json' instead of 'plain/text'.

**Comment by riccardo-forina** [comment]
Thanks @dhirajsb, adding the content-type header fixed the issue.
@gashcrumb I made the form take the full width, but other than that it LGTM.

**Comment by gashcrumb** [comment]
Awesome, thanks guys!

**Pull request merged**
