### PR TITLE
Clean and remove outdated and unused code and docs.

### PR DESCRIPTION
**Pull request by claudio4j**

### CODE REVIEW

**Comment by claudio4j** [comment]
@gashcrumb is `ux` directory outdated and a candidate to be removed ?

**Review by Delawen — APPROVED** [review]
About time!

**Review by zregvart — CHANGES_REQUESTED** [review]
I would not remove `project/proposals`, they're the only technical documentation we have, and it's still relevant as far as I know.

**Review by zregvart — CHANGES_REQUESTED** [review]
Perhaps we need to leave the `project/designs/error-handling.md` as well.

**Comment by claudio4j** [comment]
> I would not remove `project/proposals`, they're the only technical documentation we have, and it's still relevant as far as I know.

I just put it back. Thanks for reviewing.

**Comment by gashcrumb** [comment]
> @gashcrumb is `ux` directory outdated and a candidate to be removed ?

Just to follow up, we could, it wouldn't be hard to bring it back anyways.  @kahboom when's the last time you've needed to look here in [ux](https://github.com/syndesisio/syndesis/tree/1.12.x/ux)?

**Comment by kahboom** [comment]
@gashcrumb I forgot it existed. Used to be useful but now is quite outdated. I don't see any problem with it being removed.

**Pull request merged**
