### PR TITLE
refactor: add concur icon and description

### PR DESCRIPTION
**Pull request by zregvart**
This adds the Concur icon and the updates the description.

screenshot-2018-6-15 syndesis 1

cc @syndesisio/uxd @syndesisio/support-docs @KurtStam @gaughan

### CODE REVIEW

**Comment by KurtStam** [comment]
@zregvart let's commit. If UX comes up with something else we can always update.

**Comment by gaughan** [comment]
Looks great!

**Comment by zregvart** [comment]
> @zregvart let's commit. If UX comes up with something else we can always update.

Perhaps @gaughan and @TovaCohen can offer better name and description, the "Combined Concur 3.0 Swagger API" and "Use SAP Concur for travel and expense management" is probably not the best we can do. Super trivial to make changes to those.

**Comment by TovaCohen** [comment]
How's this:

Concur
SAP expense, travel, and invoice management

**Comment by gaughan** [comment]
How about? :

Concur (SAP)
Manage invoices, travel, and expenses.

**Comment by sjcox-rh** [comment]
@zregvart Icon looks good! That was the latest Icon I found and since you were able to make it a vector, no need to change it.  Thanks!

**Pull request merged**
