### PR TITLE
initial lsp quick fix framework

### PR DESCRIPTION
**Pull request by blafond**
Initial dv lsp quick fix support - TEIIDTOOLS-970

### CODE REVIEW

**Comment by blafond** [comment]
This PR is just to get something in for quick fixes. The process involves capturing the incremental errors during parsing, constructing a diagnostics object including an error code which can be used to return applicable quick fixes. 

Both the  table body and query expression clauses are missing key parsing, diagnostic and quick fix support.

Targeting the **query-primary** structure as the next step for query expression support is good and I'll log that specifically.

**Comment by KurtStam** [comment]
@dependabot rebase

**Comment by KurtStam** [comment]
@blafond Can you also open a GH issue for this, so it's easier to understand what's going on? It's a rather large PR..

**Comment by claudio4j** [comment]
Closing, as DV was removed from syndesis.

**Pull request closed without merging**
