### PR TITLE
ENTESB-12090: Fix addons parameter when executing app

### PR DESCRIPTION
**Pull request by phantomjinx**
* addons value should be a bool rather than a string

### CODE REVIEW

**Comment by KurtStam** [comment]
@phantomjinx Can you add a bit of context?I was expecting to see a simple type change and this PR seems much more comprehensive.

**Comment by heiko-braun** [comment]
@phantomjinx Should the `vendor` directory be included or was it by accident?

**Comment by phantomjinx** [comment]
@heiko-braun @KurtStam 
The vast majority of this PR is simply auto regenerated bits n pieces updated when the operator is recompiled. I'd prefer to leave it all out but to do so would simply mean everyone else seeing it all when they compile.

The only germaine file change is https://github.com/syndesisio/syndesis/pull/7259/files#diff-9f105b2a895920f82ad1c20a09c87eafR9

**Comment by heiko-braun** [comment]
> The vast majority of this PR is simply auto regenerated bits n pieces updated when the operator is recompiled. I'd prefer to leave it all out but to do so would simply mean everyone else seeing it all when they compile.


I don't know. What do others recommend? @lgarciaaco @nicolaferraro @chirino Should we commit `vendor` and other pieces as @phantomjinx suggests, or leave it out?

**Comment by zregvart** [comment]
@phantomjinx this needs a rebase

**Pull request merged**
