### PR TITLE
ENTESB-19709 fix: bump AtlasMap to 2.3.19

### PR DESCRIPTION
**Pull request by gashcrumb**
This change bumps the AtlasMap frontend to 2.3.19 along with ky to fix an issue where the AtlasMap UI can hang when loading up a csv document.

@igarashitm @claudio4j FYI

### CODE REVIEW

**Review by igarashitm — APPROVED** [review]
:+1:

**Review by claudio4j — APPROVED** [review]
Looks good. I will update the java pom files, to follow same version, once this is merged.

**Comment by claudio4j** [comment]
There is a `ui` test failing, is it related ?

**Comment by gashcrumb** [comment]
@claudio4j yep, it was, just pushed a fix

**Comment by gashcrumb** [comment]
Oh, also I think @igarashitm is planning on bumping the java version, so probably there'll be another commit on this branch in a few.

**Comment by claudio4j** [comment]
@igarashitm `app/extension/bom/pom.xml` also have to be updated.

**Pull request merged**
