### PR TITLE
[ENTESB-14339] Integration Tests for SOAP

### PR DESCRIPTION
**Pull request by christophd**
Successor of #9228

### CODE REVIEW

**Comment by christophd** [comment]
@Delawen opened this PR based on your #9228 with the fix for SoapConnector_Fault integration test. The test was successful!

Though some tests fail with
`java.io.IOException: No space left on device`

What can we do?

**Comment by christophd** [comment]
@zregvart @Delawen any ideas how to get the CI jobs working?

**Comment by zregvart** [comment]
We're trying to address that in #9528 and in a parallel effort to build the images on QE Jenkins. For this PR you can retry the integration tests; try touching one of the POM files to invalidate the cache; or simply ignore them and merge. The QE smoke tests are hung currently, something to do with locks on OpenShift, I'm guessing either an outage or a backlog of tests that's running caused by the outages earlier.

**Comment by Delawen** [comment]
I would merge already :D

**Comment by christophd** [comment]
@zregvart thanks for the explanation. I vote for merge now. No risk, no fun!

**Pull request merged**
