### PR TITLE
ENTESB-14237 1.12.x

### PR DESCRIPTION
**Pull request by rkorytkowski**
https://issues.redhat.com/browse/ENTESB-14237

(cherry picked from commit 3bbb6c632acfe42ac3171235b88c5bd3ea5939a0)

### CODE REVIEW

**Comment by mkralik3** [comment]
retest this please

**Comment by gashcrumb** [comment]
Is this a one-time thing or something actually introduced by this change?

image

**Comment by mkralik3** [comment]
No, it is caused by instability of our infra because currently all our 4.6 clusters have some problem with PVC due to which syndesis-db is not ready. We reinstalling that clusters.

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Pull request merged**
