### PR TITLE
set docker registry and prefix per image base

### PR DESCRIPTION
**Pull request by lgarciaaco**
Add more properties to the CR so we are able to fine tune the docker image path for syndesis components.

|Property path|Type|Description|
|------------ |----|-----------|
|Spec.Components.ImagePrefix|string| Prefix for `ImageStreams` for syndesis components|
|Spec.Components.Server.Registry|string|registry used for the syndesis-server `ImageStream`|
|Spec.Components.Server.ImagePrefix|string|prefix used for the syndesis-server `ImageStream`|
|Spec.Components.Meta.Registry|string|registry used for the syndesis-meta `ImageStream`|
|Spec.Components.Meta.ImagePrefix|string|prefix used for the syndesis-meta `ImageStream`|
|Spec.Components.UI.Registry|string|registry used for the syndesis-ui `ImageStream`|
|Spec.Components.UI.ImagePrefix|string|prefix used for the syndesis-ui `ImageStream`|
|Spec.Components.S2I.Registry|string|registry used for the syndesis-S2I `ImageStream`|
|Spec.Components.S2I.ImagePrefix|string|prefix used for the syndesis-S2I `ImageStream`|
|Spec.Components.Upgrade.Tag|string|tag used for the upgrade pod|
|Spec.Components.Upgrade.Registry|string|registry used for the upgrade pod|
|Spec.Components.Upgrade.ImagePrefix|string|prefix used for the upgrade pod|

Fix some formating
Fixes ENTESB-11721

### CODE REVIEW

**Comment by lgarciaaco** [comment]
This is solved in master by https://github.com/syndesisio/syndesis/pull/6722

**Comment by heiko-braun** [comment]
@asmigala Mind a review?

**Comment by heiko-braun** [comment]
@lgarciaaco Should add the same options for `Spec.Components.Komodo`?

**Comment by lgarciaaco** [comment]
> What about `Spec.Components.Komodo`?

@heiko-braun after speaking with @asmigala yesterday, the scope was to do this for syndesis components (meta, server, ui, s2i, upgrade). Andrej do you need it for komodo also? I don't mind adding it

**Comment by lgarciaaco** [comment]
fixes ENTESB-11707

**Pull request merged**
