### PR TITLE
chore: enforce and converge dependencies

### PR DESCRIPTION
**Pull request by zregvart**
This enforces the dependency convergence via Maven Enforcer rule and
converges the dependencies to a single version. In cases this meant
removing a Syndesis-declared dependency, upgrading or (rarely)
downgrading a dependency.

Going forward this will fail the build in case non-converged
dependencies are found and hopefully solve dependency issues as they're
introduced.

### CODE REVIEW

**Comment by claudio4j** [comment]
There are compile time errors in mongodb connector test classes.

**Comment by zregvart** [comment]
> There are compile time errors in mongodb connector test classes.

Yeah, I'll refactor those in a separate PR.

**Comment by zregvart** [comment]
I'll rebase this on #9864 once that is merged

**Review by claudio4j — APPROVED** [review]

**Comment by zregvart** [comment]
retest this please

**Comment by mkralik3** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Pull request merged**
