### PR TITLE
fix(UI tests): Prevent problematic characters in naming of test tape files

### PR DESCRIPTION
**Pull request by kahboom**
fixes https://github.com/syndesisio/syndesis/issues/7241

- Adds a regex pattern to replace troublesome characters across platforms.
- Removes offending tapes that currently exist, adds a few with the new naming format.

### CODE REVIEW

**Comment by matskiv** [comment]
@kahboom Thanks a lot for fixing this. I literally just bumped into the issue with `?` character in the file name. My use case involved go mod to import 1.8.x branch of the operator ([logs](https://gist.github.com/matskiv/05d1fe01fbd9153186488f5128a95a0a)).

Would it be possible to get this change into 1.8.x branch? If it can be done with just a cherry-pick - let me know, I can send a PR with that.

**Comment by kahboom** [comment]
@matskiv No problem!

Am I understanding correctly that you'd just want it in the 1.8.x branch for your use case, so nothing to do with it being included in the next release of Fuse? If you're intending for the Fuse 7.5.1 release, I think it might be a bit too late, but I'm not sure--maybe @heiko-braun knows?

On a side note--Heiko, if you can also clarify if it's still ok to backport into the 1.8.x branch, and what exactly it correlates to in terms of product (for future reference), that'd be great.

**Comment by matskiv** [comment]
@kahboom Correct, my use case is not related to next/current Fuse patch release.

Just to give you a full picture - we are importing syndesis operator as a dependency for integreatly operator. We do that just to use structs defined in `install/operator/pkg/apis/syndesis/v1alpha1`. And I want to import branch of syndesis that matches minor version of Fuse we are currently running, and for Fuse 7.5 that would be syndesis 1.8.x, right? :)

**Comment by kahboom** [comment]
@matskiv - Ah, alright I understand. Looks like yes, you'd have to cherry pick and create a PR against 1.8.x. Since I still don't know who determines what can go into `1.8.x`, I'd probably ping Gary and/or Heiko when you open it just to make sure.

**Comment by matskiv** [comment]
Will do. Thanks a lot 👍

**Pull request merged**
