### PR TITLE
chore: suppress circular reference warnings

### LINKED ISSUE #1445: Fix circular references
Currently when the UI is built we get a bunch of warnings about circular references.  These need to be fixed, they create noise and can create hard to solve runtime problems.

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #1445 (sorta in a doesn't fix it but hide it kinda way)

### CODE REVIEW

**Comment by kahboom** [comment]
Tests failed

**Comment by gashcrumb** [comment]
retest this please

**Comment by zregvart** [comment]
I wonder if those tests failed because they compare the JSON too literally and the `pre-commit` modified the expected JSON files. Let me checkout this and see.

**Comment by gashcrumb** [comment]
That's weird though this is just our angular CLI config, changing it shouldn't have an impact on anything that isn't UI related...

**Comment by zregvart** [comment]
Yeah, that would make that test flaky, i.e. not pre-commit that's causing it to fail.

**Comment by zregvart** [comment]
Oh you know what, I found out it downloads a new -SNAPSHOT of Swagger, after I removed my locally cached copy it fails for me also.

**Comment by zregvart** [comment]
Let's see if #2029 passes the checks on CI and gets merged...

**Pull request merged**
