### PR TITLE
backport 1.11.x fix for ENTESB-12104 - demoData flag used to add sampledb

### PR DESCRIPTION
**Pull request by KurtStam**
fixes https://issues.redhat.com/browse/ENTESB-12104

### CODE REVIEW

**Comment by KurtStam** [comment]
Should this PR be moved to 1.12.x ?

**Comment by zregvart** [comment]
> Should this PR be moved to 1.12.x ?

In my mind its needs to be on both 1.11 and 1.12

**Comment by KurtStam** [comment]
@zregvart I've created a backport to 1.12.x. I think it one can be closed since it's been released.

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Pull request merged**
