### PR TITLE
fix(#4590): Fix dependency on integration-runtime-tests in odata

### PR DESCRIPTION
**Pull request by phantomjinx**
* Make all test dependencies in odata active if basepom.check.skip-all
  is not defined or false, ie. if flash profile active.

### CODE REVIEW

**Comment by phantomjinx** [comment]
@zregvart 
When
- basepom.check.skip-all is true then the flash profile has been invoked and no tests are run at all. Therefore, none of the test dependencies are required.
- basepon.check.skip-all is false or not defined then the flash profile has NOT been invoked and all tests are run. Therefore all test dependencies are required, including an expectation that integration-runtime.tests has been built and is available.

**Comment by zregvart** [comment]
Other connectors also depend on `integration-runtime` in `test` scope. I think we need to address what the root cause of the issue is rather than fixing the symptoms.

**Comment by phantomjinx** [comment]
@zregvart 

> Other connectors also depend on `integration-runtime` in `test` scope. I think we need to address what the root cause of the issue is rather than fixing the symptoms.

You're right other connectors depend on integration-runtime in the test scope but the odata connector is the only one that depends on integration-runtime-tests in the test scope, since the unit tests inherit from [IntegrationTestSupport](https://github.com/syndesisio/syndesis/blob/master/app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java).

**Comment by zregvart** [comment]
> You're right other connectors depend on integration-runtime in the test scope but the odata connector is the only one that depends on integration-runtime-tests in the test scope, since the unit tests inherit from [IntegrationTestSupport](https://github.com/syndesisio/syndesis/blob/master/app/integration/runtime/src/test/java/io/syndesis/integration/runtime/IntegrationTestSupport.java).

This is the root issue, that class is in `src/test/java` so it is not meant to be reused outside of the `integration-runtime` test suite. It either needs to be refactored and moved to `src/main/java` or the tests in the OData connector need to be refactored not to use it.

**Comment by phantomjinx** [comment]
@zregvart 
How about https://maven.apache.org/guides/mini/guide-attached-tests.html ??

**Comment by phantomjinx** [comment]
Of course, the other thing to consider is that a flash build no longer downloads any of the dependencies required for the tests and as such this is far more streamlined and efficient. Would the use of this profiling based on that property not be useful across all projects?

**Comment by zregvart** [comment]
> @zregvart
> How about [maven.apache.org/guides/mini/guide-attached-tests.html](https://maven.apache.org/guides/mini/guide-attached-tests.html) ??

This sounds like an easy fix to to try.

**Comment by zregvart** [comment]
> Of course, the other thing to consider is that a flash build no longer downloads any of the dependencies required for the tests and as such this is far more streamlined and efficient. Would the use of this profiling based on that property not be useful across all projects?

To me profiles scream workarounds, and they should not be. In general profiles should be used as little as possible (IMHO).

Can you expand on "flash build no longer downloads any of the dependencies required for the tests"?

**Comment by phantomjinx** [comment]
@zregvart 
Sorry missed your reply and will directly answer now. The class IntegrationTestSupport is purely for tests and provides some really useful methods that other modules can take advantage of. Therefore, to consider:
- IntegrationTestSupport is not a runtime class but only for tests;
- Maven provides means to share test code for an occasion such as this;
- It would seem pointless to have to duplicate the class' code just to avoid a test dependency.

**Comment by phantomjinx** [comment]
> To me profiles scream workarounds, and they should not be. In general profiles should be used as little as possible (IMHO).

Agree with you on the whole and careful use of profiles is preferable.

> 
> Can you expand on "flash build no longer downloads any of the dependencies required for the tests"?

If flash is switched on then all odata-connector dependencies are ignored / not downloaded. Since the tests are not required and never run then likewise these test dependencies are never required so never fetched into the m2 repository (of course some may be there from other modules but you see my point).

**Comment by zregvart** [comment]
> If flash is switched on then all odata-connector dependencies are ignored / not downloaded. Since the tests are not required and never run then likewise these test dependencies are never required so never fetched into the m2 repository (of course some may be there from other modules but you see my point).

I completely and utterly do not understand this. Are you saying that dependencies are not resolved by Maven when `flash` profile is activated?

**Comment by phantomjinx** [comment]
I completely and utterly do not understand this. Are you saying that dependencies are not resolved by Maven when flash profile is activated?

Yes. Those placed inside the profile in this pom are only resolved if the property basepom.check.skip-all is false or not defined. Therefore, the result is all test dependencies are ignored in a flash profiled build.

**Comment by phantomjinx** [comment]
> > @zregvart
> > How about [maven.apache.org/guides/mini/guide-attached-tests.html](https://maven.apache.org/guides/mini/guide-attached-tests.html) ??
> 
> This sounds like an easy fix to to try.

So looking into this a bit further ...

A test-jar is only created if the test archive is not empty. When a flash profile build is enacted, all tests are skipped and all test compilation is skipped so no test archive. Therefore, test-jar creation is skipped as well. This means that unless the specific class (and any fellows) are moved to main, a profile is necessary is odata-connector to avoid trying to resolve the dependency, ie.

1. A flash build is enacted;
2. All test compilation and running is skipped so no test classes or test jars created at all;
3. OData connector pom (atm) has a dependency to resolve on the integration-runtime-tests jar, regardless of which profile is enacted;
4. OData connector errors because it tries to resolve integration-runtime-tests dependency but that has not been compiled so not available.

Therefore, 3 choices I can see at the moment:
- Use a profile as I have done in this PR to avoid resolving the problematic dependency during a flash build;
- Add the useful test classes to the main jar of integration-runtime where they will always be compiled and available;
- Move the useful test classes to a common test module that always gets compiled but does not pollute the integration-runtime jar;

Thoughts??

@zregvart @oscerd @lburgazzoli @anyonelse

**Comment by zregvart** [comment]
> Thoughts??

Pretty much what was already said in https://github.com/syndesisio/syndesis/pull/4621#issuecomment-464772612

Except for profiles, they should not be used.

**Comment by phantomjinx** [comment]
> > Thoughts??
> 
> Pretty much what was already said in [#4621 (comment)](https://github.com/syndesisio/syndesis/pull/4621#issuecomment-464772612)
> 
> Except for profiles, they should not be used.

Thanks @zregvart 

With respect I would appreciate some others to chip in on this as I have tried to explain and further discuss the problem and merits of the proposed solution but seem to hit the metaphorical brick wall of 'profiles should not be used.' when it addresses the rather unique problem, ie. a profile is causing a dependency error and a further profile fixes it. Therefore, if someone else would like to provide guidance on how to fix this or provide a superseding PR then that would be appreciated.

**Comment by gashcrumb** [comment]
Seeing as it's master that's broken I think it's acceptable to go for a quick fix to unbreak master and have a longer term plan, is that feasible for this PR?

**Comment by zregvart** [comment]
I wonder who will then provide a proper fix and when. I'm fine with someone else taking on the responsibility to take this on.

**Comment by phantomjinx** [comment]
Just pushed an updated PR that severs the IntegrationTestSupport connection by duplicating code into the odata-connector module. Hopefully, that should satisfy everybody.

Can take this one or [4625](https://github.com/syndesisio/syndesis/pull/4625).

**Comment by phantomjinx** [comment]
Job done.

**Pull request merged**
