### PR TITLE
chore: Update to AtlasMap 1.42.6

### PR DESCRIPTION
**Pull request by igarashitm**
contains:
https://issues.jboss.org/browse/ENTESB-11870 Data mapper doesn't map anything when incoming data shape is a collection

### CODE REVIEW

**Comment by igarashitm** [comment]
Hi @squakez, is this build failure on mongodb connector an intermittent one not related to atlasmap? is it safe to merge?

**Comment by squakez** [comment]
> Hi @squakez, is this build failure on mongodb connector an intermittent one not related to atlasmap? is it safe to merge?

Yes, you can proceed. Actually the mongo is using an embedded server for unit test, and it happens from time to time to have intermittent failures, in particular running on CircleCI containers...

**Comment by igarashitm** [comment]
OK thanks, good to know - fortunately I could restart from mongodb connector in circleci and it passed this time.

**Comment by squakez** [comment]
> OK thanks, good to know - fortunately I could restart from mongodb connector in circleci and it passed this time.

I've just created this issue #6872 to investigate and try to find a resolution.

**Pull request merged**
