### PR TITLE
OData connector returns collection data shape

### PR DESCRIPTION
**Pull request by christophd**
OData connector now using json-schema array collection type where applicable

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@phantomjinx can you have a look ?

**Comment by phantomjinx** [comment]
Looks fine. As long as it will still data map ok to the likes of gmail then I am happy. ;-)

**Comment by christophd** [comment]
@phantomjinx can you provide a sample integration with odata and gmail that should be tested as a regression test?

**Comment by phantomjinx** [comment]
@christophd 

Syndesis Export : [TriPinIntegration-export.zip](https://drive.google.com/open?id=1AqdwSz-JlR1Y5w9bjbWdRkcUkrWQB0YA)

**Pull request merged**
