### PR TITLE
chore: Add a prefix of `syndesis.io` to all labels used by syndesis

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by rhuss** [comment]
@dhirajsb this PR introduces a prefix 'syndesis.io/' to all our labels. When this is merged, you need to update the prometheus configs

**Comment by dhirajsb** [comment]
@rhuss will wait for it to be merged. I'll also make pod labels being searched for by `PrometheusMetricsProviderImpl` configurable in it's config map, in case we feel like changing them in the future.

**Comment by rhuss** [comment]
@dhirajsb I guess the following error is due because of the missing update in the prometheus code ?

```
2018-04-22 15:12:51.209 ERROR [-,6342710243ee3513,6342710243ee3513,false] 1 --- [  XNIO-3 task-5] .s.e.v.h.e.SyndesisServerExceptionMapper : Internal Server Exception. Index: 0, Size: 0

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_151]
	at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_151]
	at io.syndesis.server.metrics.prometheus.PrometheusMetricsProviderImpl.getTotalIntegrationMetricsSummary(PrometheusMetricsProviderImpl.java:160) ~[server-metrics-prometheus-1.3.5-20180422.jar!/:1.3.5-20180422]
	at io.syndesis.server.endpoint.v1.handler.metrics.IntegrationMetricsHandler.get(IntegrationMetricsHandler.java:65) ~[server-endpoint-1.3.5-20180422.jar!/:1.3.5-20180422]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[resteasy-jaxrs-3.1.4.Final.jar!/:3.1.4.Final]
```

Nevertheless, could this be coded a bit  more robust ? I.e. either a specific error message (instead of an IndexOutOfBoundsException) or ignoring it and provide a sane fallback ?

**Comment by dhirajsb** [comment]
@rhuss will add checks for that to avoid this in the future.

**Pull request merged**
