### PR TITLE
Add support for rolling deployments in Fuse Online

### PR DESCRIPTION
**Pull request by lgarciaaco**
Fixes https://issues.redhat.com/browse/ENTESB-12382

### CODE REVIEW

**Comment by lgarciaaco** [comment]
By looking at the logs this seems to work fine. How I have tested:

1. Deploy syndesis and wait it is installed
2. Change the image in syndesis-server DeploymentConfig to something different that `latest`. This will trigger a deployment.

You can see that the new version of server pod is spun up next to the old version, and only when the health check of the newest pod passed, the old pod is killed.
```
syndesis-server-2-deploy   0/1       Pending   0         0s
syndesis-server-2-deploy   0/1       Pending   0         0s
syndesis-server-2-deploy   0/1       ContainerCreating   0         0s
syndesis-server-2-deploy   0/1       ContainerCreating   0         8s
syndesis-server-2-deploy   1/1       Running   0         9s
syndesis-server-2-t8ntk   0/1       Pending   0         0s
syndesis-server-2-t8ntk   0/1       Pending   0         0s
syndesis-server-2-t8ntk   0/1       ContainerCreating   0         0s
syndesis-server-2-t8ntk   0/1       ContainerCreating   0         8s
syndesis-server-2-t8ntk   0/1       Running   0         19s
syndesis-server-2-t8ntk   1/1       Running   0         1m
syndesis-server-1-k54hk   1/1       Terminating   0         16m
syndesis-server-1-k54hk   1/1       Terminating   0         16m
syndesis-server-1-k54hk   0/1       Terminating   0         16m
syndesis-server-1-k54hk   0/1       Terminating   0         16m
syndesis-server-1-k54hk   0/1       Terminating   0         16m
syndesis-server-2-deploy   0/1       Completed   0         1m
syndesis-server-2-deploy   0/1       Completed   0         1m
``` 

By looking at the logs from both pods, no errors are shown. Also the older pod starts shutting down when the new one finished starting up.

Pod with older version:
```
2020-05-04 09:08:25.237  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.BaseIntegrationController      : Checking integrations for their status.
2020-05-04 09:09:25.237  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.BaseIntegrationController      : Checking integrations for their status.
2020-05-04 09:09:33.449  INFO [-,,,] 1 --- [      Thread-15] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@56de5251: startup date [Mon May 04 08:53:35 UTC 2020]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@1e67b872
2020-05-04 09:09:33.454  INFO [-,,,] 1 --- [      Thread-15] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@6b0615ae: startup date [Mon May 04 08:54:57 UTC 2020]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@56de5251
2020-05-04 09:09:33.488  INFO [-,,,] 1 --- [      Thread-15] io.undertow.servlet                      : Destroying Spring FrameworkServlet 'dispatcherServlet'
2020-05-04 09:09:33.494  INFO [-,,,] 1 --- [      Thread-15] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2020-05-04 09:09:33.504  INFO [-,,,] 1 --- [      Thread-15] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2020-05-04 09:09:33.504  INFO [-,,,] 1 --- [      Thread-15] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2020-05-04 09:09:33.506  INFO [-,,,] 1 --- [      Thread-15] i.s.s.m.DeploymentStateMonitorController : Stopping state monitor.
2020-05-04 09:09:33.514  INFO [-,,,] 1 --- [      Thread-15] i.s.s.c.i.online.IntegrationController   : Stopping IntegrationController (s2i)
```
Pod with newer version:
```
2020-05-04 09:09:20.704  INFO 1 --- [           main] io.syndesis.server.runtime.Application   : Started Application in 61.1 seconds (JVM running for 64.4)
2020-05-04 09:09:22.924  INFO 1 --- [  XNIO-2 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-05-04 09:09:22.988  INFO 1 --- [  XNIO-2 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-05-04 09:09:23.000  INFO 1 --- [  XNIO-2 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 12 ms
2020-05-04 09:09:59.427  INFO 1 --- [ler Scheduler-0] i.s.s.c.i.BaseIntegrationController      : Checking integrations for their status.
2020-05-04 09:10:59.427  INFO 1 --- [ler Scheduler-0] i.s.s.c.i.BaseIntegrationController      : Checking integrations for their status.
2020-05-04 09:11:59.427  INFO 1 --- [ler Scheduler-0] i.s.s.c.i.BaseIntegrationController      : Checking integrations for their status.
```

**Comment by KurtStam** [comment]
So I'm assuming this is for the syndesis-server pod only for now?

**Comment by lgarciaaco** [comment]
> To what degree does it reduce the downtime? Can you quantify the differences?

@heiko-braun I didn't notice any downtime at all which is what I would expect to happen. To be really sure we would need to setup some Prometheus rules for syndesis-server service along with some checks. This is probably a good idea regardless.

**Comment by heiko-braun** [comment]
@lgarciaaco what I look for is a comparison between the end-to-end upgrade downtime. If one component like the server uses a rolling strategy, the overall downtime should have decreased.

**Comment by zregvart** [comment]
Server runs database schema migrations on startup, what can happen is that the newer version is run changes the database schema in a backward incompatible way and then crashes rolling back the deployment to the old version, which can cause issues as the schema is not backward compatible.

Server also runs several tasks asynchronously and they will be run in both pods while the newer version of the server is not ready, I don't think we have evaluated if any of those tasks can be run in parallel safely.

**Comment by lgarciaaco** [comment]
> Server runs database schema migrations on startup, what can happen is that the newer version is run changes the database schema in a backward incompatible way and then crashes rolling back the deployment to the old version, which can cause issues as the schema is not backward compatible.
> 
> Server also runs several tasks asynchronously and they will be run in both pods while the newer version of the server is not ready, I don't think we have evaluated if any of those tasks can be run in parallel safely.

At this point I believe we have to do a bit of refactor in the server before we merge this to be sure we wont have problems. I will put together a doc with the points @zregvart mentioned and another problem that @mkralik3 found.

**Comment by zregvart** [comment]
Converted to draft

**Comment by claudio4j** [comment]
@lgarciaaco is this PR still WIP ? Can this be closed ?

**Pull request closed without merging**
