### PR TITLE
fix(ui) Patch codemirror's lint script file

### PR DESCRIPTION
**Pull request by phantomjinx**
* ReferenceError occurs when codemirror's lint.js is uglified. Since it
  will take some time for a PR to be accepted and a new version released,
  uses package-patch to make the small code change and fix the problem.

* package-patch will auto-run on post-install to ensure the patch is
  applied to the file. See https://www.npmjs.com/package/patch-package
  for details.

#3760

### CODE REVIEW

**Comment by gashcrumb** [comment]
@phantomjinx use `yarn` instead of `npm` if possible, `npm` isn't even installed on the CI machine.  It should be a direct switch I think.

**Comment by gashcrumb** [comment]
Looks like you want to use the `--use-yarn` flag so it knows to use `yarn` vs `npm`

**Comment by phantomjinx** [comment]
@gashcrumb 

So in order to workaround yarn's lack of postinstall support (explained [here](https://github.com/ds300/patch-package#why-use-postinstall-postinstall-with-yarn)), [patch-package](https://github.com/ds300/patch-package) recommends to install either [postinstall-prepare](https://github.com/ds300/patch-package) or [postinstall-postinstall](https://github.com/ds300/postinstall-postinstall) (both appear to be the same package but simply have a rename). However, these packages  do [depend](https://github.com/ds300/postinstall-postinstall/blob/master/run.js#L14) on npm hence the error in circleci builds.

The workaround is to uninstall it and just use the prepare hook. This means that the patch is not applied on a _yarn remove_ but given this specific patch is only required on a release install (full uglify) then that shouldn't be an issue at the moment. I have opened an [issue](https://github.com/ds300/postinstall-postinstall/issues/2) with postinstall-postinstall so assuming that gets fixes we can reinstall in the future.

**Comment by gashcrumb** [comment]
> The workaround is to uninstall it and just use the prepare hook. This means that the patch is not applied on a yarn remove but given this specific patch is only required on a release install (full uglify) then that shouldn't be an issue at the moment.

Yep, I think that's fine, awesome!

**Pull request merged**
