### PR TITLE
chore(operator): auto-update README.md

### PR DESCRIPTION
**Pull request by zregvart**
This tries to auto-update the README.md based on the README.md.template and the CRD YAML file.

### CODE REVIEW

**Comment by zregvart** [comment]
@lgarciaaco this is what I'd like to do for the README...

**Comment by lgarciaaco** [comment]
Yep yep, I like it. 

We need to move back the comments to the CR(I put them in the configuration package)

**Comment by zregvart** [comment]
@lgarciaaco I've rebased it, though we don't seem to have the descriptions for individual properties in the CRD YAML any more, it's been a while not sure if that was brought on by the #7025 or we lost it in the recent refactoring (and I can't regenerate on my end (#7247). We can park this for now, if you have the time can you have a look into finishing this work?

**Comment by lgarciaaco** [comment]
> @lgarciaaco I've rebased it, though we don't seem to have the descriptions for individual properties in the CRD YAML any more, it's been a while not sure if that was brought on by the #7025 or we lost it in the recent refactoring (and I can't regenerate on my end (#7247). We can park this for now, if you have the time can you have a look into finishing this work?

@zregvart Most descriptions are back with https://github.com/syndesisio/syndesis/pull/7153, which was merged after your comment :-)

**Comment by zregvart** [comment]
Let me rebase this :)

**Comment by zregvart** [comment]
I've rebased and regenerated the README, I'm still missing the descriptions in the CRD YAML, some of the properties are not present and for some that have description in code the description is not present in the YAML. For example:

No description in YAML, has description in code:

https://github.com/syndesisio/syndesis/blob/4f5cfe5a7e9af5992248787842e095854e528dfd/install/operator/deploy/crds/syndesis_v1alpha1_syndesis_crd.yaml#L121-L122

https://github.com/syndesisio/syndesis/blob/4f5cfe5a7e9af5992248787842e095854e528dfd/install/operator/pkg/syndesis/configuration/configuration.go#L120

Missing in YAML:

https://github.com/syndesisio/syndesis/blob/4f5cfe5a7e9af5992248787842e095854e528dfd/install/operator/pkg/syndesis/configuration/configuration.go#L51

I don't think the CRD YAML are up to date with code (#7247)

**Pull request closed without merging**
