### PR TITLE
Fixing dependencies

### PR DESCRIPTION
**Pull request by Delawen**
@phantomjinx my small contribution to this

### CODE REVIEW

**Comment by christophd** [comment]
Is this a work in progress PR? In case it is I would suggest to mark the PR with the respective label and reflect WIP also in PR title.

**Comment by Delawen** [comment]
Yes and no. If someone merge it, I will start a new PR.

I don't have commit rights to the main repo and I want to avoid someone working on the camel 3 branch duplicating the work.

**Comment by christophd** [comment]
It's just that the unit tests are failing on this PR. I do not know though if this is caused by the PR or already has been a common failing state on the branch before.

**Comment by Delawen** [comment]
This is the camel 3 branch which still is not a working branch. I am fixing dependencies right now, which doesn't look a quick work.

I am just not sure how to mark that I am working on that branch to try to avoid duplicated work.

**Comment by lburgazzoli** [comment]
@Delawen maybe open an issue and self assign it :)

**Comment by Delawen** [comment]
Ook :D

**Pull request closed without merging**
