### PR TITLE
[Backport-1.9.x] Update Camel version to 2.23.2.fuse-760024

### PR DESCRIPTION
**Pull request by christophd**
Manual backport #7761

### CODE REVIEW

**Comment by christophd** [comment]
@mmuzikar @avano can you please rerun the QE Jenkins build? I guess it failed because of a timeout while waiting for the CircleCi job to finish.

**Comment by avano** [comment]
retest this please

**Comment by avano** [comment]
@christophd you can use `retest this please` next time :-) it's running now

**Comment by christophd** [comment]
@avano ha ha that's great ! was not aware of this. And it's always good to be polite to your bots

**Pull request merged**
