### PR TITLE
[ResetDB] Check if syndesis-dv svc is present before trying to reset it

### PR DESCRIPTION
**Pull request by avano**

### CODE REVIEW

**Comment by zregvart** [comment]
Thoughts for a potential refactor, not sure if it was a good idea to depend on dv in this part, though if `syndesis-dv` service is not present would not we get a `UnknownHostException` which we could separately handle from the `IOException`.

**Comment by avano** [comment]
It was requested by QE, but it seems there is no particular reason that it the dv stuff reset should be part of syndesis server reset and we can handle it in our test suite.

So there are two options, either to remove the DV reset from here, or catch `UnknownHostException`, I assume you prefer the first one, right? :-)

**Comment by zregvart** [comment]
@avano I think it would be better if the client invoked two endpoints, not sure if there's an issue doing that from tests.

**Comment by avano** [comment]
@zregvart no issue at all, I'll do it in the testsuite first and then I'll edit this PR to remove the dv stuff

**Comment by zregvart** [comment]
@avano also no hurry, we can merge this and work on refactoring later...

**Comment by zregvart** [comment]
Thanks!

**Pull request merged**
