### PR TITLE
Fixes #1855: Allow correlating a Activity Step back to the step id in an integration.

### LINKED ISSUE #1855: [monitoring] The Integration Activity Table should allow for checking detailed activity logs
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Currently, the activity tab in the integration detail view shows a non-detailed listview of activity entries. Such information is pretty basic and we need to broaden each activity details upon request.

## Expected behavior
By clicking on each row, a nested view will unfold displaying a table with a corresponding detailview featuring the following:

- Step name
- Time (isn't this redundant, being more likely the same for all the items displayed at the table?)
- Duration (in seconds)
- Status (`Error` | `Success`)
- Output (plain text or `n/a` when blank)

## Screenshot
captura de pantalla 2018-03-06 a las 20 30 03

## API Endpoints and Schemas

TBD @chirino Could you fill this out? Thx

## Tasks involved / Steps to Reproduce

1. Create and deploy an integration. Wait for its `published` status.
2. Go to the integration detail view and click on activity
3. On the activity rows displayed (if any), click on the arrow on the left.
4. Check that a sub view contained tabular data matching the design above is rendered

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by zregvart** [comment]
@chirino I think the ActivityTrackingControllerTest also needs to be modified

**Comment by chirino** [comment]
Yes.  I think your right. But I’m about to jump on a flight. :(. 

I won’t be able to get back to this till tomorrow at best.

**Comment by deeleman** [comment]
Can anyone take over? Otherwise, we'll have to defer #1855 as post-TP4

**Comment by zregvart** [comment]
cc @deeleman

**Comment by deeleman** [comment]
Thanks @zregvart. It's great to know you're always there to help. It's a bit too tight for today's demo, but will try to get that list in place

**Pull request merged**
