### PR TITLE
Syndesis camel upgrade

### PR DESCRIPTION
**Pull request by phantomjinx**
Upgrades camel dependencies to 2.21.0.fuse-740028

* Incorporates removal of google-sheets camel component from syndesis as now provided within camel.

### CODE REVIEW

**Comment by phantomjinx** [comment]
Have set this to WIP for the moment. Although everything compiles I get an error in  io.syndesis.systests/DeploymentTests. This error can be replicated in my IDE & not sure how to go about fixing it.

```
Initializing Session:b0fc9775
Using Kubernetes at: https://vision.birds-of-prey.phantomjinx.org.uk:8443/
Creating project: itest-b0fc9775
To switch to the new project: oc project itest-b0fc9775
Storing pods console logs into dir /home/phantomjinx/programming/java/syndesis/app/test/target/surefire-reports
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.219 s <<< FAILURE! - in io.syndesis.systests.DeploymentTest
[ERROR] io.syndesis.systests.DeploymentTest  Time elapsed: 2.219 s  <<< ERROR!
java.lang.AbstractMethodError
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)

[INFO] Running io.syndesis.systests.SyndesisRestTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in io.syndesis.systests.SyndesisRestTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » AbstractMethod
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.747 s
[INFO] Finished at: 2019-06-11T12:56:33+01:00
[INFO] Final Memory: 37M/122M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project test: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/phantomjinx/programming/java/syndesis/app/test/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
ERROR: Last command exited with 1
```

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
CubeKubernetesConfiguration: 
  namespace = itest-0cf8b186
  master.url = https://vision.birds-of-prey.phantomjinx.org.uk:8443/
  env.script.env = {}
  env.setup.script.url = file:/home/phantomjinx/programming/java/syndesis/app/test/target/test-classes/setup.sh
  env.teardown.script.url = file:/home/phantomjinx/programming/java/syndesis/app/test/target/test-classes/teardown.sh
  env.dependencies = []
  namespace.lazy.enabled = true
  namespace.cleanup.enabled = true
  namespace.cleanup.timeout = 0
  namespace.cleanup.confirm.enabled = false
  namespace.destroy.enabled = false
  namespace.destroy.confirm.enabled = false
  namespace.destroy.timeout = 0
  wait.enabled = true
  wait.timeout = 600000
  wait.poll.interval = 5000
  ansi.logger.enabled = true
  env.init.enabled = true
  logs.copy = true
  wait.for.service.list = [syndesis-server, syndesis-ui]
  cube.api.version = v1
  cube.trust.certs = true

CubeOpenShiftConfiguration: 
  keepAliveGitServer = false
  autoStartContainers = []
  proxiedContainerPorts = []
  portForwardBindAddress = 127.0.0.1
  openshiftRouterHttpPort = 80
  openshiftRouterHttpsPort = 443
  enableImageStreamDetection = true
  routerSniPort = 443
  templateProcess = true
  stratupTimeout = 600
  httpClientTimeout = 120

[32mInitializing Session:0cf8b186[m
[32mUsing Kubernetes at: https://vision.birds-of-prey.phantomjinx.org.uk:8443/[m
[32mCreating project: itest-0cf8b186[m
To switch to the new project: oc project itest-0cf8b186
Storing pods console logs into dir /home/phantomjinx/programming/java/syndesis/app/test/target/surefire-reports
java.lang.AbstractMethodError
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1052)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:830)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:332)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:361)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:217)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.resolveDependencies(MavenRepositorySystem.java:121)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:228)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.using(MavenStrategyStageBaseImpl.java:71)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withoutTransitivity(MavenStrategyStageBaseImpl.java:58)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withoutTransitivity(MavenStrategyStageBaseImpl.java:40)
	at org.arquillian.cube.kubernetes.impl.resolve.ShrinkwrapResolver.resolve(ShrinkwrapResolver.java:46)
	at org.arquillian.cube.kubernetes.impl.SessionManager.createEnvironment(SessionManager.java:134)
	at org.arquillian.cube.kubernetes.impl.SessionManager.start(SessionManager.java:216)
	at org.arquillian.cube.kubernetes.impl.SessionManagerLifecycle.start(SessionManagerLifecycle.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
	at org.arquillian.cube.kubernetes.impl.SuiteListener.start(SuiteListener.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeSuite(EventTestRunnerAdaptor.java:70)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:103)
	at org.arquillian.cube.requirement.ArquillianConditionalRunner.run(ArquillianConditionalRunner.java:28)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by christophd** [comment]
@phantomjinx I think these are the system tests that start with a fresh Openshift namespace and try to install Syndesis. I am not sure if these tests are maintained by someone

@zregvart do you know more details about those tests?

**Comment by phantomjinx** [comment]
@oscerd @christophd 

Just ran a build pre-this-PR & get the same test failure so happy the upgrade is not responsible. Going to remove the WIP label & merge.

**Comment by oscerd** [comment]
how is it possible you merged this with a test failing?

**Comment by christophd** [comment]
I think these tests are not part of the CI/CD pipeline

**Comment by zregvart** [comment]
Yeah we failed to maintain the system tests, the [CI job succeeded](https://circleci.com/workflow-run/82780f32-d43c-4534-9562-13a1e63492ec).

**Pull request merged**
