### PR TITLE
feature(e2e-job): Don't execute on docs or ui changes

### PR DESCRIPTION
**Pull request by Delawen**
In theory the integration tests should be skipped (and seen as success) on this PR.

But on other PR it should run.

### CODE REVIEW

**Comment by Delawen** [comment]
And now it should skip full-pr build too and no QE test?

**Comment by Delawen** [comment]
No, QE is pending.... eternally now I guess.

**Comment by Delawen** [comment]
retest this please

**Comment by Delawen** [comment]
@MelissaFlinn is gonna love this one!

**Comment by MelissaFlinn** [comment]
Yes, I do! Thank you :)

**Comment by avano** [comment]
retest this please

**Review by zregvart — APPROVED** [review]
Perfect!

**Pull request merged**
