### PR TITLE
Odata connector

### PR DESCRIPTION
**Pull request by phantomjinx**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
LGTM

@dhirajsb can we remove `old-odata`
@phantomjinx has the component been contributed also upstream ?

**Comment by phantomjinx** [comment]
@lburgazzoli 

I did want to keep old-data around until the conclusion of the parent epic. I can take a copy and keep it locally if you prefer but was just easier this way.

The upstream component is available upstream but some bug fixes have not yet gone into our forked versions hence the need to keep the source in the syndesis connector. I will monitor the bugs as they get fixed (the guy doing it has been pretty quick) and as soon we get turnaround, I can clean up the forked source.

**Comment by lburgazzoli** [comment]
> @lburgazzoli
> 
> I did want to keep old-data around until the conclusion of the parent epic. I can take a copy and keep it locally if you prefer but was just easier this way.

I have no issue to keep it for a while but git is here to keep track of the history :)

> The upstream component is available upstream but some bug fixes have not yet gone into our forked versions hence the need to keep the source in the syndesis connector. I will monitor the bugs as they get fixed (the guy doing it has been pretty quick) and as soon we get turnaround, I can clean up the forked source.

ok

**Comment by oscerd** [comment]
> @lburgazzoli
> 
> I did want to keep old-data around until the conclusion of the parent epic. I can take a copy and keep it locally if you prefer but was just easier this way.
> 
> The upstream component is available upstream but some bug fixes have not yet gone into our forked versions hence the need to keep the source in the syndesis connector. I will monitor the bugs as they get fixed (the guy doing it has been pretty quick) and as soon we get turnaround, I can clean up the forked source.

I'm backporting the required fix in Fuse Camel then we can spin a new build and pin the resulting camel.

**Comment by phantomjinx** [comment]
@oscerd

These others would be good, please:
* [CAMEL-13012](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13012): NPE when response callback invoked
* [CAMEL-13008](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13008): connector assumes '/' at end of uri
* [CAMEL-13006](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13006): missing properties on olingo4 consumer
* [CAMEL-13005](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13005): serviceUri not being set correctly

**Comment by oscerd** [comment]
> @oscerd
> 
> These others would be good, please:
> 
> * [CAMEL-13012](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13012): NPE when response callback invoked
> * [CAMEL-13008](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13008): connector assumes '/' at end of uri
> * [CAMEL-13006](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13006): missing properties on olingo4 consumer
> * [CAMEL-13005](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13005): serviceUri not being set correctly

Ok, Will backport this stuff too.

**Comment by phantomjinx** [comment]
@oscerd thx. I'll create a new issue to remove the forked source etc...

@lburgazzoli 
Finally, jumped through all the source checks and passed circleci. Are you good with signing off the review to get it merged, please?

**Comment by lburgazzoli** [comment]
> @lburgazzoli
> Finally, jumped through all the source checks and passed circleci. Are you good with signing off the review to get it merged, please?

Approved

**Comment by oscerd** [comment]
> > @oscerd
> > These others would be good, please:
> > 
> > * [CAMEL-13012](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13012): NPE when response callback invoked
> > * [CAMEL-13008](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13008): connector assumes '/' at end of uri
> > * [CAMEL-13006](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13006): missing properties on olingo4 consumer
> > * [CAMEL-13005](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-13005): serviceUri not being set correctly
> 
> Ok, Will backport this stuff too.

Backported. We need to pin the next Fuse Camel build

**Comment by oscerd** [comment]
I'm merging this on #4305 

You'll find the camel components olingo2/olingo4 updated with the fix from upstream, so you can safely remove the component from syndesis

**Pull request merged**
