### PR TITLE
chore: Update to AtlasMap 2.2.0 Milestone 1

### PR DESCRIPTION
**Pull request by igarashitm**
Contains atlasmap/atlasmap#2655 required for syndesisio/syndesis#9228 https://issues.redhat.com/projects/ENTESB/issues/ENTESB-14339

### CODE REVIEW

**Comment by igarashitm** [comment]
retest this please

**Comment by christophd** [comment]
retest this please

**Comment by igarashitm** [comment]
"No test results found" sounds strange 
`QE Jenkins PR build 1.12.x — Build finished. No test results found.`

**Comment by mkralik3** [comment]
the ENG PR jobs were aborted due to timeout after one hour of waiting on images in quay. 
It looks that this job is failing https://ci.fabric8.io/job/syndesis-github-to-quay/ 

Also, we are still facing infrastructure problems due to ongoing Open Stack outage with our OCP clusters.
I will rerun it when it will be back to working.

**Comment by Delawen** [comment]
@mkralik3 is it online already?

**Comment by mkralik3** [comment]
@Delawen unfortunately no. All our clusters are still down and there is another issue with installation ( https://one.redhat.com/legacy/outages/list/details/607412a7c8d4e97ae77784b1 )

**Comment by mkralik3** [comment]
@Delawen @tadayosi 
Sorry, we still are facing with infra problems. Also, the PR job is rewriting in order to not use https://ci.fabric8.io/job/syndesis-github-to-quay/ .
Meanwhile, I downloaded the images which was created by GitHub action, pushed them to the tmp project on Quay and run the Syndesis from them. One Smoke UI test failed because there are shown field types in DM by default. @tadayosi  Is it a bug or an intention to have shown the type of field after open DM?

**Comment by igarashitm** [comment]
Yes now Field type is shown by default - https://github.com/atlasmap/atlasmap/issues/2636

**Comment by mkralik3** [comment]
Thx, fixed in Syndesis test suite. 
However, the multiple mapping test failed.
output

**Comment by igarashitm** [comment]
OK there seems to be a regression on collection source fields added to the many-to-one mapping, we'll re-submit a PR after it's fixed - https://github.com/atlasmap/atlasmap/issues/2665

**Pull request closed without merging**
