### PR TITLE
fix: Hide steps that can't be used at the end of a flow (backport)

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes [ENTESB-11976](https://issues.redhat.com/browse/ENTESB-11976)

### CODE REVIEW

**Comment by zregvart** [comment]
@gashcrumb seems related to your change, the end to end tests fail with:

```
Unable to locate element: {"method":"css selector","selector":"*[data-testid="connection-card-split-card"]"}
```

embedded0

Is this expected, should the tests be changed?

**Comment by gashcrumb** [comment]
Nope, that's not expected.  Lemme investigate further.

**Comment by gashcrumb** [comment]
Yeah, that's not the right fix, I've opened a PR to revert it on master, lemme close this PR too, will re-open when I've a better fix for this one.

**Comment by zregvart** [comment]
Hats of to @syndesisio/qe for catching another issue before we release the version :cowboy_hat_face:

**Comment by gashcrumb** [comment]
I'm always happy to provide positive validation that we should have e2e tests :-)

**Pull request closed without merging**
