### PR TITLE
feat: configure Maven mirror for S2I build

### PR DESCRIPTION
**Pull request by zregvart**
chore: use Mustache templating for settings.xml (4adbc8c)

This allows the use of Mustache templating language for `settings.xml`, enabling customization of that file.

feat: maven mirror configuration (b181cf1)

This allows specifying configuration property `maven.mirror` that influences the integration S2I build's `settings.xml` file to include a mirror configuration. This way a build can be performed accessing only the mirror repository.

feat: allow configuring Maven mirror via CR (79c5d06)

Adds `mirror` under `maven` in the server component feature configuration of the Syndesis custom resource.

Ref. https://issues.redhat.com/browse/ENTESB-17310

### CODE REVIEW

**Comment by zregvart** [comment]
retest this please

**Comment by claudio4j** [comment]
I added `oc patch syndesis/app --type=merge  -p '{"spec":{"components":{"server":{"features":{"maven": {"mirror":"http://uk.maven.org/maven2"}}}}}}'`

Which changed
```
oc get cm/syndesis-server-config -oyaml |grep -A 5 maven 
    maven:
      repositories:
        central: https://repo.maven.apache.org/maven2/
        repo-02-redhat-ga: https://maven.repository.redhat.com/ga/
        repo-03-jboss-ea: https://repository.jboss.org/nexus/content/groups/ea/
      mirror: http://uk.maven.org/maven2
```

But in the integration build pod, there is no `<mirrors>` in `/tmp/upload/src/configuration/settings.xml`
Is there other action to perform to have the mirror in settings.xml ?

**Comment by zregvart** [comment]
> But in the integration build pod, there is no `<mirrors>` in `/tmp/upload/src/configuration/settings.xml`
> Is there other action to perform to have the mirror in settings.xml ?

There should not be any other changes necessary, this is how I tested as well. Are you running the syndesis-server from this PR?

**Comment by claudio4j** [comment]
I had built with `syndesis build -m integration,server,s2i -i -f`and the server-log says 1.13-SNAPSHOT
When I apply the patch the syndesis-server log says
```
2021-10-05 20:29:07.541  INFO 1 --- [default.svc/...] .r.EventBasedConfigurationChangeDetector : Detected change in config maps
2021-10-05 20:29:07.541  INFO 1 --- [default.svc/...] .r.EventBasedConfigurationChangeDetector : Reloading using strategy: REFRESH
2021-10-05 20:29:09.204  INFO 1 --- [default.svc/...] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-configmap.syndesis-server-config.syndesis'}]
2021-10-05 20:29:09.251  INFO 1 --- [default.svc/...] o.s.boot.SpringApplication               : The following profiles are active: kubernetes
2021-10-05 20:29:09.380  INFO 1 --- [default.svc/...] o.s.boot.SpringApplication               : Started application in 1.833 seconds (JVM running for 1656.103)
```
It was able to pickup the `configmap/syndesis-server-config` change.

**Comment by zregvart** [comment]
The Maven in the S2I build is invoked with: `-s /tmp/src/configuration/settings.xml`, not sure where `/tmp/upload/src/configuration/settings.xml` comes into play.

**Comment by zregvart** [comment]
retest this please

**Review by claudio4j — APPROVED** [review]

**Comment by zregvart** [comment]
seems that there were two builds running at about the same time, so results of one (in local Maven repository) could have interfered with the other.

retest this please

**Comment by zregvart** [comment]
retest this please

**Pull request merged**
