### PR TITLE
doc-update-csv-support

### PR DESCRIPTION
**Pull request by MelissaFlinn**
Ready for review

### CODE REVIEW

**Review by zregvart — APPROVED** [review]
LGTM, should we mention the options users can set when defining the data shape?

We don't have much documentation on that, this was taken verbatim from AtlasMap:
https://github.com/syndesisio/syndesis/blob/3f0a3f52f2c2b856fbdb546912f2aa2aae9600da/app/ui-react/packages/ui/src/Integration/Editor/endpoint/DescribeDataShapeForm.tsx#L43-L125

**Comment by MelissaFlinn** [comment]
@zregvart 
yes - I agree that I should add that information - thank you.

Is my example for the specification property correct?
"inputDataShape": {
  "description": "Person data",
  "kind": "csv-instance",
  "name": "Person",
  "specification":  "{\"firstName\",\"John\",...}"
}

**Comment by MelissaFlinn** [comment]
I added the list of parameters (label and name)
Have asked Rafal for descriptions

**Comment by MelissaFlinn** [comment]
merging this PR now.
I'll create a new PR for any additional updates.

**Pull request merged**
