### PR TITLE
[ENTESB-18911] UnsatisfiedDependencyException in integration with MongoDB connector

### PR DESCRIPTION
**Pull request by rnetuka**
Issue: https://issues.redhat.com/browse/ENTESB-18911

Spring Boot 2.5.12 uses MongoDB 4.2.3
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.5.12/spring-boot-dependencies-2.5.12.pom

This needs to be synchronized.

### CODE REVIEW

**Comment by claudio4j** [comment]
Shouldn't this mongodb driver go to app/connector/mongodb connector and integration/bom/pom.xml ?

**Comment by rnetuka** [comment]
@claudio4j integration/bom/pom.xml updated. Shall app/extension/bom/pom.xml keep the update or discard it?

**Comment by claudio4j** [comment]
Both pom.xml should be updated. Looks like the CI tests are ok. Were you able to run an integration to confirm it's working ?
Thanks for fixing it.

**Comment by claudio4j** [comment]
There is https://github.com/syndesisio/syndesis/blob/1.14.x/app/pom.xml#L150 to change too.

**Comment by claudio4j** [comment]
I was looking at [mvn repo](https://mvnrepository.com/artifact/org.mongodb/mongo-java-driver) and there is no 4.x version.
Also, looking at [camel-mongodb component](https://github.com/jboss-fuse/camel/blob/2.23.x.redhat-7-x/parent/pom.xml#L521) it uses 3.12.7, I think we can continue to use this version.
camel spring boot is one of the runtimes to run camel routes, I think we are safe to use this version, but in syndesis there should be an exclusion of mongodb lib from spring boot dependency.
Were you able to run integrations to test it ?

**Comment by rnetuka** [comment]
MongoDB drivers 4.x are published as different artifacts. https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-legacy/4.2.3

Unfortunately, I wasn't able to test it since my OS refuses to run VirtualBox / Minishift.

I've updated the files with additional changes. It's still only a proposal.

**Comment by syndesisqe** [comment]
Can one of the admins verify this patch?

**Comment by rnetuka** [comment]
Upgrading to MongoDB 4.2.3 is not an option because Camel still uses 3.12.7

Replaced by PR https://github.com/syndesisio/syndesis/pull/9943

**Comment by rnetuka** [comment]
Upgrading to MongoDB 4.2.3 is not an option because Camel still uses 3.12.7

Replaced by PR https://github.com/syndesisio/syndesis/pull/9943

**Pull request closed without merging**
