### PR TITLE
[closes #2956] Increase timeout for integration state check

### LINKED ISSUE #2956: [Integration Deployment] Sometimes the integration deployment is being recreated indefinitely
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Current integration deployment behavior is that a "deployment 1" is created, but it is terminated and "deployment 2" is started and then the integration is deployed.

In rare cases (which I can't reliably reproduce), the "deployment 2" is terminated for unknown reasons and the whole "deployment" process is started again. So "deployment 3" is started and terminated and "deployment 4" is started and should deploy the integration. And this over and over again and the integration is never deployed successfully.

I saw this problem both on minishift and deployed openshift instance.

According to server log, it is doing the reprovision:

```

2018-07-03 12:06:16.441  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz:1 : Desired status "Published" != current status "Unpublished" --> calling status change handler
--
  | 2018-07-03 12:06:16.442  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Start processing integration: i-LGV1IwetePgfhzupC2oz, version: 1 with handler:PublishHandler
  | 2018-07-03 12:06:17.051  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: true
  | 2018-07-03 12:06:17.052  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Steps performed so far: {}
  | 2018-07-03 12:06:17.348  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Created project files and starting build
  | 2018-07-03 12:06:21.603  INFO [-,,,] 1 --- [ool-12-thread-1] i.s.i.p.generator.ProjectGenerator       : Integration [sf-kafka]: Project files written to output stream
  | 2018-07-03 12:07:12.399  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:08:12.427  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:09:12.398  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:09:13.875  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Starting deployment
  | 2018-07-03 12:09:16.799  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Deployment done
  | 2018-07-03 12:09:16.822  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:09:16.822  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: [PENDING] [{buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1, deploy=1}]
  | 2018-07-03 12:09:16.823  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Setting status to Pending
  | 2018-07-03 12:10:12.399  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:10:16.926  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz:1 : Desired status "Published" != current status "Unpublished" --> calling status change handler
  | 2018-07-03 12:10:16.926  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Start processing integration: i-LGV1IwetePgfhzupC2oz, version: 1 with handler:PublishHandler
  | 2018-07-03 12:10:16.964  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:10:16.964  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Steps performed so far: {buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1}
  | 2018-07-03 12:10:17.054  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Skipped step buildv1 because already performed
  | 2018-07-03 12:10:17.057  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Starting deployment
  | 2018-07-03 12:10:19.797  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Deployment done
  | 2018-07-03 12:10:19.810  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:10:19.810  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: [PENDING] [{buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1, deploy=3}]
  | 2018-07-03 12:10:19.810  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Setting status to Pending
  | 2018-07-03 12:11:12.405  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:11:19.950  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz:1 : Desired status "Published" != current status "Unpublished" --> calling status change handler
  | 2018-07-03 12:11:19.951  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Start processing integration: i-LGV1IwetePgfhzupC2oz, version: 1 with handler:PublishHandler
  | 2018-07-03 12:11:19.997  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:11:19.997  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Steps performed so far: {buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1}
  | 2018-07-03 12:11:20.093  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Skipped step buildv1 because already performed
  | 2018-07-03 12:11:20.099  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Starting deployment
  | 2018-07-03 12:11:22.656  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Deployment done
  | 2018-07-03 12:11:22.684  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:11:22.684  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: [PENDING] [{buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1, deploy=4}]
  | 2018-07-03 12:11:22.684  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Setting status to Pending
  | 2018-07-03 12:12:12.398  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:12:22.749  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz:1 : Desired status "Published" != current status "Unpublished" --> calling status change handler
  | 2018-07-03 12:12:22.749  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Start processing integration: i-LGV1IwetePgfhzupC2oz, version: 1 with handler:PublishHandler
  | 2018-07-03 12:12:22.781  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:12:22.781  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Steps performed so far: {buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1}
  | 2018-07-03 12:12:22.865  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Skipped step buildv1 because already performed
  | 2018-07-03 12:12:22.870  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Starting deployment
  | 2018-07-03 12:12:25.680  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Deployment done
  | 2018-07-03 12:12:25.698  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:12:25.699  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: [PENDING] [{buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1, deploy=6}]
  | 2018-07-03 12:12:25.701  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Setting status to Pending
  | 2018-07-03 12:13:12.399  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:13:25.836  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz:1 : Desired status "Published" != current status "Unpublished" --> calling status change handler
  | 2018-07-03 12:13:25.837  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Start processing integration: i-LGV1IwetePgfhzupC2oz, version: 1 with handler:PublishHandler
  | 2018-07-03 12:13:25.884  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:13:25.884  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Steps performed so far: {buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1}
  | 2018-07-03 12:13:25.957  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Skipped step buildv1 because already performed
  | 2018-07-03 12:13:25.960  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Starting deployment
  | 2018-07-03 12:13:28.539  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Deployment done
  | 2018-07-03 12:13:28.551  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:13:28.551  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: [PENDING] [{buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1, deploy=8}]
  | 2018-07-03 12:13:28.551  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Setting status to Pending
  | 2018-07-03 12:14:12.398  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:14:28.636  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz:1 : Desired status "Published" != current status "Unpublished" --> calling status change handler
  | 2018-07-03 12:14:28.636  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Start processing integration: i-LGV1IwetePgfhzupC2oz, version: 1 with handler:PublishHandler
  | 2018-07-03 12:14:28.662  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:14:28.662  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Steps performed so far: {buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1}
  | 2018-07-03 12:14:28.715  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Skipped step buildv1 because already performed
  | 2018-07-03 12:14:28.718  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Starting deployment
  | 2018-07-03 12:14:30.809  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Deployment done
  | 2018-07-03 12:14:30.835  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:14:30.835  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: [PENDING] [{buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1, deploy=9}]
  | 2018-07-03 12:14:30.835  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Setting status to Pending
  | 2018-07-03 12:15:12.399  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:15:31.066  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz:1 : Desired status "Published" != current status "Unpublished" --> calling status change handler
  | 2018-07-03 12:15:31.070  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Start processing integration: i-LGV1IwetePgfhzupC2oz, version: 1 with handler:PublishHandler
  | 2018-07-03 12:15:31.103  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:15:31.104  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Steps performed so far: {buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1}
  | 2018-07-03 12:15:31.193  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Skipped step buildv1 because already performed
  | 2018-07-03 12:15:31.198  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Starting deployment
  | 2018-07-03 12:15:33.326  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Deployment done
  | 2018-07-03 12:15:33.358  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:15:33.358  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: [PENDING] [{buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1, deploy=10}]
  | 2018-07-03 12:15:33.359  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Setting status to Pending
  | 2018-07-03 12:16:12.402  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
  | 2018-07-03 12:16:29.965  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.l.j.c.ActivityTrackingController   : Purging old controller
  | 2018-07-03 12:16:33.444  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz:1 : Desired status "Published" != current status "Unpublished" --> calling status change handler
  | 2018-07-03 12:16:33.445  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Start processing integration: i-LGV1IwetePgfhzupC2oz, version: 1 with handler:PublishHandler
  | 2018-07-03 12:16:33.467  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:16:33.468  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Steps performed so far: {buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1}
  | 2018-07-03 12:16:33.533  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Skipped step buildv1 because already performed
  | 2018-07-03 12:16:33.537  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Starting deployment
  | 2018-07-03 12:16:35.821  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Deployment done
  | 2018-07-03 12:16:35.839  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: Build started: false, isRunning: false, Deployment ready: false
  | 2018-07-03 12:16:35.839  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [sf-kafka]: [PENDING] [{buildv1=172.30.1.1:5000/myproject/i-sf-kafka:1, deploy=12}]
  | 2018-07-03 12:16:35.839  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LGV1IwetePgfhzupC2oz : Setting status to Pending
  | 2018-07-03 12:17:12.399  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.

... and so on :-)
```

## Expected behavior

Successful deployment of the integration

## Screenshot

s5mu

22 deployments in 17 minutes and still counting...

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by avano**
see #2956 for context

### CODE REVIEW

**Comment by heiko-braun** [comment]
I think this is not the best approach to just increase the timeout, but probably works for now. @rhuss, @chirino  Any thoughts on this? The underlying issue ( #2956) has a significant impact and should be addressed in 7.1, and I am not sure we have room for a more elaborate fix.

**Comment by rhuss** [comment]
I agree that its probably not the best solution, but its better than before IMO. 

With regard to the tight timeline I would opt for merging, but still tracking the issue to find a more elaborate fix.

**Comment by avano** [comment]
@heiko-braun @rhuss the drawback of this is when you for example start/stop integration from the UI, the status will stay in "starting"/"stopping" for the configured integration check timeout (so in this case for 2 minutes, even if the integration is started/stopped in let's say 30 seconds).

The second (temporary) solution, that came to my mind (and will not break anything) is to make this timeout configurable from outside, so from deployment env variable or config map. Then we can leave the default value set to 60 seconds and we can increase it in our tests easily. 

And we can document that it is possible to increase it in case of some problems?

WDYT? In regards to 7.1 schedule

**Comment by rhuss** [comment]
@avano I think that makes sense. Let's do this (make it configurable) for now but revisit the whole issue for 7.2

**Comment by heiko-braun** [comment]
@avano Do you update the PR?

**Comment by avano** [comment]
@heiko-braun right now I did :-)

@rhuss can you please review? I followed the same approach as for the max integrations. There needs to be something updated in the operator as well probably, but I'm not familiar with that

**Comment by heiko-braun** [comment]
I've created a follow up issue #3309

**Comment by avano** [comment]
@rhuss sure, no problem :-) I have an idea what is needed to be done, but I was not brave enough to mess with GO :-)

**Pull request merged**
