### PR TITLE
[ENTESB-18911] UnsatisfiedDependencyException in integration with MongoDB connector

### PR DESCRIPTION
**Pull request by rnetuka**
Issue: https://issues.redhat.com/browse/ENTESB-18911

Caused by autoconfiguration of MongoDB metrics - tries to use a class from MongoDB 4

### CODE REVIEW

**Comment by syndesisqe** [comment]
Can one of the admins verify this patch?

**Comment by claudio4j** [comment]
Can you have a look at the failing test ?
```
Error:  io.syndesis.integration.project.generator.ProjectGeneratorTest.testGenerateProject(TestInfo,Path)  Time elapsed: 0.352 s  <<< FAILURE
```

**Comment by claudio4j** [comment]
Can you have a look at the failing test ?
```
Error:  io.syndesis.integration.project.generator.ProjectGeneratorTest.testGenerateProject(TestInfo,Path)  Time elapsed: 0.352 s  <<< FAILURE
```

**Comment by rnetuka** [comment]
@claudio4j I've updated the test resources. Let see if it goes well this time.

**Review by claudio4j — APPROVED** [review]

**Comment by claudio4j** [comment]
Thanks Radovan

**Pull request merged**
