### PR TITLE
Fix #6185 - adding a local repo in custom settings

### LINKED ISSUE #6185: [Retrospective] Improve S2I with local repository
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
During development of #6100 there were interesting ideas how to make S2I image dependencies self contained, ie https://github.com/syndesisio/syndesis/pull/6169#issuecomment-512110694

Provide some solution in order to rely completely on local maven dependencies instead of copying "manually" dependencies.

Acceptance Criteria: all maven dependencies are retrieved locally and any cached intermediate Docker layer is kept.

### PR DESCRIPTION
**Pull request by squakez**
#6185 - The S2I is now taking everything from local repository, falling back to remote if by any chance the dependency is not found locally. With this change the Docker image will be filled up with all the dependency needed (also any `snapshot` that may be provided in the local environment).

Caching introduced by #6169 is no longer needed as it will be always present in the local maven repo, so, the build time is always reduced to the minimum (1:30 minutes in my case, vs 5 minutes when no cache was there).

Also, reduced the weight of the S2I image, from 2 GB to 1GB:
```
172.30.1.1:5000/syndesis/syndesis-s2i           latest              7a0a59fbb04a        38 minutes ago      1.08GB
...
172.30.1.1:5000/syndesis/syndesis-s2i           <none>              19eca7f8dbf3        2 weeks ago         2.01GB
```
Partially tested with `camel-snapshot` libraries, the docker image m2 repo is filled up with any snapshot, but I did not manage to find a snapshot version that works with the actual syndesis (mainly due to connector bound to `camel-fuse` upgrades).

Notice that I tried to use different settings profile, but did not manage to provide the proper order with multiple profiles, so I left a unique profile with `_local` as the first choice repo.

WIP left until next monday, don't want to leave any stale issue over the weekend ;)

### CODE REVIEW

**Comment by lburgazzoli** [comment]
wondering if we could avoid changing the project generator

**Comment by squakez** [comment]
> wondering if we could avoid changing the project generator

I guess you mean the `settings.xml`. I think I tried several experiments and I ended up copying the same settings from s2i to have it working. I'll revert locally to confirm if that is working without any change there. What would be your concern if we had to leave this config?

**Comment by lburgazzoli** [comment]
I mean the changes to the mustache files are then gogin to be part of the integration project generator so it would be nice to check if there is any alternative way. i.e. I do not know if listing the local repo (/tmp/artifacts/m2) also among the additional repositories can cause any troubles

**Comment by squakez** [comment]
I just removed a plugin from the `pom.xml.mustache` that was introduced in a previous PR #6169. This is no longer needed as the `copy-dependency` is redundant.

About the `settings.xml` removing the local repo is bringing to the following error when creating an integration:
```
Using 172.30.1.1:5000/syndesis/syndesis-s2i@sha256:a5db062c847172ad0e8daa56813686b033656efbc70121b868fb0b6368481eb6 as the s2i builder image
Preparing to build temp.builder.openshift.io/syndesis/i-asffsda-1:77bc8e71
Copying sources from "/tmp/build/inputs" to "/tmp/upload/src"
Clean build will be performed
Running "assemble" in "temp.builder.openshift.io/syndesis/i-asffsda-1:77bc8e71"
==================================================================
Starting S2I Java Build .....
S2I source build for Maven detected
Using custom maven settings from /tmp/src/configuration/settings.xml
Using MAVEN_OPTS '-XX:+UseG1GC -XX:+UseStringDeduplication -Xmx310m'
Found pom.xml ...
Running 'mvn -Dmaven.repo.local=/tmp/artifacts/m2 -s /tmp/src/configuration/settings.xml package -DskipTests -Dmaven.javadoc.skip=true -Dmaven.site.skip=true -Dmaven.source.skip=true -Djacoco.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dpmd.skip=true -Dfabric8.skip=true -e -B --strict-checksums'
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
Maven home: /opt/maven
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-957.5.1.el7.x86_64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/1.5.16.RELEASE/spring-boot-dependencies-1.5.16.RELEASE.pom 
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/1.5.16.RELEASE/spring-boot-dependencies-1.5.16.RELEASE.pom  (0 B at 0 B/s)
[...]
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/18/apache-18.pom  (0 B at 0 B/s)
[INFO] Downloading from 01_maven_central: https://repo1.maven.org/maven2/io/syndesis/integration/integration-bom/1.8-SNAPSHOT/maven-metadata.xml 
[INFO] Downloading from 01_maven_central: https://repo1.maven.org/maven2/io/syndesis/integration/integration-bom/1.8-SNAPSHOT/integration-bom-1.8-SNAPSHOT.pom 
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact io.syndesis.integration:integration-bom:pom:1.8-SNAPSHOT in 01_maven_central (https://repo1.maven.org/maven2 ) @ line 61, column 19
[ERROR] 'dependencies.dependency.version' for io.atlasmap:camel-atlasmap:jar is missing. @ line 73, column 17
[ERROR] 'dependencies.dependency.version' for io.syndesis.connector:connector-timer:jar is missing. @ line 79, column 17
[ERROR] 'dependencies.dependency.version' for io.syndesis.integration:integration-runtime:jar is missing. @ line 113, column 17
[ERROR] 'dependencies.dependency.version' for io.syndesis.integration:integration-runtime-springboot:jar is missing. @ line 118, column 17
@
[...]
```
For some reason mvn is forcing the lookup on the repo, altough all those dependencies are already available in the local repo.

**Comment by squakez** [comment]
Okey, I've performed some more experiment and I managed to have a clean maven repo by cleaning some maven metadata. Actually it's a feature requested in Maven itself: [MNG-5185](https://issues.apache.org/jira/browse/MNG-5185).

@lburgazzoli could you double check now?

**Pull request merged**
