### PR TITLE
fix: reduce integration definition size #4309

### PR DESCRIPTION
**Pull request by KurtStam**
I'm simply pruning all actions from the integration that is about to be generated to address #4309.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
wondering if we really need to keep the action inside the connector as such info is available on the step too

**Comment by zregvart** [comment]
Seems that we need to pin another early access Camel release.

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.apache.camel:camel-spring-boot-dependencies:pom:2.21.0.fuse-730033 in jboss-fuse (https://origin-repository.jboss.org/nexus/content/groups/ea) @ line 970, column 19
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.syndesis:syndesis-parent:1.6-SNAPSHOT (/workspace/app/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not find artifact org.apache.camel:camel-spring-boot-dependencies:pom:2.21.0.fuse-730033 in jboss-fuse (https://origin-repository.jboss.org/nexus/content/groups/ea) @ line 970, column 19 -> [Help 2]
```

I think @oscerd can do this for us.

**Comment by oscerd** [comment]
I already pinned the 042

**Comment by KurtStam** [comment]
> wondering if we really need to keep the action inside the connector as such info is available on the step too

@lburgazzoli good catch, we can in fact remove all actions.

**Comment by KurtStam** [comment]
@zregvart, I think now that _all_ actions are removed we reducing the footprint significantly!

**Pull request merged**
