### PR TITLE
fix: fix integration tests on 1.11.x

### PR DESCRIPTION
**Pull request by zregvart**
Use maven.repo.local property instead of settings.localRepository to set the local Maven repository for integration runtime container.

(cherry picked from commit 66067878c12fd5fa178cef98585280fc99af51f5)

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by christophd** [comment]
thanks! 👍

**Comment by zregvart** [comment]
This needed a rebase to include #9195, hopefully the integration tests will pass now.

**Comment by Delawen** [comment]
Maybe it is not enough and we need the previous patch?

To me it is still not clear when/why this maven change happened. Maybe in JDK 8 (as opposed to JDK 11 in master) this still is not enough?

**Comment by zregvart** [comment]
No idea, locally in my IDE (Eclipse) tests pass on this branch, they fail from command line. Logs:

```
13:26:32.291 [ream-1133381918] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: Starting the Java application using /opt/run-java/run-java.sh ...
13:26:32.291 [ream-1133381918] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=9779:/opt/prometheus/prometheus-config.yml -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/integration-runtime.jar
13:26:32.291 [ream-1133381918] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDERR: Error: Invalid or corrupt jarfile /deployments/integration-runtime.jar
```

And indeed `/deployments/integration-runtime.jar` is 0 bytes. I've looked in the S2I build and there `/deployments/project-0.1-SNAPSHOT.jar` looks good. I think we might be missing another commit from master here. Looking into it.

**Comment by zregvart** [comment]
So the integration container image is trying to copy `.../app/test/integration-test/target/integrations/i-timer-to-log-*/target/project-0.1-SNAPSHOT.jar` to `/deployments/integration-runtime.jar`, but the `.../app/test/integration-test/target/integrations/i-timer-to-log-*/target/` directory doesn't exist.

**Comment by zregvart** [comment]
Yeah, I think we need to include #8403 and #8451 as well.

**Comment by zregvart** [comment]
We also need #7673

**Comment by zregvart** [comment]
And #8815

**Comment by zregvart** [comment]
And #7391

**Comment by zregvart** [comment]
I think I'll remove the S2I Dockefile change, I don't think it's needed, to keep the changes within integration tests only.

**Comment by zregvart** [comment]
Retest this please

**Pull request merged**
