### PR TITLE
ENTESB-12000: Allows tagged images from quay.io pr testing registry

### PR DESCRIPTION
**Pull request by phantomjinx**
* Loosens the checkTags function slightly to allow a x-chksum format of
  image tag as well as the original version tag.

### CODE REVIEW

**Comment by phantomjinx** [comment]
This has to be reworked entirely due to refactoring of the operator.

**Comment by heiko-braun** [comment]
@phantomjinx before you do that, can you prepare a version for 1.8, i.e in another PR? It might be that we treat 1.8.x as the baseline for 7.6 and it would be good to be prepared

**Comment by lgarciaaco** [comment]
@phantomjinx the checkTag function is not required anymore. Actually we didn't have tags at the moment I refactored so I deleted all of it.

**Comment by phantomjinx** [comment]
No longer applicable.

**Pull request closed without merging**
