### PR TITLE
fix(customizations): remove nested card, unused css in api client connector review step.

### PR DESCRIPTION
**Pull request by michael-coker**
fixes https://github.com/syndesisio/syndesis/issues/3989

### CODE REVIEW

**Comment by gashcrumb** [comment]
Rebase should get the checks working, does this need to go into 1.5.x?

**Comment by zregvart** [comment]
I've reabased hope you don't mind, I wouldn't call this critical for 1.5.x but I think it poses no risk to have it there.

**Comment by gashcrumb** [comment]
@zregvart Wonder why `meta` and `server` still seem to fail and then seemingly work?

**Comment by gashcrumb** [comment]
@zregvart ah, never mind, transient failure...

**Pull request merged**
