### PR TITLE
refactor(connector): update timer's `defaultValue`

### LINKED ISSUE #4491: Stranged default when using a Cron Timer
grafik

The text field is initialized with '+' as separators. Shouldn't this be " " ?

BTW, from an UX point of view it would be far better to allow 5 input fields with labels like "minute" "hour" .... for every column, I never can memorize the order of these columns.

### PR DESCRIPTION
**Pull request by zregvart**
This should give us a more usable value for the cron expression in the timer.

Fixes #4491

### CODE REVIEW

**Comment by zregvart** [comment]
@oscerd hmm, perhaps a Customizer then that URL encodes the property, let's see...

**Comment by oscerd** [comment]
Yeah, I was talking about this
https://github.com/apache/camel/blob/master/components/camel-quartz2/src/main/docs/quartz2-component.adoc

**Comment by oscerd** [comment]
Maybe we can manipulate the value as you said

**Comment by zregvart** [comment]
Let me do some tests/digging into this, perhaps we can make it nicer and have it working also. Strange idea if you ask me, "nice and working".

**Comment by oscerd** [comment]
image

**Comment by zregvart** [comment]
@oscerd turns out no customizer is needed (I've added a test for both variants).

The `DefaultComponent::createEndpoint` for non-raw URIs will use `URISupport::parseParameters` which does urldecoding so both cases are supported out of the box.

**Pull request merged**
