### PR TITLE
Fixes #5995, fixes #6360, fixes #6362, refactored public-api into an environment handler that stores all tag names as Environment json objects

### LINKED ISSUE #5995: Remove circular dependency between API handlers for environment management
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

There is a circular dependency between `PublicAPIHandler` and `IntegrationHandler` due to the need to handle environment tags removal when deleting an integration. Refactor this out into an `environment helper` class when creating a separate environment entity (with it's own ids and not just a property of integration) to simplify handlers and remove this circular dependency.

### LINKED ISSUE #6360: PublicAPI: Duplicate tag after import when tag already exists but integration not
See also **https://issues.jboss.org/browse/ENTESB-11387**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I import exported integration with a tag which already exists in the Syndesis, the tag is duplicated. This happens only when the integration which will be imported is not in the Syndesis.
E.g.
I create Integration1 and tag1. I add tag1 to the Integration1 and export zip file according to that tag.
`curl .../integrations/tag1/export.zip -O`
After that, I delete Integration1. The tag1 still persist in the Syndesis ( fix for https://github.com/syndesisio/syndesis/issues/5917).
I import back the exported zip file
`curl .../integrations -F data=@export.zip -F environment=second`
After that, the tag1 is duplicated.
image

However, when I do the same steps but I don't delete the integration, the tag1 is not duplicated after importing. So it looks that this issue is caused by https://github.com/syndesisio/syndesis/issues/5917 fix.

### LINKED ISSUE #6362: Manage CI/CD UI doesn't check duplicates
See also **https://issues.jboss.org/browse/ENTESB-11386**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I want to create a new tag with the same name as has the existed tag, I am able to click on Save button (however the tag is not created because the backend returns `400 "developerMsg":"Duplicate environment tag1"`).

When I want to rename a tag to the same name as has another tag, I am able to click on Save button and in the UI I see two duplicated tags.
image

In the 1.7.x, the dialog for creating/updating the tag was checking whether the name is already used. 
In the left side of the images is master, in the right side is 1.7.13 (CR3)
Creating the tag with the same name:
image
Updating to the same name:
image

The UI should check the duplicities as before.
The endpoint `PUT .../api/v1/public/environments/<tag>` should check whether the name in params is not already used by another tag.

Step to reproduce:
- Go to Manage CI/CD page
- Create tag with name _tag1_
- Try to create _tag1_ again
- Create tag with name _tag2_
- Try to rename _tag2_ to _tag1_

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by zregvart** [comment]
The failing operator build should be fixed with #6489, when that's merged please rebase on master to get a green CI check.

**Comment by dhirajsb** [comment]
@zregvart thanks, will do. It's still wip, need to verify a couple of minor changes locally.

**Comment by dhirajsb** [comment]
It's failing with the following:

'''
[ERROR] Failed to execute goal com.hubspot.maven.plugins:dependency-scope-maven-plugin:0.8:check (basepom.default) on project server-endpoint: Error resolving descriptor for artifact com.github.mikegirard:spring-social-salesforce:1.3.0: Failed to read artifact descriptor for com.github.mikegirard:spring-social-salesforce:jar:1.3.0: Could not transfer artifact com.github.mikegirard:spring-social-salesforce:pom:1.3.0 from/to redhat-ga (https://maven.repository.redhat.com/ga/): Failed to transfer file: https://maven.repository.redhat.com/ga/com/github/mikegirard/spring-social-salesforce/1.3.0/spring-social-salesforce-1.3.0.pom. Return code is: 500, ReasonPhrase: Internal Server Error. -> [Help 1]
'''

Looks like the version of 'spring-social-salesforce' in MRRC and maven central is actually `1.3.0-redhat-1` instead of `1.3.0'.

**Comment by zregvart** [comment]
We're using the version provided on [jitpack.io](https://jitpack.io/#mikegirard/spring-social-salesforce/1.3.0).

**Comment by zregvart** [comment]
The build fails with this PMD issue:

```

[INFO] PMD Failure: io.syndesis.server.endpoint.v1.handler.environment.EnvironmentHandler:167 Rule:PrematureDeclaration Priority:3 Avoid declaring a variable if it is unreferenced before a possible exit point..
```

**Pull request merged**
