### PR TITLE
add cancel modal dialog to integration-basics step in integration editor

### PR DESCRIPTION
**Pull request by michael-coker**
### Don't merge this please!

@gashcrumb just taking a stab at adding a modal by using the API client connector as a reference. Seems to work :) This is re: https://github.com/syndesisio/syndesis/issues/3060

### CODE REVIEW

**Comment by michael-coker** [comment]
@gashcrumb cool, I looked at the API Connector guard before and wasn't sure if it was something I could do, but I'll take another stab at it :) thanks!

**Comment by michael-coker** [comment]
@gashcrumb just an aside, but would a better way to trigger the modal when you click the cancel button when creating a connection to be to remove the [cancel target](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.ts#L78) from the guard?

**Comment by gashcrumb** [comment]
yeah, think so.

**Comment by gashcrumb** [comment]
Sorry just double-checking, is this good to go?  On second look I think it's fine but now I read the old conversation and I can't tell if there's remaining items :-)

**Comment by michael-coker** [comment]
@gashcrumb yo! This only introduces a cancel confirmation dialog on the "connection-basics" step. My intent was just to see if that's the correct way to implement it, and if so, I was going to introduce it on the rest of the editor steps with a cancel button. However, since we were going to introduce the route guard in the integration editor, we decided not to integrate this on each step, and to use the route guard to trigger a modal instead. And since the route guard work was shelved in lieu of auto-save, this was never implemented.

I don't think this should be merged since it only adds a confirmation dialog to one step. I suppose our options are to either 1) Pick this PR back up and implement the cancel confirmation dialog in the other editor steps, or 2) close it for now and revisit after we implement autosave. 

FWIW, per our discussions about autosave, I _think_ we discussed not having a route guard or cancel modal dialog at all once autosave is enabled. I brought up still having the route guard in place, in case you accidentally navigate away from the editor workflow, but I think the group consensus was  to not have this confirmation dialog if you click "cancel," as that's an intentional click and you won't lose any work, so no need to introduce another thing for people to click on.

What do you think?

**Comment by gashcrumb** [comment]
Ah of course, I remember now!

Cool, let's revisit when we implement autosave/route guards.  But yeah, for a single page you're implementation looks good to me :-)

**Pull request closed without merging**
