### PR TITLE
#4203: adding the data integration image to the syndesis build

### PR DESCRIPTION
**Pull request by rareddy**

### CODE REVIEW

**Comment by zregvart** [comment]
This looks good to me on a technical level, just needs to add changes from the generator -- to include the changed output YAML files.

I'm trying to think of ways this can backfire, and perhaps the only two things would be: the day-to-day of the developer and if we need to increase the default 4GB memory setting for the minishift (via `syndesis minishift --install`) and any memory limit issues we might encounter on the trial cluster.

I can't really tell how big of an issue those two are, care to chip in @rhuss @heiko-braun @gaughan ?

Also heads up @djcoleman @orpiske and @cunningt this will change the Syndesis template and introduce a new image stream.

**Comment by heiko-braun** [comment]
@rareddy How is `IncludeDint` passed into the build? Is it an optional flag to the outermost build scripts? 

On a related note: Please although think through and supply the changes need to the product installation scripts: https://github.com/syndesisio/fuse-online-install

**Comment by rareddy** [comment]
@heiko-braun These are either called manually or using pre-commit hook per @zregvart  See the comment on #4203 

As per the size, I put in size for 1GB requirement for this image, I am sure this will push the limits if they are set very conservatively.

**Comment by gaughan** [comment]
Mini shift and eval cluster might be an issue. Both are short term tho with Openshift 4.1 and intergreatly trial accounts on the horizon. It might be nice to have pods scale when not in use tho

**Comment by heiko-braun** [comment]
Please hold thi suntil we have clarified if we need templates at all for data virt

**Pull request merged**
