### PR TITLE
feat: The sysdesis operator binary can now be used to install syndesis into a mini shift cluster.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by heiko-braun** [comment]
> The sysdesis operator binary can now be used to install syndesis into a mini shift cluster

Can you elaborate on that?

**Comment by nicolaferraro** [comment]
Nice work, that's the right direction!

I get installation stuck at:
```
syndesis-operator-1-hsw5k syndesis-operator {"level":"info","ts":1564518979.896481,"logger":"action","msg":"Installing Syndesis resource","type":"install","name":"app"}
syndesis-operator-1-hsw5k syndesis-operator {"level":"info","ts":1564518987.141394,"logger":"action","msg":"Failed to create or replace resource","type":"install","kind":"Role","name":"syndesis-editor","namespace":"chirino"}
```

I'm running as admin.

Maybe better printing more information about the error, it should be some permission missing in the `syndesis-operator` role.

**Comment by chirino** [comment]
@nicolaferraro operator needed more perms.  Should be better now.

**Comment by chirino** [comment]
@heiko-braun that's what I hope will happen, not needing those scripts anymore.

**Comment by chirino** [comment]
Also added a `install --dev` option which uses images which were built locally against your openshift cluster (via s2i builds).

**Comment by chirino** [comment]
This also opens up the path to moving upgrade functions that are in the upgrade image into the operator too (it would sill spin an upgrade pod, but reuse the operator image).

**Comment by chirino** [comment]
rebased and squashed a bit.

**Comment by chirino** [comment]
Merging so I can start working on my next set of changes.

**Pull request merged**
