### PR TITLE
chore(deps): Node-SASS dependency upgrade

### PR DESCRIPTION
**Pull request by squakez**
* Node-SASS

### CODE REVIEW

**Comment by squakez** [comment]
cc @zregvart @gashcrumb

**Review by cunningt — COMMENTED** [review]
The cache hash here in outputFileName https://github.com/syndesisio/syndesis/blob/44db4c22d1c56a2c7c37dd4fa5896830edf74ae3/app/ui-react/pom.xml#L320 is also going to need to be changed, not sure to what

**Comment by zregvart** [comment]
Seems to fail on QE CI with:

```
[INFO] [4/4] Rebuilding all packages...
[INFO] error /mnt/hudson_workspace/workspace/fuse-7.10-syndesis-tests-PR-ENG/syndesis/app/ui-react/node_modules/iltorb: Command failed.
[INFO] Exit code: 1
[INFO] Command: node ./scripts/install.js || node-gyp rebuild
[INFO] Arguments: 
[INFO] Directory: /mnt/hudson_workspace/workspace/fuse-7.10-syndesis-tests-PR-ENG/syndesis/app/ui-react/node_modules/iltorb
[INFO] Output:
[INFO] info npm cache directory missing, creating it... 
[INFO] info looking for cached prebuild @ /home/hudson/.npm/_prebuilds/c57c4d-iltorb-v2.4.5-node-v83-linux-x64.tar.gz
[INFO] http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-linux-x64.tar.gz
[INFO] http 404 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-linux-x64.tar.gz
[INFO] WARN install No prebuilt binaries found (target=14.17.3 runtime=node arch=x64 libc= platform=linux)
[INFO] gyp info it worked if it ends with ok
[INFO] gyp info using node-gyp@5.1.0
[INFO] gyp info using node@14.17.3 | linux | x64
[INFO] gyp ERR! find Python 
[INFO] gyp ERR! find Python Python is not set from command line or npm configuration
[INFO] gyp ERR! find Python Python is not set from environment variable PYTHON
[INFO] gyp ERR! find Python checking if "python" can be used
[INFO] gyp ERR! find Python - "python" is not in PATH or produced an error
[INFO] gyp ERR! find Python checking if "python2" can be used
[INFO] gyp ERR! find Python - "python2" is not in PATH or produced an error
[INFO] gyp ERR! find Python checking if "python3" can be used
[INFO] gyp ERR! find Python - "python3" is not in PATH or produced an error
[INFO] gyp ERR! find Python 
[INFO] gyp ERR! find Python **********************************************************
[INFO] gyp ERR! find Python You need to install the latest version of Python.
[INFO] gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
[INFO] gyp ERR! find Python you can try one of the following options:
[INFO] gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
[INFO] gyp ERR! find Python   (accepted by both node-gyp and npm)
[INFO] gyp ERR! find Python - Set the environment variable PYTHON
[INFO] gyp ERR! find Python - Set the npm configuration variable python:
[INFO] gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
[INFO] gyp ERR! find Python For more information consult the documentation at:
[INFO] gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
[INFO] gyp ERR! find Python **********************************************************
[INFO] gyp ERR! find Python 
[INFO] gyp ERR! configure error 
[INFO] gyp ERR! stack Error: Could not find any Python installation to use
[INFO] gyp ERR! stack     at PythonFinder.fail (/mnt/hudson_workspace/workspace/fuse-7.10-syndesis-tests-PR-ENG/syndesis/app/ui-react/node_modules/node-gyp/lib/find-python.js:307:47)
[INFO] gyp ERR! stack     at PythonFinder.runChecks (/mnt/hudson_workspace/workspace/fuse-7.10-syndesis-tests-PR-ENG/syndesis/app/ui-react/node_modules/node-gyp/lib/find-python.js:136:21)
[INFO] gyp ERR! stack     at PythonFinder.<anonymous> (/mnt/hudson_workspace/workspace/fuse-7.10-syndesis-tests-PR-ENG/syndesis/app/ui-react/node_modules/node-gyp/lib/find-python.js:179:16)
[INFO] gyp ERR! stack     at PythonFinder.execFileCallback (/mnt/hudson_workspace/workspace/fuse-7.10-syndesis-tests-PR-ENG/syndesis/app/ui-react/node_modules/node-gyp/lib/find-python.js:271:16)
[INFO] gyp ERR! stack     at exithandler (child_process.js:326:5)
[INFO] gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:338:5)
[INFO] gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
[INFO] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[INFO] gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
[INFO] gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
[INFO] gyp ERR! System Linux 4.18.0-147.el8.x86_64
[INFO] gyp ERR! command "/mnt/hudson_workspace/workspace/fuse-7.10-syndesis-tests-PR-ENG/syndesis/app/ui-react/node/node" "/mnt/hudson_workspace/workspace/fuse-7.10-syndesis-tests-PR-ENG/syndesis/app/ui-react/node_modules/.bin/node-gyp" "rebuild"
[INFO] gyp ERR! cwd /mnt/hudson_workspace/workspace/fuse-7.10-syndesis-tests-PR-ENG/syndesis/app/ui-react/node_modules/iltorb
[INFO] gyp ERR! node -v v14.17.3
[INFO] gyp ERR! node-gyp -v v5.1.0
[INFO] gyp ERR! not ok
[INFO] gyp ERR! find Python checking if "python2" can be usedinfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by squakez** [comment]
> The cache hash here in outputFileName
> 
> https://github.com/syndesisio/syndesis/blob/44db4c22d1c56a2c7c37dd4fa5896830edf74ae3/app/ui-react/pom.xml#L320
> is also going to need to be changed, not sure to what

it seems to be resolved as `c57c4d` --> `[INFO] info looking for cached prebuild @ /home/hudson/.npm/_prebuilds/c57c4d-iltorb-v2.4.5-node-v83-linux-x64.tar.gz`

**Comment by squakez** [comment]
Having a deeper look, it seems the `4.x` dependency is required by some Apicurito dependency:
```
 "peerDependencies": {
...
    "node-sass": "^4.0.0 || ^5.0.0",
...
  },
```
Closing this for the time being.

**Pull request closed without merging**
