### PR TITLE
feat(monitoring): Reference SOP documentation from alerts

### PR DESCRIPTION
**Pull request by jamesnetherton**
Ref #4151

### CODE REVIEW

**Comment by lgarciaaco** [comment]
We need to set clear expectations for these alerts. I am going to take  *FuseOnlineDatabaseHighRollbackRate* and *FuseOnlineDatabaseHighConnectionCount* as example. These alerts **SHOULD not** be exposed to NOC, mainly because there is nothing they can do to solve the problem (probably not even engineers from our team can do something more than further investigation). I am not saying that we don't need the metrics, but more as a support for further debugging (probably a dashboard is enough).

*FuseOnlineDatabaseHighRollbackRate* and *FuseOnlineDatabaseHighConnectionCount* will cause the application using the database to start throwing errors, and that is what we want to monitor/alert upon.

Imho, only golden signals should be monitored atm: https://www.infoq.com/articles/monitoring-SRE-golden-signals

Maybe this is not the right place but I just wanted to start the discussion :)

**Comment by jamesnetherton** [comment]
Sure - makes sense. I felt compelled to add them as I didn't have much in the way of alerting for the DB. But you're right. We should focus on symptoms, not causes. The DB dashboard will cover those metrics anyway.

If you think we should definitely remove them, I'll raise a PR shortly to do that.

**Comment by lgarciaaco** [comment]
I think *FuseOnlineRestApiHighEndpointErrorRate*, *FuseOnlineRestApiHighEndpointLatency* and *FuseOnlineDatabaseInstanceDown* are the ones we want to receive alerts from, the rest should be dashboarded or the alerts should go to a channel for history purposes.

**Comment by jamesnetherton** [comment]
Ok - agreed. 

Let's aim to keep things simple to being with. I'll remove the other redundant alerts for now. They are already covered comprehensively by the dashboards.

**Comment by jamesnetherton** [comment]
PR updated to reflect the reduced set of alerts as we discussed.

**Pull request merged**
