### PR TITLE
Fixes #5475 Disable DataVirt UI when Komodo server isn't present

### LINKED ISSUE #5475: Disable DataVirt UI when Komodo server isn't present
In certain environments the DataVirt backend may not or cannot be installed. The user interface needs to suppress the dataVirt parts, when the komodo server isn't available to address these situations.

### PR DESCRIPTION
**Pull request by rkorytkowski**
https://github.com/syndesisio/syndesis/issues/5475

### CODE REVIEW

**Comment by riccardo-forina** [comment]
I'm not sure, should we keep the "Data" link in the sidebar or not?

**Comment by rkorytkowski** [comment]
It makes sense to show "Data", if we want to communicate such a feature exists at this point. @asmigala suggested to keep it, see https://github.com/syndesisio/syndesis/issues/5475#issuecomment-498546837

**Comment by riccardo-forina** [comment]
Alright then. But yeah as Zoran said 'til we have this two repos split we need the react bits pushed on the react repo.

**Comment by rkorytkowski** [comment]
@riccardo-forina, you want me to create a PR to https://github.com/syndesisio/syndesis-react or is someone else handling that?

**Comment by riccardo-forina** [comment]
Yes if you can do that on syndesisio/syndesis-react  it would be great!
For the moment any change that's done in the ui-react folder should happen in syndesisio/syndesis-react instead.

**Comment by rkorytkowski** [comment]
Okay! I'll do it right away.

**Comment by rkorytkowski** [comment]
UI part in https://github.com/syndesisio/syndesis-react/pull/467

**Comment by zregvart** [comment]
Let's wait for #5739 to be merged, then I think this needs a rebase and it can be merged.

**Comment by rkorytkowski** [comment]
@zregvart, it seems that rebase is not needed.

**Pull request merged**
