### PR TITLE
ENTESB-16039 - fix issue with conditional flow throwing exception

### PR DESCRIPTION
**Pull request by kahboom**
addresses the first two relevant points in [ENTESB-16039](https://issues.redhat.com/browse/ENTESB-16039).

apologies for the formatting changes in the diff, not sure why this wasn't auto-formatted with prettier before.

### CODE REVIEW

**Review by gashcrumb — APPROVED** [review]
:+1:

**Comment by kahboom** [comment]
retest this please

**Comment by gashcrumb** [comment]
Might need to rebase?

**Comment by kahboom** [comment]
@dependabot rebase

**Comment by kahboom** [comment]
retest this please

**Review by gashcrumb — APPROVED** [review]
:+1:

**Pull request merged**
