### PR TITLE
Update ng-dynamic-forms (and like bunches of other deps as a result)

### LINKED ISSUE #938: Upgrade ng-dynamic-forms
While upgrading ng-dynamic-forms as part of https://github.com/syndesisio/syndesis/pull/897 it was realized that several other peer dependencies will need to be upgraded at the same time, as they share dependencies.

Possibly more, but these seem to be the main libraries needing an upgrade.

ng-dynamic-forms
ngx-chips
ngx-bootstrap
rxjs

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes #938

### CODE REVIEW

**Comment by gashcrumb** [comment]
Not working at runtime yet so WIP

**Comment by gashcrumb** [comment]
Current problem is that an older ngx-bootstrap version is being picked up at runtime that isn't angular 5.x compatible due to using `<template>` vs `<ng-template>`:

```
Can't bind to 'ngOutletContext' since it isn't a known property of 'template'. ("ate -->
<template [ngTemplateOutlet]="optionsListTemplate || (isBs4 ? bs4Template : bs3Template)"
  [ERROR ->][ngOutletContext]="{matches:matches, itemTemplate:itemTemplate, query:query}"></template>

<!-- defau"): ng:///TypeaheadModule/TypeaheadContainerComponent.html@3:2
"let-" is only supported on ng-template elements. ("

<!-- default options item template -->
<template #bsItemTemplate [ERROR ->]let-match="match" let-query="query"><span [innerHtml]="hightlight(match, query)"></span></template>

"): ng:///TypeaheadModule/TypeaheadContainerComponent.html@6:26
"let-" is only supported on ng-template elements. ("

<!-- default options item template -->
<template #bsItemTemplate let-match="match" [ERROR ->]let-query="query"><span [innerHtml]="hightlight(match, query)"></span></template>
```

This old version is present in `@atlasmap/atlasmap.data.mapper` and `patternfly-ng`, why it's getting used at runtime though I've yet to figure out :-)

**Comment by jimmidyson** [comment]
Can this wait until TP3 is tagged/released?

**Comment by gashcrumb** [comment]
@jimmidyson oh absolutely, this is more open for collaboration than anything at the moment.

**Comment by deeleman** [comment]
I have a local branch with a full update of Angular, Angular CLI and all the bootstrapping files required.

Unfortunately, dependencies containing non-transpiled TypeScript code such as Patternfly, AtlasMapper and a good bunch of circular references will prevent this from working.

In other words, it will take more (way much more actually) than bumping versions on package.json to get Angular updated. I’ve been warning about this for a while now.

**Comment by gashcrumb** [comment]
@deeleman if you wanna maybe push that branch I wouldn't mind taking a look.  Right after tp3 is cut we might wanna get this going.

**Comment by gashcrumb** [comment]
Think I might park this for now and close this PR so it's not sitting around forever, but I'd definitely like to get this done ASAP.

**Pull request closed without merging**
