### PR TITLE
Upgrade, invoke db scripts

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by paoloantinori** [comment]
fixes #1512

**Comment by avano** [comment]
hi @paoloantinori, @rhuss, @dsimansk 

how does the syndesis-cli access the syndesis database?

Doesn't the script miss the port forward to syndesis-db and parameters?

Because currently the script is trying to plain invoke java -jar syndesis-cli.jar that is trying to connect to localhost:5432 and it is causing the whole upgrade process to fail.

And second thing, if we want to externalize the syndesis-cli.jar to upgrade the DB, the syndesis-upgrade deployment will need to have the ENV vars for username and password for accessing the DB

**Comment by rhuss** [comment]
@avano the idea is that the update typically should run from within the cluster, so there the name of the db host would be just 'syndesis-db'. And yes, username and password need to be picked up then from the proper configmap (we already know how to read it).

However it would be awesome also when the upgrade script would be able to run from the outside (even if only for testing), so we need to distinguish that case and then open a port-forward to the syndesis-db pod and connect to localhost. The DB user and password can be still read from the secrets.

**Comment by rhuss** [comment]
Actually, setting up the connection is the real hard part of the db upgrade story ;)

**Pull request merged**
