### PR TITLE
fix: DropBox Connector

### PR DESCRIPTION
**Pull request by sunilmeddr**
Fixes: #1189

### CODE REVIEW

**Comment by dsimansk** [comment]
@paoloantinori could we get this PR reviewed, if someone has spare cycle for it?

**Comment by rhuss** [comment]
Could we get this PR merged today ? (i'm planning some refactorings over the weekend, so conflicts are likely afterwards, though probably easy to fix)

**Comment by oscerd** [comment]
We are in the process of reviewing this and check if it reflects the camel component the right way, I don't think we'll be able to merge today..

**Comment by rhuss** [comment]
ok, just talked with @lburgazzoli . I'm going to make the refactoring nevertheless, conflicts shouldnt be too hard to resolve afterwards.

**Comment by oscerd** [comment]
I'm looking at this one, for rebasing and check if it works after rebasing.

**Comment by oscerd** [comment]
Superseded by #1812

**Pull request closed without merging**
