### PR TITLE
Fixes #2444: Updated integration pod label, made labels configurable in Prometheus metrics implementation

### LINKED ISSUE #2444: No metrics are collected and displayed
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
For a running integration I don't see metrics numbers to be updated periodically as exchanges are flowing through. My suspicion is that `app=syndesis` label is blocking the scraping or any other from https://github.com/syndesisio/syndesis/commit/476d1eac4e0720ce456c8ef0879ca7ddb357a714.

@dhirajsb wdyt?

Prometheus log from TP4 that grows steadily:
```
evel=info ts=2018-04-05T19:03:16.725499527Z caller=main.go:225 msg="Starting Prometheus" version="(version=2.1.0, branch=HEAD, revision=85f23d82a045d103ea7f3c89a91fba4a93e6367a)"
--
  | level=info ts=2018-04-05T19:03:16.725570503Z caller=main.go:226 build_context="(go=go1.9.2, user=root@6e784304d3ff, date=20180119-12:01:23)"
  | level=info ts=2018-04-05T19:03:16.725599655Z caller=main.go:227 host_details="(Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 syndesis-prometheus-1-9j2b2 (none))"
  | level=info ts=2018-04-05T19:03:16.725614443Z caller=main.go:228 fd_limits="(soft=1048576, hard=1048576)"
  | level=info ts=2018-04-05T19:03:16.728775656Z caller=web.go:383 component=web msg="Start listening for connections" address=0.0.0.0:9090
  | level=info ts=2018-04-05T19:03:16.728482177Z caller=main.go:499 msg="Starting TSDB ..."
  | level=info ts=2018-04-05T19:03:16.737321148Z caller=main.go:509 msg="TSDB started"
  | level=info ts=2018-04-05T19:03:16.737362408Z caller=main.go:585 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
  | level=info ts=2018-04-05T19:03:16.738717738Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
  | level=info ts=2018-04-05T19:03:16.739448018Z caller=main.go:486 msg="Server is ready to receive web requests."
  | level=info ts=2018-04-05T19:03:16.739487149Z caller=manager.go:59 component="scrape manager" msg="Starting scrape manager..."
  | level=info ts=2018-04-05T21:00:04.606894795Z caller=compact.go:387 component=tsdb msg="compact blocks" count=1 mint=1522951200000 maxt=1522958400000
  | level=info ts=2018-04-05T21:00:04.633718044Z caller=head.go:348 component=tsdb msg="head GC completed" duration=1.681352ms
  | level=info ts=2018-04-05T21:00:04.633768839Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=2.066µs
  | level=info ts=2018-04-05T23:00:04.607313596Z caller=compact.go:387 component=tsdb msg="compact blocks" count=1 mint=1522958400000 maxt=1522965600000
  | level=info ts=2018-04-05T23:00:04.637361545Z caller=head.go:348 component=tsdb msg="head GC completed" duration=895.659µs
  | level=info ts=2018-04-05T23:00:04.6374084Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=2.17µs
  | level=info ts=2018-04-06T01:00:04.60717232Z caller=compact.go:387 component=tsdb msg="compact blocks" count=1 mint=1522965600000 maxt=1522972800000
  | level=info ts=2018-04-06T01:00:04.637237103Z caller=head.go:348 component=tsdb msg="head GC completed" duration=884.222µs
  | level=info ts=2018-04-06T01:00:04.637289182Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=2.691µs
  | level=info ts=2018-04-06T01:00:04.639691404Z caller=compact.go:387 component=tsdb msg="compact blocks" count=3 mint=1522951200000 maxt=1522972800000
  | level=info ts=2018-04-06T03:00:04.607060672Z caller=compact.go:387 component=tsdb msg="compact blocks" count=1 mint=1522972800000 maxt=1522980000000
  | level=info ts=2018-04-06T03:00:04.639141136Z caller=head.go:348 component=tsdb msg="head GC completed" duration=884.451µs
  | level=info ts=2018-04-06T03:00:04.639191633Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=2.978µs
```

Prometheus from current master that is stalled (on same integration):
```
level=info ts=2018-04-19T06:30:49.062743732Z caller=main.go:225 msg="Starting Prometheus" version="(version=2.1.0, branch=HEAD, revision=85f23d82a045d103ea7f3c89a91fba4a93e6367a)"
level=info ts=2018-04-19T06:30:49.062819245Z caller=main.go:226 build_context="(go=go1.9.2, user=root@6e784304d3ff, date=20180119-12:01:23)"
level=info ts=2018-04-19T06:30:49.062843215Z caller=main.go:227 host_details="(Linux 4.4.41-boot2docker #1 SMP Wed Jan 11 03:05:24 UTC 2017 x86_64 syndesis-prometheus-1-p8x6w (none))"
level=info ts=2018-04-19T06:30:49.06287353Z caller=main.go:228 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2018-04-19T06:30:49.102895289Z caller=web.go:383 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-04-19T06:30:49.102861984Z caller=main.go:499 msg="Starting TSDB ..."
level=info ts=2018-04-19T06:30:49.211129501Z caller=main.go:509 msg="TSDB started"
level=info ts=2018-04-19T06:30:49.211215373Z caller=main.go:585 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2018-04-19T06:30:49.22330559Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-04-19T06:30:49.234368418Z caller=main.go:486 msg="Server is ready to receive web requests."
level=info ts=2018-04-19T06:30:49.234790986Z caller=manager.go:59 component="scrape manager" msg="Starting scrape manager..."
level=info ts=2018-04-19T09:00:04.638008531Z caller=compact.go:387 component=tsdb msg="compact blocks" count=1 mint=1524117600000 maxt=1524124800000
level=info ts=2018-04-19T09:00:04.829312216Z caller=head.go:348 component=tsdb msg="head GC completed" duration=4.862997ms
level=info ts=2018-04-19T09:00:04.829396435Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=1.966µs
```

## Expected behavior
Numbers are increasing per exchange.

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dsimansk** [comment]
@dhirajsb I've tried to build backend from your PR, but I still can't see any metrics collected. Am I missing something? E.g. some templates update or...?

**Comment by rhuss** [comment]
for me, the code here looks good.

**Comment by dhirajsb** [comment]
@dsimansk did you update Prometheus configmap from Roland's previous changes?

**Comment by dhirajsb** [comment]
@dsimansk, I'm rebuilding my environment to test again, to make sure I didn't have something stale locally.

**Comment by rhuss** [comment]
@dsimansk feel free to aprove when it works for you. sorry, I'm too busy with my conf preps right now.

**Comment by dhirajsb** [comment]
@dsimansk I rebuilt my minishift namespace and tested it again, and it seems to be working for me. See screenshots
image
image

**Pull request merged**
