### PR TITLE
chore: add .mention-bot configuration file

### LINKED ISSUE #418: Re-enable mention-bot on syndesis repository
We should re-enable purebot for code review assignement on the syndesisio/syndesis repository.

### PR DESCRIPTION
**Pull request by zregvart**
Fixes #418

### CODE REVIEW

**Comment by jimmidyson** [comment]
Wonder if we should now use the [code](https://github.com/blog/2392-introducing-code-owners) [owners](https://help.github.com/articles/about-codeowners/) facility of github?

**Comment by zregvart** [comment]
> Wonder if we should now use the code owners facility of github?

could be I see that it supports groups also...

**Comment by zregvart** [comment]
> > Wonder if we should now use the code owners facility of github?
> 
> could be I see that it supports groups also...

Actually, I'm not sure, I would like that we don't split into groups, i.e. that everyone works on all parts of the stack (eventually). With `git blame` way of assigning we don't tie review to a particular person or group.

2c

**Comment by rhuss** [comment]
My suggestion: Try this out, check whether it works, and if not, try GitHub code owners.

**Pull request merged**
