### PR TITLE
Add CR/CRD Validation

### PR DESCRIPTION
**Pull request by rashelrr**
Added CR/CRD Validation.
Added go mod vendor changes.

### CODE REVIEW

**Comment by claudio4j** [comment]
@rashelrr Do you have the issue tracker for this fix ?

**Comment by KurtStam** [comment]
@rashelrr can you rebase? It will fix the integration tests. thx!

**Comment by rashelrr** [comment]
> @rashelrr Do you have the issue tracker for this fix ?

I don't have access to it, how should I proceed?

**Comment by rashelrr** [comment]
> @rashelrr can you rebase? It will fix the integration tests. thx!

I've rebased.

**Comment by claudio4j** [comment]
> > @rashelrr Do you have the issue tracker for this fix ?
> 
> I don't have access to it, how should I proceed?

It is the jira link. Do you have a request asking to add the crd validation tests ?

**Comment by myeung18** [comment]
> > > @rashelrr Do you have the issue tracker for this fix ?
> > 
> > 
> > I don't have access to it, how should I proceed?
> 
> It is the jira link. Do you have a request asking to add the crd validation tests ?

Hi @claudio4j   We don't have the jira link.  We created this PR is meant to contribute and bring in the validation which is common among integration operators.  Do you want us to create an jira and where?

**Comment by claudio4j** [comment]
> Do you want us to create an jira and where?
Not necessary, I thought there was a issue link. I am just waiting for the PR tests to pass and I will merge them.

**Pull request merged**
