### PR TITLE
Bump camel version to 2.21.0.fuse-750033

### PR DESCRIPTION
**Pull request by claudio4j**

### CODE REVIEW

**Comment by zregvart** [comment]
@claudio4j I've regenerated the assets_vfsdata.go from a clean git checkout and pushed a commit in 0e18f21 to have the CI check pass.

**Comment by claudio4j** [comment]
> @claudio4j I've regenerated the assets_vfsdata.go from a clean git checkout and pushed a commit in [0e18f21](https://github.com/syndesisio/syndesis/commit/0e18f21ac79545dbd4d5c2c70dca03300d80be1f) to have the CI check pass.

Thank you Zoran, how to regenerate that file ?

**Comment by zregvart** [comment]
> Thank you Zoran, how to regenerate that file ?

I've run `go generate ./pkg/...` from `install/operator`. We also have a [pre-commit hook](https://github.com/syndesisio/syndesis/blob/0e96516d1bef4d510ef40dba374d3a567d923b2a/.lintstagedrc.js#L10-L12) that you could also use so it's always up to date.

**Comment by oscerd** [comment]
Just a question. Is it pinned on Nexus?

**Comment by zregvart** [comment]
> Just a question. Is it pinned on Nexus?

@oscerd I think I've done it correctly, so hopefully yes.

**Comment by oscerd** [comment]
Thanks, last time I forgot to pin cxf, that's why I was asking :-)

**Comment by zregvart** [comment]
> Thanks, last time I forgot to pin cxf, that's why I was asking :-)

I did not promote CXF staging repository, do we need to do that?

**Comment by oscerd** [comment]
yes, usually we need to pin: camel, cxf, cxf-xjc-utils if released, kube-client, kube-model

The reference for the versions should be found here

https://origin-repository.jboss.org/nexus/content/repositories/ea/org/jboss/redhat-fuse/redhat-fuse/7.5.0.fuse-750029/redhat-fuse-7.5.0.fuse-750029.pom

**Pull request merged**
