### PR TITLE
re #2613 Apicurio Integration

### PR DESCRIPTION
**Pull request by kahboom**
cc @gashcrumb

### CODE REVIEW

**Comment by gashcrumb** [comment]
Kewl, will take a look tomorrow @kahboom

**Comment by gashcrumb** [comment]
Turns out you have to read the file locally too, doesn't appear to actually be in the response back from posting it.  Once that's sorted:

capture

**Comment by gashcrumb** [comment]
Mind you, click on anything and you'll see loads of error messages, so there's definitely still work to be done.

**Comment by kahboom** [comment]
Just an update--there has been a lot put on hold since the Angular 6 upgrade. I've spent quite some time trying to sort out some issues mentioned [here](https://github.com/syndesisio/syndesis/issues/2614#issuecomment-402695400), also have a branch to test Apicurio embedding with Angular 6 here: https://github.com/Apicurio/apicurio-angular-demo/tree/angular-6

Seems there is an issue with ng-packagr and likely my configuration settings.

screenshot 2018-07-06 10 35 17

Was hoping to ensure 6.x compatibility and that it might take care of the original Yaml.js issue, but it's taking more time than it's worth, so I'll focus on resolving the issue with Angular 5.x first.

**Comment by gashcrumb** [comment]
Yep, makes sense!  Looks like you need to rebase this PR and do `push -f` as seems to have picked up lots of other commits from master, but probably best to focus on debugging the issue with the sidebar in the example app first and get that sorted.  

We'll definitely also need to ensure Angular 6.x compatibility though, with that comes some possible rxjs migration.  You might want to have a chat with @seanforyou23 on that, he did all the migration work for Syndesis and can probably point you in the right direction for apicurio.

**Comment by kahboom** [comment]
@gashcrumb - Right, I was seeing that! Looks like compatibility with Angular 6 won't be a problem, I've set up a branch to test a few things and it actually looks like it solves some other issues. So I'll focus on 5 and think 6 won't be a major problem, but of course, you never know..

**Comment by kahboom** [comment]
Actually, on rebasing I do bring in Angular 6, so I'll work within the Apicurio Angular Demo for now and sort out this issue later.. may make more sense to close this PR and re-open when ready.

**Comment by kahboom** [comment]
@gashcrumb - Had to create a window service to deal with the hacky solution in a slightly better manner. I am still running into an error that looks pretty familiar, but I can't tell if it was something that happened during the huge rebase.

By the way, apologies for the duplicated commits. I need to rebase more frequently and can squash all the duplicates if you'd prefer.

screenshot 2018-07-13 01 30 01

**Comment by gashcrumb** [comment]
Think you just need to do `push -f` after you do your rebase.

The error is complaining about this line -> https://github.com/syndesisio/syndesis/pull/2886/files#diff-b25c2fa263e6ff5b15a5e499f0e2f2a8R72 

Is that property exposed as an input by the `api-editor` component?

**Comment by paoloantinori** [comment]
Careful with `push -f` and let's try to avoid it as much as possible! :japanese_ogre:

**Comment by gashcrumb** [comment]
@paoloantinori that's mostly a concern for shared branches by an entire team, not so much PR branches.  When squashing commits on a PR where the commits have been published, a forced push is required.

**Comment by kahboom** [comment]
I also squashed the first commit, which created some issues. 🙈 Next time will try to have a cleaner PR and rebase more frequently.

UPDATE:
Although in the demo app it is working without issues, when importing into Syndesis (which uses a different ngx-bootstrap version and Angular 6) there are some other errors that need to be ironed out.

@gashcrumb has kindly been trying to help sort this out, but a little bit more time will be needed for the toolbar issue and apparently some local issues (server errors related to the Minishift instance) I'm having that prevented me from creating a proper demo in time.

**Comment by kahboom** [comment]
cc @paoloantinori - Sorry for the git mess; this is missing the toolbar and the user won't be able to complete the flow as expected, but we can still get this merged in if you'd like and I can sort out the toolbar issue tomorrow? Your call.

**Comment by paoloantinori** [comment]
Hi Rachel, github says that there are conflicts to resolve:


Conflicting files
app/ui/package.json

Can you fix them with a further commit?

**Comment by kahboom** [comment]
@paoloantinori - I resolved the conflicts this morning and squashed some duplicate commits to clean up the history a bit. Are you okay with me proceeding to merge it?

**Pull request merged**
