### PR TITLE
Activity: fix for serialization strategy and empty collections

### LINKED ISSUE #2065: Monitoring - Activity: error to display data since 1.3.2 tag
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
It seems there's a regression in `1.3.2` and latest master that prevents displaying of activities. It's working as expected on `1.3.1`. The error from browser console below. 

@deeleman is it related to the commit https://github.com/syndesisio/syndesis/commit/c779240933fefcafa8b037012e942a0aa30c582d ?

```
2018-03-19 13:47:39,091 ERROR [root] Error fetching activity records for integration ID i-L7yH_pRYe2XVUXIaQEvz
TypeError: Cannot read property 'forEach' of undefined
@
{anonymous}()@https://syndesis.192.168.64.17.nip.io/common.chunk.js:7226:32
  SafeSubscriber._next()@https://syndesis.192.168.64.17.nip.io/common.chunk.js:7225:26
  SafeSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrSetError()@https://syndesis.192.168.64.17.nip.io/polyfills.bundle.js:2926:16
  SafeSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next()@https://syndesis.192.168.64.17.nip.io/polyfills.bundle.js:2866:27
  Subscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next()@https://syndesis.192.168.64.17.nip.io/polyfills.bundle.js:2805:26
  Subscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next()@https://syndesis.192.168.64.17.nip.io/polyfills.bundle.js:2769:18
  DoSubscriber.webpackJsonp.../../../../rxjs/_esm5/operators/tap.js.DoSubscriber._next()@https://syndesis.192.168.64.17.nip.io/polyfills.bundle.js:6161:24
  DoSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next()@https://syndesis.192.168.64.17.nip.io/polyfills.bundle.js:2769:18
  CatchSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next()@https://syndesis.192.168.64.17.nip.io/polyfills.bundle.js:2805:26
```

## Screenshot
screen shot 2018-03-19 at 13 53 08

## Request and Response Data

```json
[
  {
    "id": "i-L7yJe-qTeealRdrBnaqz",
    "logts": "2018-03-19T12:53:45.143107529Z",
    "at": 1521464025142,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  },
  {
    "id": "i-L7yJbZaTeealRdrBnakz",
    "logts": "2018-03-19T12:53:35.143932271Z",
    "at": 1521464015142,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  },
  {
    "id": "i-L7yJ_7KTeealRdrBnaez",
    "logts": "2018-03-19T12:53:25.143172743Z",
    "at": 1521464005141,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  },
  {
    "id": "i-L7yJXg4TeealRdrBnaZz",
    "logts": "2018-03-19T12:53:15.142806427Z",
    "at": 1521463995141,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  },
  {
    "id": "i-L7yJVEpTeealRdrBnaTz",
    "logts": "2018-03-19T12:53:05.143404102Z",
    "at": 1521463985141,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  },
  {
    "id": "i-L7yJSnaTeealRdrBnaNz",
    "logts": "2018-03-19T12:52:55.159079232Z",
    "at": 1521463975142,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  },
  {
    "id": "i-L7yJQMKTeealRdrBnaHz",
    "logts": "2018-03-19T12:52:45.143426388Z",
    "at": 1521463965141,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  },
  {
    "id": "i-L7yJNv4TeealRdrBnaBz",
    "logts": "2018-03-19T12:52:35.141632623Z",
    "at": 1521463955141,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  },
  {
    "id": "i-L7yJLToTeealRdrBna5z",
    "logts": "2018-03-19T12:52:25.159943592Z",
    "at": 1521463945140,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  },
  {
    "id": "i-L7yJJ1ZTeealRdrBna-z",
    "logts": "2018-03-19T12:52:15.141258436Z",
    "at": 1521463935140,
    "pod": "i-db-db-2-btl8t",
    "ver": "1",
    "status": "done",
    "failed": false
  }
]
```

## Tasks involved / Steps to Reproduce

1. Create simple DB->DB integration
2. Wait until `Published`
3. Check detail view -> Activity tab

### PR DESCRIPTION
**Pull request by paoloantinori**
fixes #2065

This is quick and dirty, and one of the narrowest scope I could find to implement this.

Feel free to improve it but consider merging this to close this current blocker.
It would also deserve a unit test to avoid regressions in future.

### CODE REVIEW

**Comment by valdar** [comment]
@paoloantinori you have a PR to your branch https://github.com/paoloantinori/syndesis/pull/1 adding the test.

**Comment by rhuss** [comment]
@paoloantinori not sure whether this PR is still required as #2065 has been fixed. I think this PR can be closed.

**Comment by paoloantinori** [comment]
well, it's a matter of fixing this at client side only or fix it also at server side.

**Comment by paoloantinori** [comment]
any interest in fixing this server side? no?

**Comment by rhuss** [comment]
> well, it's a matter of fixing this at client side only or fix it also at server side.

@paoloantinori as its merged now, I'm fine with it. 

But not sure whether adding an empty collection is really to be considered a fix, when the client expect now an absent collection since the #2065 fix. Its just a matter how we define the API, and if the API states, an no-activity is absent instead of returning an empty array, than thats fine as well. Changing it on both sides (on the ui towards being absent, on the server side towards empty arrays) is for me not a fix, but just reverts the issue. It should be change only on one side.

If the UI can work with both, fine. but its just dilutes the API. 

just my two cents, fine with it though.

**Comment by paoloantinori** [comment]
hi. yes I agree. This is definitely one of the topics I'd like to focus on,
if we are given the chance again to improve a stabilize our API.

I think the Backen-UI flow will benefit a lot of something official, and
eventually, we could even generate tests based on fixed set of rules like
those.

**Pull request merged**
