### PR TITLE
Deleting a connection which is used by an integration leads to inconsistent state (backend)

### PR DESCRIPTION
**Pull request by lburgazzoli**
This PR is related to #2524 and:

- fixes the NPE thrown by syndesis-server when an integration with deleted connector is invoked
- introduces additional checks on integration level warn about inconsistent state of extensions or deleted connectors, @gashcrumb related codes are:

    ```java
        SYNDESIS009, // Connection has been deleted
        SYNDESIS010, // Multiple extension installed
    ```

The integration page now shows a warning on the impacted connection:

image

Going to integration summary, the following is shown:

image

There are some remaining issues I cannot fix on backend side

1. when an integration with deleted connections is edited, UI invokes the following endpoint

        /api/v1/connections/undefined/actions/${actionId}

    Here _undefined_ if obviously wrong and happens because the actualized connection does not have    the _connectorId_ set (as the connection does not exists any more).

2. New codes need to be integrated on UI side

### CODE REVIEW

**Comment by gashcrumb** [comment]
@lburgazzoli cool, lemme get those changes in place and update this PR.

**Comment by gashcrumb** [comment]
Yeah, I'm -1 to this...  Like what am I supposed to do in the editor, delete the affected connection?  I think this PR is going in the wrong direction.

capture

**Comment by lburgazzoli** [comment]
@gashcrumb rebased and squashed, now the step is re-setted but UI hangs now

**Comment by gashcrumb** [comment]
@lburgazzoli think that last commit should do it, lemme know if you see anything else.

**Comment by lburgazzoli** [comment]
@gashcrumb yes works for me, going to remove WIP

**Pull request merged**
