### PR TITLE
fix(install): operator permissions

### PR DESCRIPTION
**Pull request by zregvart**
When installing via the `syndesis-operator` CLI the permissions for `deploymentconfigs/finalizers` are required.

Otherwise this is printed to the output of the syndesis-operator pod log:

```
{"level":"error","ts":1572605346.2647836,"logger":"controller","msg":"Error reconciling","action":"*action.installAction","phase":"Installing","error":"roles.rbac.authorization.k8s.io \"syndesis-editor\" is forbidden: attempt to grant extra privileges: [{[get] [] [deploymentconfigs/finalizers] [] []} {[list] [] [deploymentconfigs/finalizers] [] []} {[create] [] [deploymentconfigs/finalizers] [] []} {[update] [] [deploymentconfigs/finalizers] [] []} {[delete] [] [deploymentconfigs/finalizers] [] []} {[deletecollection] [] [deploymentconfigs/finalizers] [] []} {[watch] [] [deploymentconfigs/finalizers] [] []} {[patch] [] [deploymentconfigs/finalizers] [] []} {[get] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[list] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[create] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[update] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[delete] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[deletecollection] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[watch] [apps.openshift.io] [deploymentconfigs/finalizers] [] []} {[patch] [apps.openshift.io] [deploymentconfigs/finalizers] [] []}] user=&{system:serviceaccount:syndesis:syndesis-operator 5a42e0e8-fbf6-11e9-8816-5254000da7ac [system:serviceaccounts system:serviceaccounts:syndesis system:authenticated] map[]} ownerrules=[{[get] [ user.openshift.io] [users] [~] []} {[list] [ project.openshift.io] [projectrequests] [] []} {[get list] [ authorization.openshift.io] [clusterroles] [] []} {[get list watch] [rbac.authorization.k8s.io] [clusterroles] [] []} {[get list] [storage.k8s.io] [storageclasses] [] []} {[list watch] [ project.openshift.io] [projects] [] []} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] [] [] [] [/healthz /healthz/*]} {[get] [] [] [] [/version /version/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /swaggerapi /swaggerapi/* /swagger.json /swagger-2.0.0.pb-v1 /osapi /osapi/ /.well-known /.well-known/* /]} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[create] [ build.openshift.io] [builds/docker builds/optimizeddocker] [] []} {[create] [ build.openshift.io] [builds/jenkinspipeline] [] []} {[create] [ build.openshift.io] [builds/source] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]} {[delete] [ oauth.openshift.io] [oauthaccesstokens oauthauthorizetokens] [] []} {[get] [] [] [] [/version /version/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /swaggerapi /swaggerapi/* /swagger.json /swagger-2.0.0.pb-v1 /osapi /osapi/ /.well-known /.well-known/* /]} {[impersonate] [authentication.k8s.io] [userextras/scopes.authorization.openshift.io] [] []} {[create get] [ build.openshift.io] [buildconfigs/webhooks] [] []} {[impersonate] [] [serviceaccounts] [] []} {[get] [] [namespaces] [] []} {[get] [ project.openshift.io] [projects] [] []} {[impersonate] [] [serviceaccounts] [] []} {[get list create update delete deletecollection watch] [] [pods pods/exec services endpoints persistentvolumeclaims configmaps secrets serviceaccounts] [] []} {[get list create update delete deletecollection watch patch] [] [replicationcontrollers replicationcontrollers/scale] [] []} {[get list create update delete deletecollection watch patch] [apps] [daemonsets deployments deployments/scale replicasets replicasets/scale statefulsets statefulsets/scale] [] []} {[get list create update delete deletecollection watch patch] [extensions] [daemonsets deployments deployments/scale ingresses networkpolicies replicasets replicasets/scale replicationcontrollers/scale] [] []} {[get list watch] [] [bindings events limitranges namespaces/status pods/log pods/status replicationcontrollers/status resourcequotas resourcequotas/status] [] []} {[get list create update delete deletecollection watch patch] [ build.openshift.io] [buildconfigs buildconfigs/webhooks builds] [] []} {[create] [ build.openshift.io] [buildconfigs/instantiate buildconfigs/instantiatebinary builds/clone] [] []} {[update] [ build.openshift.io] [builds/details] [] []} {[get list watch] [ build.openshift.io] [builds/log] [] []} {[get list create update delete deletecollection watch patch] [ apps.openshift.io] [deploymentconfigs deploymentconfigs/scale] [] []} {[create] [ apps.openshift.io] [deploymentconfigrollbacks deploymentconfigs/instantiate deploymentconfigs/rollback] [] []} {[get list watch] [ apps.openshift.io] [deploymentconfigs/log deploymentconfigs/status] [] []} {[get list create update delete deletecollection watch patch] [ image.openshift.io] [imagestreams imagestreamimages imagestreammappings imagestreams/secrets imagestreamtags] [] []} {[create] [ image.openshift.io] [imagestreamimports] [] []} {[get list watch] [ image.openshift.io] [imagestreams/status] [] []} {[get list create update delete deletecollection watch patch] [route.openshift.io] [routes] [] []} {[get list create update delete deletecollection watch patch] [ template.openshift.io] [processedtemplates templateconfigs templateinstances templates] [] []} {[get list create update delete deletecollection watch patch] [ build.openshift.io] [buildlogs] [] []} {[get list create update delete deletecollection watch] [syndesis.io] [* */finalizers] [] []} {[get list create update delete deletecollection watch] [] [pods services endpoints persistentvolumeclaims configmaps secrets serviceaccounts] [] []} {[get] [] [pods/log] [] []} {[get list create update delete deletecollection watch] [] [replicationcontrollers replicationcontrollers/scale replicationcontrollers/status] [] []} {[get list create update delete deletecollection watch] [ build.openshift.io] [builds buildconfigs builds/details buildconfigs/webhooks buildconfigs/instantiatebinary builds/log] [] []} {[get list create update delete deletecollection watch patch] [ apps.openshift.io] [deploymentconfigs deploymentconfigs/scale] [] []} {[create] [ apps.openshift.io] [deploymentconfigrollbacks deploymentconfigs/instantiate deploymentconfigs/rollback] [] []} {[get list watch] [ apps.openshift.io] [deploymentconfigs/log deploymentconfigs/status] [] []} {[get list create update delete deletecollection watch patch] [ image.openshift.io] [imagestreams imagestreamimages imagestreammappings imagestreams/secrets imagestreamtags] [] []} {[get list watch] [ image.openshift.io] [imagestreams/status imagestreamimports] [] []} {[get list] [] [events] [] []} {[get list create update delete deletecollection watch] [rbac.authorization.k8s.io] [roles rolebindings] [] []} {[get list create update delete deletecollection watch patch] [ template.openshift.io] [processedtemplates templateconfigs templateinstances templates] [] []} {[get list create update delete deletecollection watch] [authorization.openshift.io] [rolebindings] [] []} {[get list create update delete deletecollection watch patch] [route.openshift.io] [routes routes/custom-host] [] []} {[get list create update delete deletecollection watch] [camel.apache.org] [*] [] []} {[get list create update delete deletecollection watch] [monitoring.coreos.com] [alertmanagers prometheuses servicemonitors prometheusrules] [] []} {[get list create update delete deletecollection watch] [integreatly.org] [grafanadashboards] [] []} {[get list watch] [serving.knative.dev] [services] [] []} {[get list watch] [eventing.knative.dev] [channels] [] []} {[get] [ image.openshift.io] [imagestreams/layers] [] []}] ruleResolutionErrors=[]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/circleci/project/install/operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/syndesisio/syndesis/install/operator/pkg/controller/syndesis.(*ReconcileSyndesis).Reconcile\n\t/home/circleci/project/install/operator/pkg/controller/syndesis/syndesis_controller.go:120\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/circleci/project/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/circleci/project/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/circleci/project/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/circleci/project/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/circleci/project/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

### CODE REVIEW

**Comment by zregvart** [comment]
I've tested with:

```shell
$ minishift start
$ oc login -u admin -p admin
$ (cd install/operator && ./build.sh --image-build skip --source-gen on) # build the operator
$ install/operator/dist/linux-amd64/syndesis-operator install cluster
$ install/operator/dist/linux-amd64/syndesis-operator install app --dev
```

At that point the `syndesis-db` pod started otherwise it would not.

**Comment by phantomjinx** [comment]
Wow! Starting to feel this permission is haunting me - how very apt for Halloween.

The process of
1. syndesis install cluster
2. syndesis install operator

has always been a little vague on what step 2 should be executed as (other than $user). What do I mean by that?
Well, step 1 is very clear that it needs to be executed as `cluster-admin` (says it in help, checked in scripts etc.). However, there are two use-cases that crop up:
a. As system:admin execute step 1 then as 'developer' execute step 2
b. As system:admin give developer cluster-admin then as 'developer' execute step 1 & 2

Use-case b has always been my interpretation (erroneously perhaps) of achieving success over the two steps (do the cluster-admin escalation once and be done with it) and thus it has been unnecessary to provide the syndesis-operator with the deploymentconfigs/finalizers permission during step 1 since 'developer' (as a cluster-admin) has always had the power to provide it during step 2.

So this is perhaps the crux of why this permission has caused so much trouble. My bad? probably.
Can we mitigage against it? (Constructive :-) ) suggestions welcome.

@heiko-braun @lgarciaaco

**Comment by zregvart** [comment]
@phantomjinx yeah my bad, the `syndesis-operator install app --dev` is to be run by an non-admin user.

**Comment by zregvart** [comment]
@phantomjinx @lgarciaaco do we need to backport this to `1.8.x`?

**Comment by lgarciaaco** [comment]
Part of it is already in with https://github.com/syndesisio/syndesis/pull/6965/files

**Pull request merged**
