### PR TITLE
Lots of updates including user doc for logging, metrics, amq, amqp, s…

### PR DESCRIPTION
**Pull request by TovaCohen**
…3 connectors, custom connectors. 1623.
This is ready to merge. Lots of new and updated doc. While it needs to be reviewed, I want to bring it downstream so that it can be reviewed in the format that it will have on the customer portal. 
Both books (tutorial and ug) build successfully with ccutil. 
Thanks in advance for approving the merge.

### CODE REVIEW

**Comment by TovaCohen** [comment]
@fbolton I don't understand why there are conflicts. Can you help me understand what I did wrong this time?
I followed the instructions that appear when I click "view command line instructions" in the pull request. But I don't know where to see the result of what I did.

**Comment by gashcrumb** [comment]
@TovaCohen I think you need to update your master and then rebase this branch against it, when I try and check it out via the command line I find my local git has to rewind a bunch of commits before applying these changes.  When's the last time you've done a `git pull upstream master` or the equivalent in your git client?

**Comment by TovaCohen** [comment]
Thanks @gashcrumb . It was a while. That makes sense. I'll try that on Friday. I won't be in today. (Thursday).
I wonder if I messed up even more by following the instructions for conflict resolution that the link below offered. But I'll figure it out on Friday.

**Comment by TovaCohen** [comment]
Thanks @gashcrumb, I rebased from upstream master, and resolved the conflicts. This is where I am now:
[tcohen@tcohen doc]$ git status
# On branch 1623-tp4-user-doc
# Your branch and 'origin/1623-tp4-user-doc' have diverged,
# and have 221 and 1 different commit each, respectively.
#   (use "git pull" to merge the remote branch into yours)
#
nothing to commit, working directory clean
[tcohen@tcohen doc]$ 

Do I want to pull from origin to local, or push from local to origin? And I should also mention, that on
Wednesday, I did this:
git checkout -b TovaCohen-1623-tp4-user-doc master
git pull https://github.com/TovaCohen/syndesis.git 1623-tp4-user-doc
git checkout master
git merge --no-ff TovaCohen-1623-tp4-user-doc
git push origin master

Have I totally messed up my origin repo?
Thank you!

**Comment by gashcrumb** [comment]
So what you want to do is keep the master branch on your fork up to date with the upstream master branch.  The general workflow I use is (from the very beginning):

1. `git config --global --bool pull.rebase true && git config --global branch.autosetuprebase always` <--- always rebase by default
1. `git clone git@github.com:gashcrumb/syndesis.git` 
1. `git remote add upstream git@github.com:syndesisio/syndesis.git`
1. `git pull upstream master && git push` <--- I do this daily or whenever I want to pull in new stuff

When it's time to do stuff, I do the last step above first, then:

1.  `git checkout -b new-feature-branch-name`
1.  Do work, commit...

Before actually pushing my feature branch I want to be sure it'll merge, so:

1.  `git checkout master && git pull upstream master && git push`
1.  `git checkout new-feature-branch-name`
1.  `git rebase master`  <--- re-applies the commits on my feature branch on top of any new changes to master
1.  `git push origin new-feature-branch-name` and create PR

In your case where things went wrong was here:

```
git checkout master
git merge --no-ff TovaCohen-1623-tp4-user-doc
```

as now you've merged your commit from your feature branch to your repo's master and pushed that, you actually wanted it the other way.  I think you want to reset your fork's master:

1.  `git log` will show you pointers where `origin\master` and `upstream\master` is.  You want to copy the commit ID of the `upstream\master` pointer
1.  then do `git reset --hard <paste commit id here>`
1.  `git push -f` should reset `origin\master`
1.  now update against upstream: `git pull upstream master && git push` should work smoothly

I think at this stage it might be easier to grab the commit ID with your changes and cherry pick it to a new branch created off of master, so...

1.  `git checkout TovaCohen-1623-tp4-user-doc`
1.  `git log` and look for your commit, copy the commit ID
1.  `git checkout master`
1.  `git checkout -b my-new-feature-branch`
1.  `git cherry-pick <paste commit ID here>`

You may need to resolve conflicts on that last step, not 100% sure.

Also feel free to hit me up on IRC, we can do a bluejeans session if need be :-)

**Comment by gashcrumb** [comment]
Doh!  forgot, after you create a new feature branch, you can close this PR and then:

1.  `git push origin my-new-feature-branch`
1.  Create new PR for this work...

**Comment by TovaCohen** [comment]
Stan helped me straighten things out. I am about to create a new pull request from a new branch. So I'm closing this one. Thanks Stan!

**Pull request closed without merging**
