### PR TITLE
chore: upgrade apicurio to 0.2.40

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes [ENTESB-11759](https://issues.jboss.org/browse/ENTESB-11759)

### CODE REVIEW

**Comment by riccardo-forina** [comment]
This should not be backported I think, to avoid adding load on QA. Do you confirm @paoloantinori?

**Comment by paoloantinori** [comment]
yes, not backported. this was an activity planned for 7.6

**Comment by gashcrumb** [comment]
Ah, didn't see that, thanks!

**Comment by heiko-braun** [comment]
+1 on not backporting. This might carry unintended side effects.

**Pull request merged**
