### PR TITLE
chore(deps): update camel to 2.21.0.fuse-730042

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@rhuss looks like pure-bot is broken again

**Comment by rhuss** [comment]
Ok, I will check.

**Comment by rhuss** [comment]
@lburgazzoli Hmm, at least pure-bot tried:

```

2019-02-06T08:59:43.595Z	ERROR	github	webhook/webhook.go:162	webhook handler failed	{"error": "PUT https://api.github.com/repos/syndesisio/syndesis/pulls/4452/merge:  405 Pull Request is not mergeable []\nfailed to merge pull request https://github.com/syndesisio/syndesis/pull/4452\ngithub.com/syndesisio/pure-bot/pkg/webhook.mergePR\n\t/go/src/github.com/syndesisio/pure-bot/pkg/webhook/auto_merge.go:185\ngithub.com/syndesisio/pure-bot/pkg/webhook.(*autoMerger).handleStatusEvent\n\t/go/src/github.com/syndesisio/pure-bot/pkg/webhook/auto_merge.go:106\ngithub.com/syndesisio/pure-bot/pkg/webhook.(*autoMerger).HandleEvent\n\t/go/src/github.com/syndesisio/pure-bot/pkg/webhook/auto_merge.go:54\ngithub.com/syndesisio/pure-bot/pkg/webhook.NewGithubHTTPHandler.func1\n\t/go/src/github.com/syndesisio/pure-bot/pkg/webhook/webhook.go:156\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1918\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2254\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2619\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1801\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2337 "}
--
```

**Comment by rhuss** [comment]
It's GitHub which doesn't allow the merge for some reason.

**Comment by rhuss** [comment]
Might be a race condition (with check getting green and sending out the event)

**Pull request merged**
