### PR TITLE
Partial fix for #4248, strips external hidden secrets when importing connections

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
This is a partial fix since the UI also needs to be fixed to address #5582 and #5763.

**Comment by zregvart** [comment]
We could have also re-encrypted with a shared secret on export and re-encrypt with the instance encryption on import. This way we're potentially creating NullPointerExceptions when those properties are missing.

**Comment by dhirajsb** [comment]
@zregvart this fix surgically only removes auto-generated tokens, so it will let through clientId/clientSecret credentials for example. 
So there shouldn't be any null pointer exceptions, unless some connector only has auto-generated tokens and no user supplied configuration properties. 
I don't believe that's a valid scenario, since even the OAuth flow adds the shared clientId/clientSecret to the connection configuration. 
In the future we could add support for a shared secret on export/import to provide shared tokens for export/import calls.

**Comment by zregvart** [comment]
@dhirajsb this:

https://github.com/syndesisio/syndesis/pull/5765/files#diff-e8218eb21e549d14ee4e80c9d3beb3fdR475

removes the `refresh_token` property of the Salesforce connector:

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/salesforce/src/main/resources/META-INF/syndesis/connector/salesforce.json#L638-L651

`authenticationType` and `authorizationUrl` and `tokenUrl` from the gmail connector:

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json#L247-L278

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/gmail/src/main/resources/META-INF/syndesis/connector/gmail.json#L339-L353

`authorizationToken` from the telegram connector:

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/telegram/src/main/resources/META-INF/syndesis/connector/telegram.json#L82-L95

`refreshToken from the concur connector:

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/concur/src/main/resources/META-INF/syndesis/connector/concur-api.json#L3252-L3267

`authenticationType` and `authorizationUrl` and `tokenUrl` from the google calendar connector:

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json#L555-L586

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json#L647-L662

`authenticationType` and `authorizationUrl` and `tokenUrl` from the google sheets connector:

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json#L950-L981

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/google-sheets/src/main/resources/META-INF/syndesis/connector/sheets.json#L1081-L1096

`accessToken` and `accessTokenSecret` from the twitter connector:

https://github.com/syndesisio/syndesis/blob/0e818c23250be06c53901cb809ea155ba6646156/app/connector/twitter/src/main/resources/META-INF/syndesis/connector/twitter.json#L237-L264

Your assumption is wrong, please revert this.

**Pull request merged**
