### PR TITLE
refactor(dv): fix code checks

### PR DESCRIPTION
**Pull request by zregvart**
This re-enables code checks on data virtualization backend and fixes the
outstanding issues.

For duplicate classes on classpath, since Teiid bundles same classes in
multiple JARs I had to add additional exclusions.

Tomcat version was upgraded to 9.0.33 and JUnit Jupiter was upgraded to
5.6.2 to align versions with ones imported from (Spring) BOMs.

One change was unrelated to DV, in the rest-swagger connector dealing
with OAuth, as indicated by newer version of ErrorProne, so fixed here
to ease the upgrade.

Issues in DV mostly fail into these categories:
 - naming constants properly
 - marking immutable references as final
 - make sure proper resource usage
 - proper use of String::format
 - removal of raw types usage
 - proper use of exception assertion in tests
 - code style issues (formatting, unused or wildcard imports)

One change was more invasive: in `ServiceVdbGeneratorTest` several
unused parameters in `helpGenerateDdlForWithJoinType` method were
removed.

### CODE REVIEW

**Comment by blafond** [comment]
Is any of this intended to be backported to 1.10.x?

**Comment by zregvart** [comment]
> Is any of this intended to be backported to 1.10.x?

I hope not, though if you need it for easier backports I can tackle that as well...

**Comment by zregvart** [comment]
> > Is any of this intended to be backported to 1.10.x?
> 
> I hope not, though if you need it for easier backports I can tackle that as well...

Or... we can merge this after 1.10.0 release, so you don't have issues with backports to 1.10. from master...

**Comment by blafond** [comment]
k.. I can't speak for all of DV, but it wouldn't affect the LSP features in 1.10.x if it wasn't backported.

**Comment by zregvart** [comment]
Let's have a little more bake time on this, I'm in the process of going through the PMD issues so I'll have more to add here.

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Pull request merged**
