### PR TITLE
Cherry pick #7370 - fix(UI tests): Prevent problematic characters in naming of test tape files

### PR DESCRIPTION
**Pull request by matskiv**
Cherry-picking https://github.com/syndesisio/syndesis/pull/7370 into `1.8.x` branch to allow importing of the operator with go mod.
This solves import errors that can be seen [here](https://gist.github.com/matskiv/05d1fe01fbd9153186488f5128a95a0a).

More discussion, and a use case that benefits from this change can be seen in comments on the original PR (https://github.com/syndesisio/syndesis/pull/7370).

Ping @heiko-braun @gaughan

### CODE REVIEW

**Comment by heiko-braun** [comment]
@lgarciaaco @phantomjinx What do you think?

**Comment by heiko-braun** [comment]
I am reluctant to accept that into our product branch (1.8.x) without prior checks from ENG and QE

**Comment by zregvart** [comment]
@heiko-braun AFAIK this is about UI-Server integration tests, I think this has no impact at runtime. And it's about enabling folk on non Unix platforms to run those tests, or even checkout from git.

**Comment by heiko-braun** [comment]
thanks @zregvart

**Comment by matskiv** [comment]
@heiko-braun @zregvart Thank you guys!

**Pull request merged**
