### PR TITLE
fix: get an updated integration when editing its definition using the new API introduced in #5724

### PR DESCRIPTION
**Pull request by riccardo-forina**
Fixes https://github.com/syndesisio/syndesis/issues/5697

### CODE REVIEW

**Comment by riccardo-forina** [comment]
@zregvart I'm not sure if I'm doing something wrong, but I'm not getting the properly updated integration back from the API you added in #5724. Check the gif:

lost-integration-customization

So basically I have an existing API Provider based integration saved, I customize one of the operations - the GET /beers one - to add a Log step. Then I edit the definition, remove the DELETE operation, and call the new API to get the updated integration object. Here is a sample cURL copied from the dev tools: https://gist.github.com/riccardo-forina/e9ec2bef2bdb61a840b09880443f05e7
If you check the raw integration object, the Log step is there, but I get back the integration without the DELETE operation - correct - but also without the Log step - wrong.

**Comment by zregvart** [comment]
@riccardo-forina that should be `PUT` instead of `POST` for updating. I don't see those paths in the OpenAPI document so I guess that's the source of the confusion. We have `POST /api/v1/apis/generator` to create a _blank_ integration from the OpenAPI document and `PUT /api/v1/apis/generator` to update a  integration from the OpenAPI document. Both are multipart and accept the OpenAPI document in the `specification` part and the `PUT` one accepts `integration` part also.

**Comment by riccardo-forina** [comment]
It is a PUT in the attached gist

**Comment by zregvart** [comment]
I've found that the flow ID is set to `new-integration:flows...` it needs to be same as the value returned from `POST /api/v1/apis/generator` otherwise the matching of the flows from the given integration and the uploaded specification fails. So the end result is to remove the two flows generated from the GET and POST operations and add a new flow for the GET operation other than matching the two GET flows and performing a single update. Trying to figure out where this happens.

**Comment by gashcrumb** [comment]
Ah yeah, ideally when we create flow IDs they probably shouldn't make use of the integration ID at all or rely on it, it should just be a unique key like other ids.

**Comment by zregvart** [comment]
There's a `PUT /api/v1/apis/generator` instead of `POST /api/v1/apis/generator` when clicking `Next` on new API provider integration from scratch and the `integration` has the `id` of `new-integration` at that point.

**Comment by gashcrumb** [comment]
Yeah, at that point we're using that `new-integration` id to ensure that there's some Id field set for the integration as it's used in the routing.  That'll get deleted when we eventually create the integration, as at that point we do a POST with no ID if I recall correctly.

**Comment by riccardo-forina** [comment]
Correct.

**Comment by riccardo-forina** [comment]
Tested against latest BE, I think this is good to go.

**Pull request merged**
