### PR TITLE
chore: Update to AtlasMap 2.1.1

### PR DESCRIPTION
**Pull request by igarashitm**
https://issues.redhat.com/browse/ENTESB-15520

Updating from 2.0.10. Release notes:
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.0
* https://github.com/atlasmap/atlasmap/releases/tag/atlasmap-2.1.1

### CODE REVIEW

**Comment by gashcrumb** [comment]
@mcada FYI

**Comment by gashcrumb** [comment]
retest this please

**Comment by zregvart** [comment]
This [smoke test](https://github.com/syndesisio/syndesis-qe/blob/c0c2534c3eedba95140715853433c0f376b73b4e/ui-tests/src/test/resources/features/integrations/db-to-db.feature#L20-L69) fails with `NullPointerException` in the running integration.

[integration.log](https://github.com/syndesisio/syndesis/files/5816412/integration.log)

**Comment by gashcrumb** [comment]
Do you get that locally @igarashitm?

**Comment by igarashitm** [comment]
How can I run this test? the default `syndesis -c` runs fine and `syndesis integration-test` fails with `java.lang.NoClassDefFoundError: Could not initialize class io.syndesis.test.itest.SyndesisIntegrationTestSupport`

**Comment by zregvart** [comment]
> How can I run this test?

These are run from https://github.com/syndesisio/syndesis-qe not sure if it would be easier to export the integration project and troubleshoot that, I'm afraid if you do run the test it'll be ephemeral so you'll get the same log and not much else to go on. I find it easier to work with exported integration and debug it.

**Comment by mcada** [comment]
@asmigala Can you please look into it? AtlasMap updates break our tests quite often. This PR should be only merged together with a PR into QE tests with all necessary fixes (as stated in Jira ticket).

**Comment by asmigala** [comment]
@igarashitm  here's the exported integration in question: https://drive.google.com/file/d/1F8beEpva2ccjHhi18ofJDs1Tba4VlzrW/view?usp=sharing 

I'm trying to figure out whether it's an issue in the test suite, but the mapping looks ok in the UI

**Comment by asmigala** [comment]
Also not sure this is relevant but typing anything in the `Mapping Preview` field in data mapper results in `Internal Server Error` in the sidebar and the following in `syndesis-server` log:
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "attribute" (class io.atlasmap.json.v2.JsonField), not marked as ignorable (16 known properties: "path", "arrayDimensions", "primitive", "name", "value", "index", "docId", "fieldType", "format", "collectionType", "arraySize", "actions", "required", "typeName", "status", "userCreated"])
 at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 307] (through reference chain: io.atlasmap.v2.ProcessMappingRequest["mapping"]->io.atlasmap.v2.Mapping["inputField"]->java.util.ArrayList[0]->io.atlasmap.json.v2.JsonField["attribute"])
```

**Comment by igarashitm** [comment]
Not sure if this is the root cause of the test failure, but this is definitely a bug - https://github.com/atlasmap/atlasmap/issues/2528
> Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "attribute" (class io.atlasmap.json.v2.JsonField)

**Comment by igarashitm** [comment]
I'll re-submit at least after atlasmap/atlasmap#2528 is fixed

**Pull request closed without merging**
