### PR TITLE
feat: Design proposal for custom connectors

### PR DESCRIPTION
**Pull request by zregvart**
This is the initial design proposal for custom connectors.

### CODE REVIEW

**Comment by rhuss** [comment]
@zregvart is it already ready for review (as it is still marked as wip) ?

**Comment by zregvart** [comment]
> @zregvart is it already ready for review (as it is still marked as wip) ?

needs updating to the latest API in #450

**Comment by rhuss** [comment]
@zregvart ok, let me know when its good to go so I (or somebody else, too) can do the review.

**Comment by zregvart** [comment]
@rhuss I'm still not satisfied with the breadth of the design. I think it shows the most important aspects of that are needed for UI work and we can fill in the details when we see that this works in practice.

**Comment by rhuss** [comment]
Fine with that, going to review it later today ... (but hopefully before the meeting marathon this afternoon. If not then afterwards ...)

**Pull request merged**
