### PR TITLE
clean up integration list CSS including making body scrollable, fix padding issue in firefox

### PR DESCRIPTION
**Pull request by michael-coker**
fixes https://github.com/syndesisio/syndesis/issues/2118

### CODE REVIEW

**Comment by gashcrumb** [comment]
Did you mean to close this?

**Comment by michael-coker** [comment]
@gashcrumb yeah, I noticed after creating the PR that the scrollbars are in a weird position. Is it good practice to close a PR in a case like that, or leave it open and add a comment saying I'm still working on it?

**Comment by gashcrumb** [comment]
Yeah, you can label it wip and it won't merge, also you can pushore commits
to the branch etc

**Comment by michael-coker** [comment]
@gashcrumb thanks! It's ready - I pushed an update yesterday and re-opened.

**Comment by gashcrumb** [comment]
@michael-coker when you get a chance, can you maybe try rebasing this branch against master and do a force push?  Want to see if that clears up the CI errors or not...

**Comment by michael-coker** [comment]
@gashcrumb done

**Pull request merged**
