### PR TITLE
feat: Eliminate the atlasmap pod by embedding it’s rest services in the syndesis-rest pod.  Fixes #1308

### LINKED ISSUE #1308: Eliminate the atlasmap pod by embedding it’s rest services in the syndesis-rest pod.
Theres no good reason to isolate the atlasmap rest services in their own pod and take on the associated memory budget expense.  We should be able expose them as rest services from the syndesis-rest pod.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
This is wip since it needs a new release of atlasmap before it can be merged.

**Comment by chirino** [comment]
I think this PR is ready to go in now.  Keeping the wip label on it so it does not auto merge, would like a @rhuss to do quick review.  I think I'm missing updating the release scripts too.  Do you want me to try to handle that in this PR?

**Comment by zregvart** [comment]
Let's try this, seems straightforward. 👍 

@chirino there is a merge conflict would you mind rebasing?

**Comment by chirino** [comment]
rebased.

**Comment by rhuss** [comment]
@chirino Awesome ! Makes things much straight forwarder.

Still todo:

* Remove generration of atlasmap image from productised builds
* Remove from `syndesis release` (just working on it)

**Pull request merged**
