### PR TITLE
fix: monitoring/integrations OpenAPI definition

### LINKED ISSUE #4086: Endpoint /api/v1/monitoring/integrations missing in the internal swagger.json spec
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Endpoint `/api/v1/monitoring/integrations` is missing from the internal swagger.json file, the one downloadable at the URL `http://XXX/api/v1/internal/swagger.json`.

### PR DESCRIPTION
**Pull request by zregvart**
Adds the missing OpenAPI definition for the `/monitoring/integrations`
endpoint.

Fixes #4086

### CODE REVIEW

**Comment by zregvart** [comment]
retest this please

**Comment by zregvart** [comment]
retest this please

**Comment by mkralik3** [comment]
@zregvart You can ignore that 1 failed test. It is failing due to https://issues.redhat.com/browse/ENTESB-17748 (I will remote it from smoke tests)

**Comment by zregvart** [comment]
I don't think this is something we need for 1.13, so I'll park it for now.

**Pull request merged**
