### PR TITLE
fix: Slack connector

### PR DESCRIPTION
**Pull request by rohanmars**

### CODE REVIEW

**Comment by rhuss** [comment]
Can we get this PR merged today ? I'm asking over the weekend I'd like to make the final adjustment wrt to naming and modules, so conflicts are likely.

**Comment by lburgazzoli** [comment]
@rhuss I and @oscerd  are working on getting those connectors merged

**Comment by rhuss** [comment]
cool, thanks !

**Comment by oscerd** [comment]
Looking at this one, I already have everything aligned and slack channel set. But I'm blocked by this one https://github.com/syndesisio/syndesis/issues/1841

**Comment by oscerd** [comment]
Superseded by #1864

**Pull request closed without merging**
