### PR TITLE
Initial version of publishing status monitoring endpoint, fixes 2619 See comment in issue for details.

### LINKED ISSUE #2619: Backend - Give more details on the publishing process

### PR DESCRIPTION
**Pull request by dhirajsb**
fixes #2619

### CODE REVIEW

**Comment by gashcrumb** [comment]
This is safe to merge without the UI part right?  If so we should merge this today, I'll do a separate PR with the UI updates.

**Comment by dhirajsb** [comment]
@gashcrumb I refactored it a bit to make it easier in the ui to get current state details and steps. So the output of the query
```
https://syndesis.192.168.64.36.nip.io/api/v1/monitoring/integrations/i-LGd-g4Wto2emeUlMlEsz
```
is
```
{"detailedState":{"value":"BUILDING","currentStep":2,"totalSteps":4},"logsUrl":"https://openshift.default.svc/api/v1/namespaces/syndesis/pods/i-amqp-integration-12-build/logs","id":"i-LGd-g4Wto2emeUlMlEsz:7","integrationId":"i-LGd-g4Wto2emeUlMlEsz","deploymentVersion":7}
```
and the output of query
```
https://syndesis.192.168.64.36.nip.io/api/v1/monitoring/integrations/
```
is
```
[{"detailedState":{"value":"BUILDING","currentStep":2,"totalSteps":4},"logsUrl":"https://openshift.default.svc/api/v1/namespaces/syndesis/pods/i-amqp-integration-12-build/logs","id":"i-LGd-g4Wto2emeUlMlEsz:7","integrationId":"i-LGd-g4Wto2emeUlMlEsz","deploymentVersion":7}]
```

**Comment by dhirajsb** [comment]
@gashcrumb this is good to merge now!

**Comment by gashcrumb** [comment]
@dhirajsb perfect, I can work with this, thanks!

**Pull request merged**
