### PR TITLE
fix(datavirt): add tech preview popover to title text

### PR DESCRIPTION
**Pull request by mcoker**
fixes https://github.com/syndesisio/syndesis/issues/6055

### CODE REVIEW

**Comment by mcoker** [comment]
@riccardo-forina circleci failed, but I don't see any details. Do you know what I can do to fix it?

**Comment by riccardo-forina** [comment]
It was an error in some unrelated step. I relaunched the build, let’s see if it helps

**Comment by mcoker** [comment]
@riccardo-forina still failing :(

**Comment by riccardo-forina** [comment]
It must be something temporary, maybe some repo down. I’m on my mobile, it’s hard to check. Will try again tomorrow

**Comment by riccardo-forina** [comment]
@mcoker try rebasing this against latest master, it should fix the failing build.

**Comment by mcoker** [comment]
@riccardo-forina the build passed 🎉

**Pull request merged**
