### PR TITLE
ENTESB-11772: Fixes for outstanding errors

### PR DESCRIPTION
**Pull request by phantomjinx**
* Fixes the ENDPOINTS_TEST_SUPPORT_ENABLED var as it has been renamed
  to TEST_SUPPORT_ENABLED

* Sorts the parameters list

### CODE REVIEW

**Comment by zregvart** [comment]
Perhaps a better approach would be not to workaround the issue but fix the issue at the cause. And by that I mean either change this:

https://github.com/syndesisio/syndesis/blob/2fb60c6807ee526aab7d07bda10b48f39c4f7182/install/operator/pkg/syndesis/configuration/configuration.go#L28

To use `ENDPOINTS_TEST_SUPPORT_ENABLED`, or change this:

https://github.com/syndesisio/syndesis/blob/2fb60c6807ee526aab7d07bda10b48f39c4f7182/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/handler/tests/TestSupportHandler.java#L51

To be `test_support.enabled`.

With this the workaround would be applied to any `ENDPOINTS_` variable, which could cause issues in the future.

**Comment by zregvart** [comment]
> @zregvart
> I would agree with you but am not sure I can do that. The aim of the exercise is to cause the generate to produce a template that looks like [this](https://github.com/syndesisio/fuse-online-install/blob/1.7.x/resources/fuse-online-template-oh.yml#L1197) [](/syndesisio/fuse-online-install/blob/HEAD@{2019-10-17T15:18:24Z}/resources/fuse-online-template-oh.yml#L1197). Note. the template contains both the TEST_SUPPORT_ENABLED flag and the ENDPOINTS_TEST_SUPPORT_ENABLED variable.

I'm pretty sure, but I'll allow that I'm wrong, that template parameters are one time thing only, and with that yesterdays template doesn't have to bare any resemblance to the today's template.

If I'm wrong on this, perhaps the replacement could be made explicit by changing the string `ENDPOINTS_TEST_SUPPORT_ENABLED` to `TEST_SUPPORT_ENABLED`, to prevent future issues.

**Comment by phantomjinx** [comment]
> > @zregvart
> > I would agree with you but am not sure I can do that. The aim of the exercise is to cause the generate to produce a template that looks like [this](https://github.com/syndesisio/fuse-online-install/blob/1.7.x/resources/fuse-online-template-oh.yml#L1197) . Note. the template contains both the TEST_SUPPORT_ENABLED flag and the ENDPOINTS_TEST_SUPPORT_ENABLED variable.
> 
> I'm pretty sure, but I'll allow that I'm wrong, that template parameters are one time thing only, and with that yesterdays template doesn't have to bare any resemblance to the today's template.
> 
> If I'm wrong on this, perhaps the replacement could be made explicit by changing the string `ENDPOINTS_TEST_SUPPORT_ENABLED` to `TEST_SUPPORT_ENABLED`, to prevent future issues.

@chirino @lburgazzoli 
Are you able to give any steerage on this, please?

**Comment by lburgazzoli** [comment]
I have a very little knowledge about what the operator does nowadays but in term of naming, I think we should keep "endpoints." for property and "ENDPOINTS_" for env var as this is a quite common convention in spring boot.

**Comment by phantomjinx** [comment]
> I have a very little knowledge about what the operator does nowadays but in term of naming, I think we should keep "endpoints." for property and "ENDPOINTS_" for env var as this is a quite common convention in spring boot.

Sorry, @lburgazzoli, I actually meant to put in @lgarciaaco rather than yourself. However, my thanks for the contribution - much appreciated.

**Pull request merged**
