### PR TITLE
(backport-1.10.x)[PF4 migration] Added DataTestIds to activity, metrics and cicd pages

### PR DESCRIPTION
**Pull request by mkralik3**
Backport of https://github.com/syndesisio/syndesis/pull/8291 to 1.10.x

### CODE REVIEW

**Comment by mkralik3** [comment]
@kahboom  The change (the order of the imports) is already here.

**Comment by kahboom** [comment]
Thanks @mkralik3 , I've kicked off a new PR build. Not sure how to do that for the QE PR build though?

**Comment by mkralik3** [comment]
Thanks. It is need to write `retest this please` to the new comment. The smoke tests PR job will automatically run.

**Comment by mkralik3** [comment]
retest this please

**Comment by mkralik3** [comment]
retest this please

**Pull request merged**
