### PR TITLE
fix(5715,5729) and add empty state components for integration-related components

### PR DESCRIPTION
**Pull request by elvisisking**
- See #5715 and #5729 
- added empty state to dashboard's TopIntegrationCard
- added empty state to integrations list
- fixed issues in metrics page when not all metrics are available
- changed data helpers util to return '0 ms' when duration is zero.

### CODE REVIEW

**Comment by paoloantinori** [comment]
This is a blocker only Sprint. If this is not related to a corresponding blocker it won't be merged until the end of the sprint or the branching of the code.

**Comment by gashcrumb** [comment]
@elvisisking can you link this PR to the related issues?

**Comment by elvisisking** [comment]
@gashcrumb I've added a link to #5715 in description. The other issue, 427, is from the archived react repo (couldn't get link to work).

**Comment by gashcrumb** [comment]
Fixed that for ya :smile:

**Comment by gashcrumb** [comment]
@paoloantinori personally I kinda think syndesisio/syndesis-react#427 would be a blocker.

**Pull request merged**
