### PR TITLE
[ENTESB-13000] Adding "update" to description of put aws-ddb operation

### PR DESCRIPTION
**Pull request by Delawen**
Just a minor description update

### CODE REVIEW

**Comment by zregvart** [comment]
Why backport to 1.9.x?

**Comment by Delawen** [comment]
Because it was "insert or update" since the first release, which was 1.9.x if I'm not mistaken...

**Comment by zregvart** [comment]
@Delawen will there be another 1.9.x release?

**Comment by Delawen** [comment]
Probably not, you are right.

**Comment by Delawen** [comment]
Manually backporting...

**Pull request merged**
