### PR TITLE
ENTESB-11772: Generate a template from the operator configuration

### PR DESCRIPTION
**Pull request by phantomjinx**
* Parses the internal operator configuration and exports an openshift
  template

* install/install.go
 * Adds in the "forge" command for forging the template
 * eg. syndesis-operator install forge \
       --operator-config ./build/conf/config.yaml \
       --addons todo --eject yaml

* install-forge.go
 * Does the work of generating the new openshift template

* configuration.go
 * Enhances the config constants by mapping them to their descriptions,
   default values, whether required and whether generated

* template/install.go
 * Utilise the AllConfigMap for providing the default values

### CODE REVIEW

**Comment by phantomjinx** [comment]
Labelled as WIP at the moment in case major changes required.

**Comment by phantomjinx** [comment]
Execute command:
`syndesis-operator install forge --operator-config ./build/conf/config.yaml --addons todo --eject yaml`

Generates -> [syndesis.yml](https://gist.github.com/phantomjinx/0741e348b12510c562f3bf16d6e818ce)

**Comment by heiko-braun** [comment]
Pretty cool, thanks Paul

**Comment by phantomjinx** [comment]
> @lgarciaaco @phantomjinx Is there a reason not to merge to 1.8.x?

Just did a trial merge to 1.8.x local branch and seems straightforward so can backport if required.

@lgarciaaco
Does contain changes to the way default values are assigned. You may not want something like that backported. WDYT?

**Comment by heiko-braun** [comment]
@phantomjinx Can you create a PR manually? The bot doesn't seem to be capable of doing it.

**Pull request merged**
