### PR TITLE
#5978: Adding Teiid JDBC Driver to the connector-sql connector

### PR DESCRIPTION
**Pull request by rareddy**

### CODE REVIEW

**Comment by KurtStam** [comment]
@rareddy Looks like you forgot to check in the DbTeiid class. Looks good otherwise.

**Comment by rareddy** [comment]
arrg.. sorry, among many ".gitignore" files noise I missed it. I updated PR now.

**Comment by rareddy** [comment]
@KurtStam I have no idea what is failed as the circleci does not want to show what is the error it is failed on?

**Comment by zregvart** [comment]
There's an issue with maven.repository.redhat.com, [from CircleCI](https://circleci.com/gh/syndesisio/syndesis/111028):

```
[ERROR] Failed to execute goal com.hubspot.maven.plugins:dependency-scope-maven-plugin:0.8:check (basepom.default) on project meta: Error resolving descriptor for artifact com.atlassian.jira:jira-rest-java-client-api:5.1.2-2bd0a62e: Failed to read artifact descriptor for com.atlassian.jira:jira-rest-java-client-api:jar:5.1.2-2bd0a62e: Could not transfer artifact com.atlassian.jira:jira-rest-java-client-api:pom:5.1.2-2bd0a62e from/to redhat-ga (https://maven.repository.redhat.com/ga/): Failed to transfer file: https://maven.repository.redhat.com/ga/com/atlassian/jira/jira-rest-java-client-api/5.1.2-2bd0a62e/jira-rest-java-client-api-5.1.2-2bd0a62e.pom. Return code is: 500, ReasonPhrase: Internal Server Error. -> [Help 1]
```

**Comment by rareddy** [comment]
looks like pure-bot error?

**Pull request merged**
