### PR TITLE
chore(json): disable serialization of empty collections

### PR DESCRIPTION
**Pull request by lburgazzoli**
@gashcrumb here the new PR to get rid of empty collections

### CODE REVIEW

**Comment by gashcrumb** [comment]
tx!  working on this now...

**Comment by gashcrumb** [comment]
K, fixed up the UI to deal with that and rebased just in case, should be ready to go...

**Comment by lburgazzoli** [comment]
So let's try to remove the wip label and see what we'll break :)

**Comment by lburgazzoli** [comment]
@gashcrumb can you approve it ?

**Pull request merged**
