### PR TITLE
chore(ui): [ENTESB-16972] Upgrade to PF4

### PR DESCRIPTION
**Pull request by kahboom**
fixes [ENTESB-16972](https://issues.redhat.com/browse/ENTESB-16972)

### CODE REVIEW

**Comment by kahboom** [comment]
@zregvart the yarn and node versions used by maven are super old. it looks like there are some transitive dependencies that are not compatible with 10.15.1. wonder if it'd be worth it to pull the version bump from your PR into a separate one prior to getting this merged?

**Comment by zregvart** [comment]
> @zregvart the yarn and node versions used by maven are super old. it looks like there are some transitive dependencies that are not compatible with 10.15.1. wonder if it'd be worth it to pull the version bump from your PR into a separate one prior to getting this merged?

Not sure we would build, the `node-sass` native bits won't compile on Node.js != 10 from what I remember. That was kinda the start of the Angular update for Apicurio.

**Comment by gashcrumb** [comment]
Is there a more recent node LTS we could switch to?  I think `node-saas` ships binaries for LTS versions and relies on building on the fly during install for non-LTS node releases.

**Comment by zregvart** [comment]
I see several options:

1. lobby to get Apicurio released
2. try using [GitPkg](https://gitpkg.vercel.app/) (failing miserably atm)
3. add `git clone` and `yarn link` to the build
4. find a version of Node.js that lies at the intersection of Apicurio (node-sass) and Patternfly
5. resolve to a newer version of node-sass

**Comment by zregvart** [comment]
Another interesting conundrum, we're pulling in node-sass 4.14.1:

```
$ yarn why node-sass
yarn why v1.22.5
[1/4] Why do we have the module "node-sass"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@syndesis/apicurio-assembly#node-sass@4.11.0"
info Reasons this module exists
   - "_project_#@syndesis#apicurio-assembly#@angular-devkit#build-angular" depends on it
   - Hoisted from "_project_#@syndesis#apicurio-assembly#@angular-devkit#build-angular#node-sass"
   - in the nohoist list ["/_project_/@syndesis/apicurio-assembly/@angular*/**","/_project_/@syndesis/apicurio-assembly/@patternfly/patternfly","/_project_/@syndesis/apicurio-assembly/@types/node","/_project_/@syndesis/apicurio-assembly/@types/marked","/_project_/@syndesis/apicurio-assembly/apicurio-design-studio","/_project_/@syndesis/apicurio-assembly/oai-ts-core","/_project_/@syndesis/apicurio-assembly/oai-ts-commands","/_project_/@syndesis/apicurio-assembly/apicurio-ts-core","/_project_/@syndesis/apicurio-assembly/brace","/_project_/@syndesis/apicurio-assembly/core-js","/_project_/@syndesis/apicurio-assembly/js-yaml","/_project_/@syndesis/apicurio-assembly/marked","/_project_/@syndesis/apicurio-assembly/moment","/_project_/@syndesis/apicurio-assembly/bootstrap","/_project_/@syndesis/apicurio-assembly/ngx-bootstrap","/_project_/@syndesis/apicurio-assembly/ngx-clipboard","/_project_/@syndesis/apicurio-assembly/patternfly","/_project_/@syndesis/apicurio-assembly/pluralize","/_project_/@syndesis/apicurio-assembly/rxjs","/_project_/@syndesis/apicurio-assembly/zone.js","/_project_/@syndesis/apicurio-assembly/cp-cli","/_project_/@syndesis/apicurio-assembly/ng-packagr","/_project_/@syndesis/apicurio-assembly/ts-node","/_project_/@syndesis/apicurio-assembly/tsickle","/_project_/@syndesis/apicurio-assembly/tslib","/_project_/@syndesis/apicurio-assembly/typescript","/_project_/**/ngx-bootstrap","/_project_/**/jest","/_project_/**/rxjs"]
=> Found "@syndesis/apicurio-assembly#ng-packagr#node-sass@4.14.1"
info This module exists because "_project_#@syndesis#apicurio-assembly#ng-packagr" depends on it.
info Disk size without dependencies: "6.3MB"
info Disk size with unique dependencies: "12.75MB"
info Disk size with transitive dependencies: "24.09MB"
info Number of shared dependencies: 150
Done in 3.96s.
```

And that one is [supposed to work](https://github.com/sass/node-sass#node-version-support-policy) on Node.js 14. Spoiler, it does not.

I think the bit that helps us in the new Apicurio on Angular 11 is that node-sass was [marked as optional](https://github.com/angular/angular-cli/pull/5282), not that the node-sass/Node.js version makes it easy to install.

**Comment by zregvart** [comment]
We'll have a release of Apicurio this week, so we can get #9674 merged and then rebase this on that.

**Comment by kahboom** [comment]
Thanks @zregvart - In that case I'll leave this open until then, and at that point we can assess the feasibility of the React upgrade for [ENTESB-16973](https://issues.redhat.com/browse/ENTESB-16973).

**Comment by zregvart** [comment]
@kahboom we're now on Node.js 14 so this can be rebased to get merged :partying_face:

**Comment by kahboom** [comment]
@zregvart @gashcrumb Build failures appear to be related to this issue, and seem to be unrelated to the node version: https://github.com/developit/microbundle/issues/807

The overall build is failing because the Syndesis packages that consume another Syndesis package (i.e. `utils` consumes `auto-form`) are not able to find their type declaration files (or at least, rollup isn't able to). The type declaration files _are_ being generated for each package, which have a successful build, however, I noticed that they are quite nested for some reason, even if I manually remove `dist` directories prior to building.

Screen Shot 2021-07-19 at 12 06 01

It's unclear if this nesting was happening before. Also, it's unclear if it's the real problem, because even if I change the `typings` path to reflect this deeply nested level, the consumer package build still fails.

Would it be acceptable to disable `noImplicitAny` for packages that depend on other Syndesis packages for now? I believe the CI build fails if I attempt to disable it.

**Comment by zregvart** [comment]
> Would it be acceptable to disable `noImplicitAny` for packages that depend on other Syndesis packages for now? I believe the CI build fails if I attempt to disable it.

Let's use a workaround and track to remove it when this is fixed in microbundle.

**Comment by zregvart** [comment]
Should that `typings` be `dist/ui/src/ui/src/index.d.ts`?

**Comment by kahboom** [comment]
>Should that typings be dist/ui/src/ui/src/index.d.ts?

@zregvart - Yeah that's my point, that when I change the path to reflect the correct one (even though I'm confused why it didn't fail before), the build still fails. So, it seems like something has changed. Upon further investigation, it looks like it is automatically appending `ui/src` to the path. For example, in `package.json`, `"typings": "dist/index.d.ts"` generates `dist/ui/src/index.d.ts`, which is why every time I tried to update the path to be `dist/ui/src/index.d.ts` it kept nesting it further and further.

This didn't used to be a problem, or at least if it happened it didn't cause build failure. I'm testing updating the `typings` paths for each package to see if it fixes the build.

**Comment by zregvart** [comment]
> This didn't used to be a problem, or at least if it happened it didn't cause build failure. I'm testing updating the `typings` paths for each package to see if it fixes the build.

Very odd, looks like a bug, I'd go with a workaround for now to get this merged. Workaround should not be an issue if we're tracking this bug to make sure we remove it once the fix has been delivered.

**Comment by seanforyou23** [comment]
Good stuff @kahboom! I found a couple minor issues with stylesheet loading order and PF pkg version alignment between devDeps/peerDeps - I'm gonna take a crack at fixing those, rest of the changes look great!

**Comment by zregvart** [comment]
@kahboom @seanforyou23 can we get this merged and then address outstanding issues in followup PRs? This has been open for a while and now that the CI passes I don't want it to remain open for much long.

**Comment by seanforyou23** [comment]
Hey @zregvart! I'll defer to @kahboom on the incremental merge. There are some styling issues though. I'm working on this as we speak so the effort hasn't gone stale FWIW.

**Comment by seanforyou23** [comment]
Update: we recently learned the `@rh-uxd` pkg has been archived (which was used in both `@syndesis/syndesis` and `@syndesis/ui`), so anything related to that should go away. It's partly the cause of some of the styling issues we are seeing as it pulls in out of date versions of PF, so I'm inclined to say it would be a good idea to hold off on merging this until that's sorted. Should we close this one and open a new PR once the dust settles?

**Comment by gashcrumb** [comment]
@seanforyou23 I'd be more inclined to get this PR in now and then fix the remaining issues in smaller PRs, this is an ok time in the lifecycle to deal with the main branch being slightly unstable.

**Comment by seanforyou23** [comment]
Ok cool - sounds good to me, just wanted to put the disclaimer out there ;) - I'll continue working with @kahboom on the last bits, seems like we're getting close.

**Comment by zregvart** [comment]
Let's merge this.

**Pull request merged**
