### PR TITLE
Prototype for documenting syndesis CR

### PR DESCRIPTION
**Pull request by phantomjinx**
* Finds all pragmas used in the templates and attempts to then match the
  Syndesis paths to their equivalent types in the Syndesis object tree.

* Currently spits out simple list of those found. Need to determine how
  to meaningfully represent the data.

### CODE REVIEW

**Comment by phantomjinx** [comment]
Hey @lgarciaaco 
Got kinda bogged down in this so wanted to get a little feedback as to when (if anywhere) we go with it?

**Comment by heiko-braun** [comment]
> Currently spits out simple list of those found

@phantomjinx Can you add an example of what it generates?

**Comment by lgarciaaco** [comment]
@phantomjinx could you paste here the output and usage

**Comment by lgarciaaco** [comment]
isn't this kinda also creating documentation https://github.com/syndesisio/syndesis/pull/6745

**Comment by chirino** [comment]
rebased.

**Comment by phantomjinx** [comment]
Current Output extract from all templates & placed into a set of symbol objects (id, freq, defaultValue). The defaultValue is currently yet to be implemented.

```
Freq          Key
4               Images.Syndesis.Komodo          ''
4               Images.Syndesis.Rest            ''
4               Images.Syndesis.Ui              ''
1               Images.Syndesis.Upgrade         ''
4               Images.Syndesis.Verifier                ''
4               Syndesis.Namespace              'string'
1               Syndesis.Spec.Addons."komodo"."enabled"         'string, v1alpha1.Parameters'
2               Syndesis.Spec.Addons.jaeger.SAMPLER_TYPE "const"                'string, v1alpha1.Parameters'
4               Syndesis.Spec.Components.Db.Database            'string'
1               Syndesis.Spec.Components.Db.ImageStreamNamespace                'string'
2               Syndesis.Spec.Components.Db.Resources.Limits.Memory             'v1.ResourceName, resource.Quantity'
1               Syndesis.Spec.Components.Db.Resources.VolumeCapacity            'string'
5               Syndesis.Spec.Components.Db.User                'string'
1               Syndesis.Spec.Components.Komodo.Resources.Limits.Memory         'v1.ResourceName, resource.Quantity'
2               Syndesis.Spec.Components.Komodo.Tag             'string'
1               Syndesis.Spec.Components.Meta.Resources.Limits.Memory.String            'v1.ResourceName, resource.Quantity'
1               Syndesis.Spec.Components.Meta.Resources.VolumeCapacity          'string'
2               Syndesis.Spec.Components.Meta.Tag               'string'
2               Syndesis.Spec.Components.Oauth.Tag              'string'
2               Syndesis.Spec.Components.PostgresExporter.Tag           'string'
2               Syndesis.Spec.Components.Prometheus.Resources.Limits.Memory             'v1.ResourceName, resource.Quantity'
1               Syndesis.Spec.Components.Prometheus.Resources.VolumeCapacity            'string'
2               Syndesis.Spec.Components.Prometheus.Tag         'string'
6               Syndesis.Spec.Components.Scheduled              'bool'
1               Syndesis.Spec.Components.Server.Resources.Limits.Memory         'v1.ResourceName, resource.Quantity'
2               Syndesis.Spec.Components.Server.Tag             'string'
2               Syndesis.Spec.Components.UI.Tag         'string'
1               Syndesis.Spec.Components.Upgrade.Resources.VolumeCapacity               'string'
1               Syndesis.Spec.DemoData          'bool'
1               Syndesis.Spec.DeployIntegrations                'bool'
5               Syndesis.Spec.DevSupport                'bool'
8               Syndesis.Spec.ImageStreamNamespace              'string'
2               Syndesis.Spec.Integration.Limit         'int'
2               Syndesis.Spec.Integration.StateCheckInterval            'int'
1               Syndesis.Spec.OpenShiftConsoleUrl               'string'
1               Syndesis.Spec.OpenShiftMaster           'string'
8               Syndesis.Spec.Registry          'string'
9               Syndesis.Spec.RouteHostname             'string'
1               Syndesis.Spec.SarNamespace              'string'
1               Syndesis.Spec.TestSupport               'bool'
1               Syndesis.Status.TargetVersion           'string'
```

**Pull request closed without merging**
