### PR TITLE
chore(deps): upgrade testcontainers to 1.15.1

### PR DESCRIPTION
**Pull request by zregvart**
Not sure why we can't pull testcontainers/ryuk image in GitHub actions
perhaps upgrading testcontainers would help with this.

(cherry picked from commit 806c684faf2ef433e588bea4412a8d869533ca55)

```
# Conflicts:
#	app/pom.xml
```

### CODE REVIEW

**Comment by Delawen** [comment]
```Error:    AMQToHttp_IT>JUnit4CitrusTest.run:70->JUnit4CitrusTest.invokeTestMethod:102 » TestCaseFailed```

**Comment by zregvart** [comment]
> Error: AMQToHttp_IT>JUnit4CitrusTest.run:70->JUnit4CitrusTest.invokeTestMethod:102 » TestCaseFailed

Yeah, looks flaky, previous run took 6h until it got canceled.

**Review by oscerd — APPROVED** [review]
Docker api has been changed in version 1.41 and ryuk is not available anymore from what I understood.

**Comment by zregvart** [comment]
> Docker api has been changed in version 1.41 and ryuk is not available anymore from what I understood.

Thanks @oscerd, yeah, we made this change on `2.x` and it helped there, though the reasons why it stopped working were not that clear. Thanks for clearing that up.

**Pull request merged**
