### PR TITLE
Creating github files

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
Add github files in order to follow the good practice to work with opensource.  

## What
Add github files 

## Why
- Following the [opensource guide](https://opensource.guide/) recommendations and checklists for contributors choose a project to contribute with
- Help the users/contributor track properly an issue and a PR

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @zregvart,

Could you check this one?

**Comment by camilamacedo86** [comment]
Closing the PR

**Comment by zregvart** [comment]
@camilamacedo86 no need to close the PR, you can always push updates to your branch and have the changes reflected on the PR. Of course if it's easier on you feel free to open/close PRs to suit best your workflow.

**Comment by camilamacedo86** [comment]
Hi @zregvart I closed because I understanding that it is not required for you folks. Feel free to use your not the content of it.

**Pull request closed without merging**
