### PR TITLE
fix(operator): stateCheckInterval was not properly picked up by the operator

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by rhuss** [comment]
@avano Is a backport to 1.4.x required ? Not sure anymore whether we introduced this to allow to fix a blocker in 7.1)

**Comment by rhuss** [comment]
@heiko-braun @paoloantinori Could you please comment whether we should backport this fix to 7.1 ? It's about having a configuration option to prevent an endless redeployment of an integration in certain scenarios.

**Comment by heiko-braun** [comment]
@rhuss @avano I've changed to prio to blocker several days ago already. This needs to be merged to support QE testing.

**Comment by avano** [comment]
@heiko-braun thanks, sorry, I didn't notice that :-)

**Pull request merged**
