### PR TITLE
[fix] for ENTESB-15274 API Provider response is always 200 for 2xx re…

### PR DESCRIPTION
**Pull request by KurtStam**
…sponses

### CODE REVIEW

**Comment by squakez** [comment]
I noticed we worked on the same issue. This should have been already fixed via #9159

**Comment by mkralik3** [comment]
This PR #9194 resolved the issue ENTESB-15274, verified on the latest version 1.11.0-20201113. But the changes were not backported to the master yet. In that case (once the changes are in master), this issue can be closed.

**Comment by squakez** [comment]
> This PR #9194 resolved the issue ENTESB-15274, verified on the latest version 1.11.0-20201113. But the changes were not backported to the master yet. In that case (once the changes are in master), this issue can be closed.

It was backported via #9163 - https://github.com/syndesisio/syndesis/pull/9163/commits/52001c9841b8fac8b7e28964a832170256fcfc33

**Comment by mkralik3** [comment]
@squakez Sorry, my bad :man_facepalming: . I was checking master directly from the PR changes tab which is pointing to your fork master https://github.com/squakez/syndesis/blob/master/app/connector/api-provider/src/main/java/io/syndesis/connector/apiprovider/ApiProviderReturnPathCustomizer.java

**Comment by KurtStam** [comment]
@squakez In Camel-3 (on master) the exception is located elsewhere.

**Review by squakez — APPROVED** [review]
:+1:

**Pull request merged**
