### PR TITLE
Added public API OAuth proxy variables for productization

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
@zregvart @heiko-braun I added these variables for productization.

**Comment by dhirajsb** [comment]
@cunningt @djcoleman productization pipeline needs to set these to the same values as at https://github.com/syndesisio/syndesis/blob/1.6.x/install/generator/syndesis-template.go#L120-L149. 
At present the image seems to be set to 'registry.fuse-ignite.openshift.com/openshift/oauth-proxy:v1.1.0.

**Comment by heiko-braun** [comment]
@dhirajsb  i am unclear what you ask for. The oauth proxy version is mangwd externally here: https://github.com/syndesisio/fuse-online-install/blob/master/import_images.pl#L66

**Comment by dhirajsb** [comment]
@heiko-braun Syndesis mustache templates are modified by `syndesis-template.go` script to use productized images. 
But the public OAuth proxy template is standalone and needs to be modified for prod build, where these variables should be replaced to appropriate values.

**Comment by zregvart** [comment]
I guess we need another Syndesis release to pick this up, am I correct?

**Comment by heiko-braun** [comment]
@zregvart no, i think the build from this afternoon is fine. I have talked to @dhirajsb and what he said in https://github.com/syndesisio/syndesis/pull/5138#issuecomment-479900357 doesn't not need to be done. Is this correct @dhirajsb ?

**Pull request merged**
