### PR TITLE
bump prometheus version

### PR DESCRIPTION
**Pull request by lgarciaaco**
Fixes ENTESB-11840

### CODE REVIEW

**Comment by lgarciaaco** [comment]
test this please

**Comment by zregvart** [comment]
> test this please

@lgarciaaco rebase to get the #6813

**Comment by zregvart** [comment]
Also might be easier to do this against `master` and then backport to `1.8.x`

**Comment by lgarciaaco** [comment]
> Also might be easier to do this against `master` and then backport to `1.8.x`

It needs manual backport to master ...

**Comment by zregvart** [comment]
@lgarciaaco don't forget to update this on `master` also...

**Comment by avano** [comment]
@lgarciaaco for upstream, there is no `v3.9` tag: https://hub.docker.com/r/prom/prometheus/tags

**Pull request merged**
