### PR TITLE
feat(connectors): New Google-Calendar connector

### PR DESCRIPTION
**Pull request by oscerd**
Related to #3454 

The connector works fine, we still need to add additional options to the create and update operation, but the basic stuff is done.

I noticed that Atlasmap repors warning while parsing the Event model class from Google API, this is something to check for @igarashitm , a part the warnings and some options the connector is done.

### CODE REVIEW

**Comment by oscerd** [comment]
Still have to fix a couple of tests. Updating.

**Comment by zregvart** [comment]
I'm cc-ing @TovaCohen to have a look on the text in [Connector JSON](https://github.com/syndesisio/syndesis/blob/760096f17e5459eb5a5361f0c82bb7ce5943b6d0/app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json) and to be aware that this needs to be documented.
There's a user story on the Google Calendar epic in #3454.

**Comment by oscerd** [comment]
Sure, this is just the first version, but there is still place to have it improved and with different option.

**Comment by TovaCohen** [comment]
Thanks Zoran! I'll take a look.

**Pull request merged**
