### PR TITLE
[WIP] Splitter

### PR DESCRIPTION
**Pull request by iocanel**
An early early implementation of the split step. It's currently work in progress (its a working impl but the design isn't finalized yet).

### CODE REVIEW

**Comment by gashcrumb** [comment]
Thumbs up on the UI side at least :-)

**Comment by lburgazzoli** [comment]
@iocanel be aware of #1144 that has huge impact on this PR too :)

**Comment by lburgazzoli** [comment]
@iocanel fyi, a [SplitStepHandler](https://github.com/syndesisio/syndesis/blob/master/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SplitStepHandler.java) has already been implemented for the new integration runtime

**Comment by iocanel** [comment]
Yeah, I figured :-)

**Comment by iocanel** [comment]
Don't intend to spent more time on it. And since its optional, I'll close it.

**Pull request closed without merging**
