### PR TITLE
ENTESB-14314  Remove DV from the 7.8 release

### PR DESCRIPTION
**Pull request by vhalbert**
https://issues.redhat.com/projects/ENTESB/issues/ENTESB-14314

### CODE REVIEW

**Comment by vhalbert** [comment]
> Hey @vhalbert
> This is fine to merge but doesn't remove the dv addon functionality from the syndesis operator. If you like, you can update the PR or merge it as-is & I can take a look at the operator.

I'll update the PR to remove the addon.

**Comment by gashcrumb** [comment]
Also is the plan to remove the UI bits in this PR as well, or is the plan to do that in a follow-up?  

The main integration point in the UI code would be [here](https://github.com/syndesisio/syndesis/tree/master/app/ui-react/syndesis/src/modules/data) and it's entry in the [main nav](https://github.com/syndesisio/syndesis/blob/master/app/ui-react/syndesis/src/index.tsx#L112-L116) and then there's going to be leftover components in the `ui` and `api` packages.

**Comment by vhalbert** [comment]
> Also is the plan to remove the UI bits in this PR as well, or is the plan to do that in a follow-up?
> 
> The main integration point in the UI code would be [here](https://github.com/syndesisio/syndesis/tree/master/app/ui-react/syndesis/src/modules/data) and it's entry in the [main nav](https://github.com/syndesisio/syndesis/blob/master/app/ui-react/syndesis/src/index.tsx#L112-L116) and then there's going to be leftover components in the `ui` and `api` packages.

If its a easy as removing the "data" folder and deleting the single entry point, then sure.  Otherwise, I'll do it in 2 steps.

**Comment by gashcrumb** [comment]
It's worth a quick try to see if it'll pass the build, but I suspect it'll take some more cleanup work after removing those references before the `lint` step passes.

**Comment by vhalbert** [comment]
Create PR for removing the addons, did not include removal of UI bits, due to too many changes in this commit.

**Comment by KurtStam** [comment]
Just curious - why is this work done on the 1.11.x branch on not on master?

**Comment by vhalbert** [comment]
> @vhalbert Just curious - why is this work done on the 1.11.x branch on not on master?

This was already begun when originally it was just to remove from 7.8 and future 7.x releases.   And this is to get the prod builds fixed and building correctly in the DR phase.

**Comment by vhalbert** [comment]
@phantomjinx and/or @gashcrumb  removed the DV UI bits and the build was successful.  As to the QE build, not sure what will need to be done if if fails again (now that DV is being removed, kinda expect QE to fail in some places).

**Comment by gashcrumb** [comment]
@avano @mcada are there QE tests for the DV parts in syndesis that need to be disabled for this?

**Comment by avano** [comment]
@gashcrumb @vhalbert when deploying the images from this PR, the syndesis ui doesn't load with:

```
2.0b213bec.chunk.js:102 TypeError: Cannot read property 'dvUrl' of undefined
    at Object.children (main.ce6b60ea.chunk.js:1)
    at t.render (main.ce6b60ea.chunk.js:1)
    at Fa (2.0b213bec.chunk.js:102)
    at ja (2.0b213bec.chunk.js:102)
    at ms (2.0b213bec.chunk.js:102)
    at uc (2.0b213bec.chunk.js:102)
    at sc (2.0b213bec.chunk.js:102)
    at Qs (2.0b213bec.chunk.js:102)
    at 2.0b213bec.chunk.js:102
    at t.unstable_runWithPriority (2.0b213bec.chunk.js:110)
```

**Comment by gashcrumb** [comment]
Ah great thanks @avano, missed that in the test output, that'll definitely need to be fixed.  It's probably [this line](https://github.com/syndesisio/syndesis/blob/1.11.x/app/ui-react/syndesis/src/index.tsx#L61) but it'd be good to pull out the relevant code depending on it.  @vhalbert is @mdrillin around to help out with this?

**Comment by vhalbert** [comment]
> Ah great thanks @avano, missed that in the test output, that'll definitely need to be fixed. It's probably [this line](https://github.com/syndesisio/syndesis/blob/1.11.x/app/ui-react/syndesis/src/index.tsx#L61) but it'd be good to pull out the relevant code depending on it. @vhalbert is @mdrillin around to help out with this?

Does the monaco editor and related logic need to be pulled out?

**Comment by gashcrumb** [comment]
Yep.

**Comment by avano** [comment]
@gashcrumb unfortunately it isn't anywhere in the test output, the only artifact is the screenshot of the page and that is just an empty white page :grin: I'll ask around if that could be improved

**Comment by mdrillin** [comment]
@gashcrumb @vhalbert yeah I'm around if you need anything

**Pull request merged**
