### PR TITLE
fix: manage environment variables on publish

### PR DESCRIPTION
**Pull request by zregvart**
Instead of managing the environment variables, i.e. in this case removal
of environment variables, at the point the integration is updated this
manages the environment variables at the point of publishing by
examining environment variables of previous deployments and adding any
environment variables that are not present on the latest deployment to
the list of environment variables to remove.

Ref. https://issues.redhat.com/browse/ENTESB-17748

### CODE REVIEW

**Comment by zregvart** [comment]
@mkralik3 looking at the smoke test failure, and it's a bit of a low-resolution image in the report, the environment variable has name set to `ENV4ENV4NAMEUPDATED`, which would mean that this `input.clear()` did not clear the `input`, does that ring any bells to you?

https://github.com/syndesisio/syndesis-qe/blob/8cf8a2fb3076b9bca78f638b4d47042111703a31/ui-common/src/main/java/io/syndesis/qe/pages/integrations/editor/CreateIntegration.java#L118

**Comment by mkralik3** [comment]
@zregvart Probably. I will try it manually.

**Comment by mkralik3** [comment]
@zregvart  It works on Firefox. It looks that it doesn't work only on Chrome. I have found in the different part of the test suite that there are some other steps ( i recall some problems was also on macOS )
```
        input.sendKeys(Keys.chord(Keys.SHIFT, Keys.HOME));
        input.sendKeys(Keys.BACK_SPACE);
        input.clear();
```

anyway, the test passed so we can merge this PR.

**Comment by zregvart** [comment]
> @zregvart It works on Firefox. It looks that it doesn't work only on Chrome. I have found in the different part of the test suite that there are some other steps ( i recall some problems was also on macOS )

Could it be that the UI binds the value after the `.clear()` was invoked? So the order of events is:

1. `input.clear()`
2. React binds attribute to `value="ENV4"`
3. Additional keys are sent

Anyhow thank you for double checking this!

**Pull request merged**
