### PR TITLE
fix: add IVP titles for the API Provider pages

### LINKED ISSUE #3796: API Provider tooltip text
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Text displays as Provided API in a flow. 

## Expected behavior

It should read in the example below: "Add a new pet to the store"

## Screenshot

image

### LINKED ISSUE #3848: [API Provider] Operation name is missing from IVP when editing a flow
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When editing a flow for API provider integraiton, users can only rely on the page breadcrumb to tell which operation they're building the flow for. Operation name is not available in IVP. 

## Expected behavior

Operation name should appear beneath the integration name area in the IVP. See UX design [here](https://redhat.invisionapp.com/share/CBNWDY58AHG#/screens/318306622) for operation name location. 

screen shot 2018-10-15 at 3 37 05 pm

## Screenshot

Current implementation:

screen shot 2018-10-15 at 3 31 57 pm

### PR DESCRIPTION
**Pull request by riccardo-forina**
api-provider-ivp-titles

Closes #3848
Closes #3796

### CODE REVIEW

**Comment by dongniwang** [comment]
Looks good to me! 

cc: @gaughan

**Comment by gaughan** [comment]
@riccardo-forina "Provided API" text is still there as in #3796, no?

**Comment by riccardo-forina** [comment]
Ah, I didn't capture that. Yes, but only on the Operations page:

api-provider-ivp-provided-api

We can change it to something more fitting. Any suggestion?

**Comment by gaughan** [comment]
API Provider or Operations?

**Pull request merged**
