### PR TITLE
Add submodules

### PR DESCRIPTION
**Pull request by gashcrumb**
@rhuss @chirino @zregvart FYI...

### CODE REVIEW

**Comment by rhuss** [comment]
@gashcrumb awesome, thanks ! Let's wait a bit with the PR, as I think we are already trying to go via direct copy. I'm going to open an issue to discuss this (containing the results from our discussion yesterday).

**Comment by gashcrumb** [comment]
@rhuss This seemed like a pretty easy way to bootstrap this repo though, as it's trivial to switch the submodules to just regular directories containing files:

https://stackoverflow.com/questions/1759587/un-submodule-a-git-submodule

**Comment by zregvart** [comment]
Yeah I think we should approve this in order to work the CI tasks, or at least to try to create a Jenkins or Circle CI setup. Would be one more data point for our CI discussion.

**Comment by rhuss** [comment]
Let's merge ...

**Pull request merged**
