### PR TITLE
fix: Username should be displayed in header #2269

### PR DESCRIPTION
**Pull request by KurtStam**
This PR sets the OpenShift User that is logged in based on the UserPrincipal.

### CODE REVIEW

**Comment by zregvart** [comment]
@KurtStam does it work on your end, I'm getting an exception (OpenShift 3.7 on minishift from `syndesis minishift --full-reset`):

```
2018-04-10 08:22:04.203 ERROR [-,56b7d6578c16fe2a,56b7d6578c16fe2a,false] 1 --- [  XNIO-3 task-4] .s.e.v.h.e.SyndesisServerExceptionMapper : Internal Server Exception. Failure executing: GET at: https://openshift.default.svc/oapi/v1/users/developer . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:syndesis:syndesis-server" cannot get users at the cluster scope: User "system:serviceaccount:syndesis:syndesis-server" cannot get users at the cluster scope.

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://openshift.default.svc/oapi/v1/users/developer . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:syndesis:syndesis-server" cannot get users at the cluster scope: User "system:serviceaccount:syndesis:syndesis-server" cannot get users at the cluster scope.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:312) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:295) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:753) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:206) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:181) ~[kubernetes-client-2.4.1.jar!/:na]
	at io.syndesis.server.openshift.OpenShiftServiceImpl.whoAmI(OpenShiftServiceImpl.java:158) ~[server-openshift-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.handler.user.UserHandler.whoAmI(UserHandler.java:60) ~[server-endpoint-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
```

**Comment by KurtStam** [comment]
Hmm yeah looks like our service account can't do this. The issue is that the 'current-user' is the service-account, and the service account doesn't have enough privileges to lookup the user(s). I see two options:

1. increase privileges of the system account
2. Don't do a user lookup and return the username only.

@zregvart wdyt?

**Comment by zregvart** [comment]
I think we just fetch the username. We decided that we don't want to mandate that the user installing Syndesis has permissions to modify system groups, and I think that's what's needed to allow `syndesis-server` service account to fetch users:

```shell
$ oc policy who-can get users
Namespace: syndesis
Verb:      get
Resource:  users

Users:  system:admin
        system:serviceaccount:default:pvinstaller
        system:serviceaccount:kube-system:generic-garbage-collector
        system:serviceaccount:kube-system:namespace-controller

Groups: system:cluster-admins
        system:cluster-readers
        system:masters
```

**Comment by KurtStam** [comment]
@zregvart agreed. `api/v1/users/~` now responds

```
{
username: "developer"
}
```

**Pull request merged**
