### PR TITLE
Fixes ENTESB-14339, added SOAP Fault to output data shapes for SOAP connector

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by gashcrumb** [comment]
Guess the license needs to be fixed up in these files?

image

**Comment by dhirajsb** [comment]
@gashcrumb thanks, of course that error didn't show up in local build!

**Comment by Delawen** [comment]
This has the label WIP. Should we convert the PR to a WIP PR or is it ready to merge?

**Comment by dhirajsb** [comment]
@Delawen I had to update an integration test, I'm merging it now.

**Pull request merged**
