### PR TITLE
Port from #6619

### PR DESCRIPTION
**Pull request by Delawen**
Port from #6619

### CODE REVIEW

**Comment by zregvart** [comment]
@Delawen you can just add `backport 1.8.x` label to the pull request on master (#6619) and let the bot do the rest...

**Comment by Delawen** [comment]
Magic! :dancer:

**Comment by Delawen** [comment]
Nothing to compare, bot, both branches are the same.

**Comment by heiko-braun** [comment]
@Delawen The backport label needs to go onto the original PR that addresses master.

**Pull request merged**
