### PR TITLE
Fixes #2075: override dependencies from bom if present in extension json

### LINKED ISSUE #2075: Syndesis Maven Plugin duplicates dependencies
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I created a custom step extension project and ran the build which triggers the syndesis maven plugin to generate the json file. When looking at the json file I discovered the dependency entry duplicated but with different versions....one which was already in the source version of the json and then the new version taken from the pom.xml by the plugin.

## Expected behavior
I would have expected that the existing dependencies are reused in the json. In my case the 1.3-SNAPSHOT dependency should have been overwritten with the 1.3.0.fuse-000014 version instead of duplicating that dependency which makes no sense at all.

## Screenshot
The generated JSON: https://gist.github.com/lhein/e745970c811cc60da043668fb7c9466f
The Project POM: https://gist.github.com/lhein/04771457354513dfc330c568f2fa3bb0
The original json in my project sources: https://gist.github.com/lhein/0356471d7aacedb3f8ae0290a107ba3c

## Request and Response Data
not applicable

## API Endpoints and Schemas
not appilicable 

## Tasks involved / Steps to Reproduce
1. create a step extension project and enter version 1.3-SNAPSHOT as shown in the gists
2. edit the pom.xml and change the syndesis version to 1.3.0.fuse-000014
3. run the build to regenerate the json file and build the jar
4. open the jar and check the json

### PR DESCRIPTION
**Pull request by nicolaferraro**
Fixes #2075

### CODE REVIEW

**Comment by nicolaferraro** [comment]
retest this please

**Comment by nicolaferraro** [comment]
It seems there's a circleci outage

**Comment by rhuss** [comment]
yep, issue on the circleci side. @nicolaferraro  for retriggering the build with circleci you have to go to circleci and rerun the build from their UI. I just did this, not sure whether it will be reported back here.

**Comment by rhuss** [comment]
It's here were you could rerun the builds --> https://circleci.com/workflow-run/d9c09aa9-09ee-4b8a-9dfc-9d37f180c7ae

**Pull request merged**
