### PR TITLE
#8950: Enable OLM installation of camel-k

### PR DESCRIPTION
**Pull request by phantomjinx**
* First step towards default installation of camel-k
 ** Set Enabled flag to ALWAYS install camel-k addon
 ** Adds Olm stanza that will create a subscription to the
    community-operator camel-k 1.1.0.
 ** If a later version is required then first need to create a catalog
    source that targets appropriately

### CODE REVIEW

**Comment by squakez** [comment]
I have a question. How this behave if I previously have a camel k operator installed? will it just skip the OLM installation or produce any error?

**Comment by phantomjinx** [comment]
> I have a question. How this behave if I previously have a camel k operator installed? will it just skip the OLM installation or produce any error?

It will install a second operator based on the created subscription. If you have already installed a camel-k operator from OLM, ie. existing subscription, then the current framework does take account of this.

At this point, I made the minimum changes to get this to work but since camel-k is no longer going to be an addon then its install can be refactored to become a component and at that point checks for existing camel-k operators (as well as OLM subscriptions) can be better implemented.

WDYT?

**Comment by squakez** [comment]
Yeah, I feel that's the way we should proceed. However, since we're not yet completely ready to promote `camel-k` runtime, I think we should pause this PR for the moment.

**Comment by christophd** [comment]
adding WIP label as this PR is paused for the moment

**Pull request closed without merging**
