### PR TITLE
fix: scrolling fixed for Integration activity steps logs output

### PR DESCRIPTION
**Pull request by deeleman**

### CODE REVIEW

**Comment by deeleman** [comment]
@michael-coker What OS/browser combo are you using to test?

**Comment by michael-coker** [comment]
Mac/Chrome

**Comment by deeleman** [comment]
That's odd, I had no horizontal scrolling in my env. Probs you're spotting a non-wrappeable loooong line, where `word-wrap: break-word;` has no effect. In any event you're right, that `overflow` there is redundant. Thanks for noticing.

**Comment by deeleman** [comment]
I see. Now it's fixed anyways. :)

**Pull request merged**
