### PR TITLE
Removes temporary fix for Camel Salesforce issue ENTESB-9452

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
@janstey is there a recent camel build after ENTESB-9452 from prod 7.1.x branch? Perhaps the release version?

**Comment by zregvart** [comment]
I think we had a build of Camel version 2.21.0.fuse-710021. We need to wait for GA release, will be a bit of a chicken-and-egg situation I think.

See https://repository.jboss.org/nexus/#nexus-search;gav~~camel-salesforce~2.21.0.fuse-710021~~

cc @cunningt

**Comment by oscerd** [comment]
That version is pinned on origin Nexus. So it will be there for the time being.

**Comment by zregvart** [comment]
@dhirajsb, @oscerd I've pushed a commit to set the version of Camel to 2.21.0.fuse-710021 that contains the fix we patched locally, I think it's best we merge this so we don't forget it for the patch release.

**Comment by oscerd** [comment]
Let me know if you want me to approve and go ahead

**Comment by gaughan** [comment]
@zregvart sounds good, can we run the Kurts test case that failed previously @tplevko

**Comment by zregvart** [comment]
@oscerd your robot powers of approval are needed :robot:

**Comment by oscerd** [comment]
Here I am.

**Comment by zregvart** [comment]
Funny I've pushed Camel version to the PR branch, must have done something wrong, slapped `pr/wip` label again.

**Comment by zregvart** [comment]
@oscerd I missed the push to @dhirajsb's fork, now we have the commit here and I think it's good to go.

**Comment by tplevko** [comment]
@gaughan I will ask guys testing camel, whether the fix is present, as in Syndesis, we can verify this only with productized images. This really wasn't an issue with dev builds even for 7.1. With syndesis, we will first be able to test this once we get the prod builds (hopefully with camel version which will contain the fix).

**Pull request merged**
