### PR TITLE
Change binary name from operator to syndesis

### PR DESCRIPTION
**Pull request by lgarciaaco**
`operator` is very generic, change the binary to `syndesis`

@orpiske you tweak to some nods on your end.

### CODE REVIEW

**Comment by orpiske** [comment]
@lgarciaaco thanks, noted!

**Comment by asmigala** [comment]
@lgarciaaco won't it be kind of confusing, since there will now be two executables called `syndesis` ? The other being https://github.com/syndesisio/syndesis/blob/master/tools/bin/syndesis

**Comment by lgarciaaco** [comment]
> @lgarciaaco won't it be kind of confusing, since there will now be two executables called `syndesis` ? The other being https://github.com/syndesisio/syndesis/blob/master/tools/bin/syndesis

I dont know ... maybe. @heiko-braun ^^

**Comment by zregvart** [comment]
Needs a change here:

https://github.com/syndesisio/syndesis/blob/7a18a509fbdb70ad9c71c67f27af52d20a49fa73/install/operator/build/Dockerfile#L8

Also would be better to do these changes on `master` and then backport it to `1.8.x`

**Comment by lgarciaaco** [comment]
> Also would be better to do these changes on `master` and then backport it to `1.8.x`

ok, closing this doing it that way

**Pull request closed without merging**
