### PR TITLE
chore: add OLM manifests for version 1.9

### PR DESCRIPTION
**Pull request by zregvart**
I've copied from 1.7.0 manifests, adjusted the version where needed and
made sure that the permissions and the deployment config reflect the
current state for 1.9.

### CODE REVIEW

**Comment by lgarciaaco** [comment]
@zregvart 1.7.0 is not up to date, we even skipped a release. You rather want to copy from [downstream](https://github.com/jboss-fuse/fuse-online-operator/tree/private-devel-fuse-7.6-openshift-rhel-7/manifests/7.6.0) and change /Fuse Online/Syndesis/s and other tiny bits.

**Comment by heiko-braun** [comment]
@lgarciaaco You also need to restore the syndesis icon that I changed here: https://github.com/jboss-fuse/fuse-online-operator/commit/24dae12b6bf1af9b4227a3541ee42fb03d5bd03c

**Comment by zregvart** [comment]
The image here should be okay. I'm not 100% sure if we need a copy of the manifests here, we can have them at the [community-operators](https://github.com/operator-framework/community-operators/tree/master/community-operators/syndesis). Having them here is a bit confusing as you might think that making modifications here reflects on the operatorhub.io.

**Comment by lgarciaaco** [comment]
I have the work for [community operators](https://github.com/operator-framework/community-operators/tree/master/community-operators/syndesis) ready. I will wait for 1.9 to be released before I actually make the PR

**Comment by Delawen** [comment]
So.... pushing now?

**Comment by Delawen** [comment]
@lgarciaaco we have 1.9.0 release so you can do your PR

**Pull request merged**
