### PR TITLE
(backport) fix: rework the validation checking and tidy up

### PR DESCRIPTION
**Pull request by gashcrumb**
fixes ENTESB-13842

Backports https://github.com/syndesisio/syndesis/pull/8593

### CODE REVIEW

**Comment by kahboom** [comment]
retest this please

**Comment by gashcrumb** [comment]
retest this please

**Comment by kahboom** [comment]
retest this please

**Comment by avano** [comment]
retest this please

**Comment by gashcrumb** [comment]
retest this please

**Pull request merged**
